const Grade = require("../models/grade");

exports.createGrade = (req, res, next) => {
  const grade = new Grade({
    gradeNumber: req.body.gradeNumber,
    gradeLiter: req.body.gradeLiter,

    mondayFirstLessonFG: req.body.mondayFirstLessonFG,
    mondayFirstLessonTeacherFG: req.body.mondayFirstLessonTeacherFG,
    mondayFirstLessonClassroomFG: req.body.mondayFirstLessonClassroomFG,
    mondayFirstLessonSG: req.body.mondayFirstLessonSG,
    mondayFirstLessonTeacherSG: req.body.mondayFirstLessonTeacherSG,
    mondayFirstLessonClassroomSG: req.body.mondayFirstLessonClassroomSG,
    mondaySecondLessonFG: req.body.mondaySecondLessonFG,
    mondaySecondLessonTeacherFG: req.body.mondaySecondLessonTeacherFG,
    mondaySecondLessonClassroomFG: req.body.mondaySecondLessonClassroomFG,
    mondaySecondLessonSG: req.body.mondaySecondLessonSG,
    mondaySecondLessonTeacherSG: req.body.mondaySecondLessonTeacherSG,
    mondaySecondLessonClassroomSG: req.body.mondaySecondLessonClassroomSG,
    mondayThirdLessonFG: req.body.mondayThirdLessonFG,
    mondayThirdLessonTeacherFG: req.body.mondayThirdLessonTeacherFG,
    mondayThirdLessonClassroomFG: req.body.mondayThirdLessonClassroomFG,
    mondayThirdLessonSG: req.body.mondayThirdLessonSG,
    mondayThirdLessonTeacherSG: req.body.mondayThirdLessonTeacherSG,
    mondayThirdLessonClassroomSG: req.body.mondayThirdLessonClassroomSG,
    mondayFourthLessonFG: req.body.mondayFourthLessonFG,
    mondayFourthLessonTeacherFG: req.body.mondayFourthLessonTeacherFG,
    mondayFourthLessonClassroomFG: req.body.mondayFourthLessonClassroomFG,
    mondayFourthLessonSG: req.body.mondayFourthLessonSG,
    mondayFourthLessonTeacherSG: req.body.mondayFourthLessonTeacherSG,
    mondayFourthLessonClassroomSG: req.body.mondayFourthLessonClassroomSG,
    mondayFifthLessonFG: req.body.mondayFifthLessonFG,
    mondayFifthLessonTeacherFG: req.body.mondayFifthLessonTeacherFG,
    mondayFifthLessonClassroomFG: req.body.mondayFifthLessonClassroomFG,
    mondayFifthLessonSG: req.body.mondayFifthLessonSG,
    mondayFifthLessonTeacherSG: req.body.mondayFifthLessonTeacherSG,
    mondayFifthLessonClassroomSG: req.body.mondayFifthLessonClassroomSG,
    mondaySixthLessonFG: req.body.mondaySixthLessonFG,
    mondaySixthLessonTeacherFG: req.body.mondaySixthLessonTeacherFG,
    mondaySixthLessonClassroomFG: req.body.mondaySixthLessonClassroomFG,
    mondaySixthLessonSG: req.body.mondaySixthLessonSG,
    mondaySixthLessonTeacherSG: req.body.mondaySixthLessonTeacherSG,
    mondaySixthLessonClassroomSG: req.body.mondaySixthLessonClassroomSG,
    mondaySeventhLessonFG: req.body.mondaySeventhLessonFG,
    mondaySeventhLessonTeacherFG: req.body.mondaySeventhLessonTeacherFG,
    mondaySeventhLessonClassroomFG: req.body.mondaySeventhLessonClassroomFG,
    mondaySeventhLessonSG: req.body.mondaySeventhLessonSG,
    mondaySeventhLessonTeacherSG: req.body.mondaySeventhLessonTeacherSG,
    mondaySeventhLessonClassroomSG: req.body.mondaySeventhLessonClassroomSG,
    mondayEighthLessonFG: req.body.mondayEighthLessonFG,
    mondayEighthLessonTeacherFG: req.body.mondayEighthLessonTeacherFG,
    mondayEighthLessonClassroomFG: req.body.mondayEighthLessonClassroomFG,
    mondayEighthLessonSG: req.body.mondayEighthLessonSG,
    mondayEighthLessonTeacherSG: req.body.mondayEighthLessonTeacherSG,
    mondayEighthLessonClassroomSG: req.body.mondayEighthLessonClassroomSG,
    mondayNinthLessonFG: req.body.mondayNinthLessonFG,
    mondayNinthLessonTeacherFG: req.body.mondayNinthLessonTeacherFG,
    mondayNinthLessonClassroomFG: req.body.mondayNinthLessonClassroomFG,
    mondayNinthLessonSG: req.body.mondayNinthLessonSG,
    mondayNinthLessonTeacherSG: req.body.mondayNinthLessonTeacherSG,
    mondayNinthLessonClassroomSG: req.body.mondayNinthLessonClassroomSG,
    mondayTenthLessonFG: req.body.mondayTenthLessonFG,
    mondayTenthLessonTeacherFG: req.body.mondayTenthLessonTeacherFG,
    mondayTenthLessonClassroomFG: req.body.mondayTenthLessonClassroomFG,
    mondayTenthLessonSG: req.body.mondayTenthLessonSG,
    mondayTenthLessonTeacherSG: req.body.mondayTenthLessonTeacherSG,
    mondayTenthLessonClassroomSG: req.body.mondayTenthLessonClassroomSG,
    tuesdayFirstLessonFG: req.body.tuesdayFirstLessonFG,
    tuesdayFirstLessonTeacherFG: req.body.tuesdayFirstLessonTeacherFG,
    tuesdayFirstLessonClassroomFG: req.body.tuesdayFirstLessonClassroomFG,
    tuesdayFirstLessonSG: req.body.tuesdayFirstLessonSG,
    tuesdayFirstLessonTeacherSG: req.body.tuesdayFirstLessonTeacherSG,
    tuesdayFirstLessonClassroomSG: req.body.tuesdayFirstLessonClassroomSG,
    tuesdaySecondLessonFG: req.body.tuesdaySecondLessonFG,
    tuesdaySecondLessonTeacherFG: req.body.tuesdaySecondLessonTeacherFG,
    tuesdaySecondLessonClassroomFG: req.body.tuesdaySecondLessonClassroomFG,
    tuesdaySecondLessonSG: req.body.tuesdaySecondLessonSG,
    tuesdaySecondLessonTeacherSG: req.body.tuesdaySecondLessonTeacherSG,
    tuesdaySecondLessonClassroomSG: req.body.tuesdaySecondLessonClassroomSG,
    tuesdayThirdLessonFG: req.body.tuesdayThirdLessonFG,
    tuesdayThirdLessonTeacherFG: req.body.tuesdayThirdLessonTeacherFG,
    tuesdayThirdLessonClassroomFG: req.body.tuesdayThirdLessonClassroomFG,
    tuesdayThirdLessonSG: req.body.tuesdayThirdLessonSG,
    tuesdayThirdLessonTeacherSG: req.body.tuesdayThirdLessonTeacherSG,
    tuesdayThirdLessonClassroomSG: req.body.tuesdayThirdLessonClassroomSG,
    tuesdayFourthLessonFG: req.body.tuesdayFourthLessonFG,
    tuesdayFourthLessonTeacherFG: req.body.tuesdayFourthLessonTeacherFG,
    tuesdayFourthLessonClassroomFG: req.body.tuesdayFourthLessonClassroomFG,
    tuesdayFourthLessonSG: req.body.tuesdayFourthLessonSG,
    tuesdayFourthLessonTeacherSG: req.body.tuesdayFourthLessonTeacherSG,
    tuesdayFourthLessonClassroomSG: req.body.tuesdayFourthLessonClassroomSG,
    tuesdayFifthLessonFG: req.body.tuesdayFifthLessonFG,
    tuesdayFifthLessonTeacherFG: req.body.tuesdayFifthLessonTeacherFG,
    tuesdayFifthLessonClassroomFG: req.body.tuesdayFifthLessonClassroomFG,
    tuesdayFifthLessonSG: req.body.tuesdayFifthLessonSG,
    tuesdayFifthLessonTeacherSG: req.body.tuesdayFifthLessonTeacherSG,
    tuesdayFifthLessonClassroomSG: req.body.tuesdayFifthLessonClassroomSG,
    tuesdaySixthLessonFG: req.body.tuesdaySixthLessonFG,
    tuesdaySixthLessonTeacherFG: req.body.tuesdaySixthLessonTeacherFG,
    tuesdaySixthLessonClassroomFG: req.body.tuesdaySixthLessonClassroomFG,
    tuesdaySixthLessonSG: req.body.tuesdaySixthLessonSG,
    tuesdaySixthLessonTeacherSG: req.body.tuesdaySixthLessonTeacherSG,
    tuesdaySixthLessonClassroomSG: req.body.tuesdaySixthLessonClassroomSG,
    tuesdaySeventhLessonFG: req.body.tuesdaySeventhLessonFG,
    tuesdaySeventhLessonTeacherFG: req.body.tuesdaySeventhLessonTeacherFG,
    tuesdaySeventhLessonClassroomFG: req.body.tuesdaySeventhLessonClassroomFG,
    tuesdaySeventhLessonSG: req.body.tuesdaySeventhLessonSG,
    tuesdaySeventhLessonTeacherSG: req.body.tuesdaySeventhLessonTeacherSG,
    tuesdaySeventhLessonClassroomSG: req.body.tuesdaySeventhLessonClassroomSG,
    tuesdayEighthLessonFG: req.body.tuesdayEighthLessonFG,
    tuesdayEighthLessonTeacherFG: req.body.tuesdayEighthLessonTeacherFG,
    tuesdayEighthLessonClassroomFG: req.body.tuesdayEighthLessonClassroomFG,
    tuesdayEighthLessonSG: req.body.tuesdayEighthLessonSG,
    tuesdayEighthLessonTeacherSG: req.body.tuesdayEighthLessonTeacherSG,
    tuesdayEighthLessonClassroomSG: req.body.tuesdayEighthLessonClassroomSG,
    tuesdayNinthLessonFG: req.body.tuesdayNinthLessonFG,
    tuesdayNinthLessonTeacherFG: req.body.tuesdayNinthLessonTeacherFG,
    tuesdayNinthLessonClassroomFG: req.body.tuesdayNinthLessonClassroomFG,
    tuesdayNinthLessonSG: req.body.tuesdayNinthLessonSG,
    tuesdayNinthLessonTeacherSG: req.body.tuesdayNinthLessonTeacherSG,
    tuesdayNinthLessonClassroomSG: req.body.tuesdayNinthLessonClassroomSG,
    tuesdayTenthLessonFG: req.body.tuesdayTenthLessonFG,
    tuesdayTenthLessonTeacherFG: req.body.tuesdayTenthLessonTeacherFG,
    tuesdayTenthLessonClassroomFG: req.body.tuesdayTenthLessonClassroomFG,
    tuesdayTenthLessonSG: req.body.tuesdayTenthLessonSG,
    tuesdayTenthLessonTeacherSG: req.body.tuesdayTenthLessonTeacherSG,
    tuesdayTenthLessonClassroomSG: req.body.tuesdayTenthLessonClassroomSG,

    wednesdayFirstLessonFG: req.body.wednesdayFirstLessonFG,
    wednesdayFirstLessonTeacherFG: req.body.wednesdayFirstLessonTeacherFG,
    wednesdayFirstLessonClassroomFG: req.body.wednesdayFirstLessonClassroomFG,
    wednesdayFirstLessonSG: req.body.wednesdayFirstLessonSG,
    wednesdayFirstLessonTeacherSG: req.body.wednesdayFirstLessonTeacherSG,
    wednesdayFirstLessonClassroomSG: req.body.wednesdayFirstLessonClassroomSG,
    wednesdaySecondLessonFG: req.body.wednesdaySecondLessonFG,
    wednesdaySecondLessonTeacherFG: req.body.wednesdaySecondLessonTeacherFG,
    wednesdaySecondLessonClassroomFG: req.body.wednesdaySecondLessonClassroomFG,
    wednesdaySecondLessonSG: req.body.wednesdaySecondLessonSG,
    wednesdaySecondLessonTeacherSG: req.body.wednesdaySecondLessonTeacherSG,
    wednesdaySecondLessonClassroomSG: req.body.wednesdaySecondLessonClassroomSG,
    wednesdayThirdLessonFG: req.body.wednesdayThirdLessonFG,
    wednesdayThirdLessonTeacherFG: req.body.wednesdayThirdLessonTeacherFG,
    wednesdayThirdLessonClassroomFG: req.body.wednesdayThirdLessonClassroomFG,
    wednesdayThirdLessonSG: req.body.wednesdayThirdLessonSG,
    wednesdayThirdLessonTeacherSG: req.body.wednesdayThirdLessonTeacherSG,
    wednesdayThirdLessonClassroomSG: req.body.wednesdayThirdLessonClassroomSG,
    wednesdayFourthLessonFG: req.body.wednesdayFourthLessonFG,
    wednesdayFourthLessonTeacherFG: req.body.wednesdayFourthLessonTeacherFG,
    wednesdayFourthLessonClassroomFG: req.body.wednesdayFourthLessonClassroomFG,
    wednesdayFourthLessonSG: req.body.wednesdayFourthLessonSG,
    wednesdayFourthLessonTeacherSG: req.body.wednesdayFourthLessonTeacherSG,
    wednesdayFourthLessonClassroomSG: req.body.wednesdayFourthLessonClassroomSG,
    wednesdayFifthLessonFG: req.body.wednesdayFifthLessonFG,
    wednesdayFifthLessonTeacherFG: req.body.wednesdayFifthLessonTeacherFG,
    wednesdayFifthLessonClassroomFG: req.body.wednesdayFifthLessonClassroomFG,
    wednesdayFifthLessonSG: req.body.wednesdayFifthLessonSG,
    wednesdayFifthLessonTeacherSG: req.body.wednesdayFifthLessonTeacherSG,
    wednesdayFifthLessonClassroomSG: req.body.wednesdayFifthLessonClassroomSG,
    wednesdaySixthLessonFG: req.body.wednesdaySixthLessonFG,
    wednesdaySixthLessonTeacherFG: req.body.wednesdaySixthLessonTeacherFG,
    wednesdaySixthLessonClassroomFG: req.body.wednesdaySixthLessonClassroomFG,
    wednesdaySixthLessonSG: req.body.wednesdaySixthLessonSG,
    wednesdaySixthLessonTeacherSG: req.body.wednesdaySixthLessonTeacherSG,
    wednesdaySixthLessonClassroomSG: req.body.wednesdaySixthLessonClassroomSG,
    wednesdaySeventhLessonFG: req.body.wednesdaySeventhLessonFG,
    wednesdaySeventhLessonTeacherFG: req.body.wednesdaySeventhLessonTeacherFG,
    wednesdaySeventhLessonClassroomFG: req.body.wednesdaySeventhLessonClassroomFG,
    wednesdaySeventhLessonSG: req.body.wednesdaySeventhLessonSG,
    wednesdaySeventhLessonTeacherSG: req.body.wednesdaySeventhLessonTeacherSG,
    wednesdaySeventhLessonClassroomSG: req.body.wednesdaySeventhLessonClassroomSG,
    wednesdayEighthLessonFG: req.body.wednesdayEighthLessonFG,
    wednesdayEighthLessonTeacherFG: req.body.wednesdayEighthLessonTeacherFG,
    wednesdayEighthLessonClassroomFG: req.body.wednesdayEighthLessonClassroomFG,
    wednesdayEighthLessonSG: req.body.wednesdayEighthLessonSG,
    wednesdayEighthLessonTeacherSG: req.body.wednesdayEighthLessonTeacherSG,
    wednesdayEighthLessonClassroomSG: req.body.wednesdayEighthLessonClassroomSG,
    wednesdayNinthLessonFG: req.body.wednesdayNinthLessonFG,
    wednesdayNinthLessonTeacherFG: req.body.wednesdayNinthLessonTeacherFG,
    wednesdayNinthLessonClassroomFG: req.body.wednesdayNinthLessonClassroomFG,
    wednesdayNinthLessonSG: req.body.wednesdayNinthLessonSG,
    wednesdayNinthLessonTeacherSG: req.body.wednesdayNinthLessonTeacherSG,
    wednesdayNinthLessonClassroomSG: req.body.wednesdayNinthLessonClassroomSG,
    wednesdayTenthLessonFG: req.body.wednesdayTenthLessonFG,
    wednesdayTenthLessonTeacherFG: req.body.wednesdayTenthLessonTeacherFG,
    wednesdayTenthLessonClassroomFG: req.body.wednesdayTenthLessonClassroomFG,
    wednesdayTenthLessonSG: req.body.wednesdayTenthLessonSG,
    wednesdayTenthLessonTeacherSG: req.body.wednesdayTenthLessonTeacherSG,
    wednesdayTenthLessonClassroomSG: req.body.wednesdayTenthLessonClassroomSG,

    thursdayFirstLessonFG: req.body.thursdayFirstLessonFG,
    thursdayFirstLessonTeacherFG: req.body.thursdayFirstLessonTeacherFG,
    thursdayFirstLessonClassroomFG: req.body.thursdayFirstLessonClassroomFG,
    thursdayFirstLessonSG: req.body.thursdayFirstLessonSG,
    thursdayFirstLessonTeacherSG: req.body.thursdayFirstLessonTeacherSG,
    thursdayFirstLessonClassroomSG: req.body.thursdayFirstLessonClassroomSG,
    thursdaySecondLessonFG: req.body.thursdaySecondLessonFG,
    thursdaySecondLessonTeacherFG: req.body.thursdaySecondLessonTeacherFG,
    thursdaySecondLessonClassroomFG: req.body.thursdaySecondLessonClassroomFG,
    thursdaySecondLessonSG: req.body.thursdaySecondLessonSG,
    thursdaySecondLessonTeacherSG: req.body.thursdaySecondLessonTeacherSG,
    thursdaySecondLessonClassroomSG: req.body.thursdaySecondLessonClassroomSG,
    thursdayThirdLessonFG: req.body.thursdayThirdLessonFG,
    thursdayThirdLessonTeacherFG: req.body.thursdayThirdLessonTeacherFG,
    thursdayThirdLessonClassroomFG: req.body.thursdayThirdLessonClassroomFG,
    thursdayThirdLessonSG: req.body.thursdayThirdLessonSG,
    thursdayThirdLessonTeacherSG: req.body.thursdayThirdLessonTeacherSG,
    thursdayThirdLessonClassroomSG: req.body.thursdayThirdLessonClassroomSG,
    thursdayFourthLessonFG: req.body.thursdayFourthLessonFG,
    thursdayFourthLessonTeacherFG: req.body.thursdayFourthLessonTeacherFG,
    thursdayFourthLessonClassroomFG: req.body.thursdayFourthLessonClassroomFG,
    thursdayFourthLessonSG: req.body.thursdayFourthLessonSG,
    thursdayFourthLessonTeacherSG: req.body.thursdayFourthLessonTeacherSG,
    thursdayFourthLessonClassroomSG: req.body.thursdayFourthLessonClassroomSG,
    thursdayFifthLessonFG: req.body.thursdayFifthLessonFG,
    thursdayFifthLessonTeacherFG: req.body.thursdayFifthLessonTeacherFG,
    thursdayFifthLessonClassroomFG: req.body.thursdayFifthLessonClassroomFG,
    thursdayFifthLessonSG: req.body.thursdayFifthLessonSG,
    thursdayFifthLessonTeacherSG: req.body.thursdayFifthLessonTeacherSG,
    thursdayFifthLessonClassroomSG: req.body.thursdayFifthLessonClassroomSG,
    thursdaySixthLessonFG: req.body.thursdaySixthLessonFG,
    thursdaySixthLessonTeacherFG: req.body.thursdaySixthLessonTeacherFG,
    thursdaySixthLessonClassroomFG: req.body.thursdaySixthLessonClassroomFG,
    thursdaySixthLessonSG: req.body.thursdaySixthLessonSG,
    thursdaySixthLessonTeacherSG: req.body.thursdaySixthLessonTeacherSG,
    thursdaySixthLessonClassroomSG: req.body.thursdaySixthLessonClassroomSG,
    thursdaySeventhLessonFG: req.body.thursdaySeventhLessonFG,
    thursdaySeventhLessonTeacherFG: req.body.thursdaySeventhLessonTeacherFG,
    thursdaySeventhLessonClassroomFG: req.body.thursdaySeventhLessonClassroomFG,
    thursdaySeventhLessonSG: req.body.thursdaySeventhLessonSG,
    thursdaySeventhLessonTeacherSG: req.body.thursdaySeventhLessonTeacherSG,
    thursdaySeventhLessonClassroomSG: req.body.thursdaySeventhLessonClassroomSG,
    thursdayEighthLessonFG: req.body.thursdayEighthLessonFG,
    thursdayEighthLessonTeacherFG: req.body.thursdayEighthLessonTeacherFG,
    thursdayEighthLessonClassroomFG: req.body.thursdayEighthLessonClassroomFG,
    thursdayEighthLessonSG: req.body.thursdayEighthLessonSG,
    thursdayEighthLessonTeacherSG: req.body.thursdayEighthLessonTeacherSG,
    thursdayEighthLessonClassroomSG: req.body.thursdayEighthLessonClassroomSG,
    thursdayNinthLessonFG: req.body.thursdayNinthLessonFG,
    thursdayNinthLessonTeacherFG: req.body.thursdayNinthLessonTeacherFG,
    thursdayNinthLessonClassroomFG: req.body.thursdayNinthLessonClassroomFG,
    thursdayNinthLessonSG: req.body.thursdayNinthLessonSG,
    thursdayNinthLessonTeacherSG: req.body.thursdayNinthLessonTeacherSG,
    thursdayNinthLessonClassroomSG: req.body.thursdayNinthLessonClassroomSG,
    thursdayTenthLessonFG: req.body.thursdayTenthLessonFG,
    thursdayTenthLessonTeacherFG: req.body.thursdayTenthLessonTeacherFG,
    thursdayTenthLessonClassroomFG: req.body.thursdayTenthLessonClassroomFG,
    thursdayTenthLessonSG: req.body.thursdayTenthLessonSG,
    thursdayTenthLessonTeacherSG: req.body.thursdayTenthLessonTeacherSG,
    thursdayTenthLessonClassroomSG: req.body.thursdayTenthLessonClassroomSG,

    fridayFirstLessonFG: req.body.fridayFirstLessonFG,
    fridayFirstLessonTeacherFG: req.body.fridayFirstLessonTeacherFG,
    fridayFirstLessonClassroomFG: req.body.fridayFirstLessonClassroomFG,
    fridayFirstLessonSG: req.body.fridayFirstLessonSG,
    fridayFirstLessonTeacherSG: req.body.fridayFirstLessonTeacherSG,
    fridayFirstLessonClassroomSG: req.body.fridayFirstLessonClassroomSG,
    fridaySecondLessonFG: req.body.fridaySecondLessonFG,
    fridaySecondLessonTeacherFG: req.body.fridaySecondLessonTeacherFG,
    fridaySecondLessonClassroomFG: req.body.fridaySecondLessonClassroomFG,
    fridaySecondLessonSG: req.body.fridaySecondLessonSG,
    fridaySecondLessonTeacherSG: req.body.fridaySecondLessonTeacherSG,
    fridaySecondLessonClassroomSG: req.body.fridaySecondLessonClassroomSG,
    fridayThirdLessonFG: req.body.fridayThirdLessonFG,
    fridayThirdLessonTeacherFG: req.body.fridayThirdLessonTeacherFG,
    fridayThirdLessonClassroomFG: req.body.fridayThirdLessonClassroomFG,
    fridayThirdLessonSG: req.body.fridayThirdLessonSG,
    fridayThirdLessonTeacherSG: req.body.fridayThirdLessonTeacherSG,
    fridayThirdLessonClassroomSG: req.body.fridayThirdLessonClassroomSG,
    fridayFourthLessonFG: req.body.fridayFourthLessonFG,
    fridayFourthLessonTeacherFG: req.body.fridayFourthLessonTeacherFG,
    fridayFourthLessonClassroomFG: req.body.fridayFourthLessonClassroomFG,
    fridayFourthLessonSG: req.body.fridayFourthLessonSG,
    fridayFourthLessonTeacherSG: req.body.fridayFourthLessonTeacherSG,
    fridayFourthLessonClassroomSG: req.body.fridayFourthLessonClassroomSG,
    fridayFifthLessonFG: req.body.fridayFifthLessonFG,
    fridayFifthLessonTeacherFG: req.body.fridayFifthLessonTeacherFG,
    fridayFifthLessonClassroomFG: req.body.fridayFifthLessonClassroomFG,
    fridayFifthLessonSG: req.body.fridayFifthLessonSG,
    fridayFifthLessonTeacherSG: req.body.fridayFifthLessonTeacherSG,
    fridayFifthLessonClassroomSG: req.body.fridayFifthLessonClassroomSG,
    fridaySixthLessonFG: req.body.fridaySixthLessonFG,
    fridaySixthLessonTeacherFG: req.body.fridaySixthLessonTeacherFG,
    fridaySixthLessonClassroomFG: req.body.fridaySixthLessonClassroomFG,
    fridaySixthLessonSG: req.body.fridaySixthLessonSG,
    fridaySixthLessonTeacherSG: req.body.fridaySixthLessonTeacherSG,
    fridaySixthLessonClassroomSG: req.body.fridaySixthLessonClassroomSG,
    fridaySeventhLessonFG: req.body.fridaySeventhLessonFG,
    fridaySeventhLessonTeacherFG: req.body.fridaySeventhLessonTeacherFG,
    fridaySeventhLessonClassroomFG: req.body.fridaySeventhLessonClassroomFG,
    fridaySeventhLessonSG: req.body.fridaySeventhLessonSG,
    fridaySeventhLessonTeacherSG: req.body.fridaySeventhLessonTeacherSG,
    fridaySeventhLessonClassroomSG: req.body.fridaySeventhLessonClassroomSG,
    fridayEighthLessonFG: req.body.fridayEighthLessonFG,
    fridayEighthLessonTeacherFG: req.body.fridayEighthLessonTeacherFG,
    fridayEighthLessonClassroomFG: req.body.fridayEighthLessonClassroomFG,
    fridayEighthLessonSG: req.body.fridayEighthLessonSG,
    fridayEighthLessonTeacherSG: req.body.fridayEighthLessonTeacherSG,
    fridayEighthLessonClassroomSG: req.body.fridayEighthLessonClassroomSG,
    fridayNinthLessonFG: req.body.fridayNinthLessonFG,
    fridayNinthLessonTeacherFG: req.body.fridayNinthLessonTeacherFG,
    fridayNinthLessonClassroomFG: req.body.fridayNinthLessonClassroomFG,
    fridayNinthLessonSG: req.body.fridayNinthLessonSG,
    fridayNinthLessonTeacherSG: req.body.fridayNinthLessonTeacherSG,
    fridayNinthLessonClassroomSG: req.body.fridayNinthLessonClassroomSG,
    fridayTenthLessonFG: req.body.fridayTenthLessonFG,
    fridayTenthLessonTeacherFG: req.body.fridayTenthLessonTeacherFG,
    fridayTenthLessonClassroomFG: req.body.fridayTenthLessonClassroomFG,
    fridayTenthLessonSG: req.body.fridayTenthLessonSG,
    fridayTenthLessonTeacherSG: req.body.fridayTenthLessonTeacherSG,
    fridayTenthLessonClassroomSG: req.body.fridayTenthLessonClassroomSG,

    saturdayFirstLessonFG: req.body.saturdayFirstLessonFG,
    saturdayFirstLessonTeacherFG: req.body.saturdayFirstLessonTeacherFG,
    saturdayFirstLessonClassroomFG: req.body.saturdayFirstLessonClassroomFG,
    saturdayFirstLessonSG: req.body.saturdayFirstLessonSG,
    saturdayFirstLessonTeacherSG: req.body.saturdayFirstLessonTeacherSG,
    saturdayFirstLessonClassroomSG: req.body.saturdayFirstLessonClassroomSG,
    saturdaySecondLessonFG: req.body.saturdaySecondLessonFG,
    saturdaySecondLessonTeacherFG: req.body.saturdaySecondLessonTeacherFG,
    saturdaySecondLessonClassroomFG: req.body.saturdaySecondLessonClassroomFG,
    saturdaySecondLessonSG: req.body.saturdaySecondLessonSG,
    saturdaySecondLessonTeacherSG: req.body.saturdaySecondLessonTeacherSG,
    saturdaySecondLessonClassroomSG: req.body.saturdaySecondLessonClassroomSG,
    saturdayThirdLessonFG: req.body.saturdayThirdLessonFG,
    saturdayThirdLessonTeacherFG: req.body.saturdayThirdLessonTeacherFG,
    saturdayThirdLessonClassroomFG: req.body.saturdayThirdLessonClassroomFG,
    saturdayThirdLessonSG: req.body.saturdayThirdLessonSG,
    saturdayThirdLessonTeacherSG: req.body.saturdayThirdLessonTeacherSG,
    saturdayThirdLessonClassroomSG: req.body.saturdayThirdLessonClassroomSG,
    saturdayFourthLessonFG: req.body.saturdayFourthLessonFG,
    saturdayFourthLessonTeacherFG: req.body.saturdayFourthLessonTeacherFG,
    saturdayFourthLessonClassroomFG: req.body.saturdayFourthLessonClassroomFG,
    saturdayFourthLessonSG: req.body.saturdayFourthLessonSG,
    saturdayFourthLessonTeacherSG: req.body.saturdayFourthLessonTeacherSG,
    saturdayFourthLessonClassroomSG: req.body.saturdayFourthLessonClassroomSG,
    saturdayFifthLessonFG: req.body.saturdayFifthLessonFG,
    saturdayFifthLessonTeacherFG: req.body.saturdayFifthLessonTeacherFG,
    saturdayFifthLessonClassroomFG: req.body.saturdayFifthLessonClassroomFG,
    saturdayFifthLessonSG: req.body.saturdayFifthLessonSG,
    saturdayFifthLessonTeacherSG: req.body.saturdayFifthLessonTeacherSG,
    saturdayFifthLessonClassroomSG: req.body.saturdayFifthLessonClassroomSG,
    saturdaySixthLessonFG: req.body.saturdaySixthLessonFG,
    saturdaySixthLessonTeacherFG: req.body.saturdaySixthLessonTeacherFG,
    saturdaySixthLessonClassroomFG: req.body.saturdaySixthLessonClassroomFG,
    saturdaySixthLessonSG: req.body.saturdaySixthLessonSG,
    saturdaySixthLessonTeacherSG: req.body.saturdaySixthLessonTeacherSG,
    saturdaySixthLessonClassroomSG: req.body.saturdaySixthLessonClassroomSG,
    saturdaySeventhLessonFG: req.body.saturdaySeventhLessonFG,
    saturdaySeventhLessonTeacherFG: req.body.saturdaySeventhLessonTeacherFG,
    saturdaySeventhLessonClassroomFG: req.body.saturdaySeventhLessonClassroomFG,
    saturdaySeventhLessonSG: req.body.saturdaySeventhLessonSG,
    saturdaySeventhLessonTeacherSG: req.body.saturdaySeventhLessonTeacherSG,
    saturdaySeventhLessonClassroomSG: req.body.saturdaySeventhLessonClassroomSG,
    saturdayEighthLessonFG: req.body.saturdayEighthLessonFG,
    saturdayEighthLessonTeacherFG: req.body.saturdayEighthLessonTeacherFG,
    saturdayEighthLessonClassroomFG: req.body.saturdayEighthLessonClassroomFG,
    saturdayEighthLessonSG: req.body.saturdayEighthLessonSG,
    saturdayEighthLessonTeacherSG: req.body.saturdayEighthLessonTeacherSG,
    saturdayEighthLessonClassroomSG: req.body.saturdayEighthLessonClassroomSG,
    saturdayNinthLessonFG: req.body.saturdayNinthLessonFG,
    saturdayNinthLessonTeacherFG: req.body.saturdayNinthLessonTeacherFG,
    saturdayNinthLessonClassroomFG: req.body.saturdayNinthLessonClassroomFG,
    saturdayNinthLessonSG: req.body.saturdayNinthLessonSG,
    saturdayNinthLessonTeacherSG: req.body.saturdayNinthLessonTeacherSG,
    saturdayNinthLessonClassroomSG: req.body.saturdayNinthLessonClassroomSG,
    saturdayTenthLessonFG: req.body.saturdayTenthLessonFG,
    saturdayTenthLessonTeacherFG: req.body.saturdayTenthLessonTeacherFG,
    saturdayTenthLessonClassroomFG: req.body.saturdayTenthLessonClassroomFG,
    saturdayTenthLessonSG: req.body.saturdayTenthLessonSG,
    saturdayTenthLessonTeacherSG: req.body.saturdayTenthLessonTeacherSG,
    saturdayTenthLessonClassroomSG: req.body.saturdayTenthLessonClassroomSG,

  });
  grade.save().then(createdGrade => {
    console.log(createdGrade);
    res.status(201).json({
      message: "Grade added successfully",
      grades: {
        ...createdGrade,
        id: createdGrade._id
      }
      // gradeName: createdGrade.gradeName
    });
  })
  .catch(error => {
    res.status(500).json({
      message: "Creating a grade failed!"
    });
  });
};

exports.updateGrade = (req, res, next) => {
  const grade = new Grade({
    _id: req.body.id,

    gradeNumber: req.body.gradeNumber,
    gradeLiter: req.body.gradeLiter,

    mondayFirstLessonFG: req.body.mondayFirstLessonFG,
    mondayFirstLessonTeacherFG: req.body.mondayFirstLessonTeacherFG,
    mondayFirstLessonClassroomFG: req.body.mondayFirstLessonClassroomFG,
    mondayFirstLessonSG: req.body.mondayFirstLessonSG,
    mondayFirstLessonTeacherSG: req.body.mondayFirstLessonTeacherSG,
    mondayFirstLessonClassroomSG: req.body.mondayFirstLessonClassroomSG,
    mondaySecondLessonFG: req.body.mondaySecondLessonFG,
    mondaySecondLessonTeacherFG: req.body.mondaySecondLessonTeacherFG,
    mondaySecondLessonClassroomFG: req.body.mondaySecondLessonClassroomFG,
    mondaySecondLessonSG: req.body.mondaySecondLessonSG,
    mondaySecondLessonTeacherSG: req.body.mondaySecondLessonTeacherSG,
    mondaySecondLessonClassroomSG: req.body.mondaySecondLessonClassroomSG,
    mondayThirdLessonFG: req.body.mondayThirdLessonFG,
    mondayThirdLessonTeacherFG: req.body.mondayThirdLessonTeacherFG,
    mondayThirdLessonClassroomFG: req.body.mondayThirdLessonClassroomFG,
    mondayThirdLessonSG: req.body.mondayThirdLessonSG,
    mondayThirdLessonTeacherSG: req.body.mondayThirdLessonTeacherSG,
    mondayThirdLessonClassroomSG: req.body.mondayThirdLessonClassroomSG,
    mondayFourthLessonFG: req.body.mondayFourthLessonFG,
    mondayFourthLessonTeacherFG: req.body.mondayFourthLessonTeacherFG,
    mondayFourthLessonClassroomFG: req.body.mondayFourthLessonClassroomFG,
    mondayFourthLessonSG: req.body.mondayFourthLessonSG,
    mondayFourthLessonTeacherSG: req.body.mondayFourthLessonTeacherSG,
    mondayFourthLessonClassroomSG: req.body.mondayFourthLessonClassroomSG,
    mondayFifthLessonFG: req.body.mondayFifthLessonFG,
    mondayFifthLessonTeacherFG: req.body.mondayFifthLessonTeacherFG,
    mondayFifthLessonClassroomFG: req.body.mondayFifthLessonClassroomFG,
    mondayFifthLessonSG: req.body.mondayFifthLessonSG,
    mondayFifthLessonTeacherSG: req.body.mondayFifthLessonTeacherSG,
    mondayFifthLessonClassroomSG: req.body.mondayFifthLessonClassroomSG,
    mondaySixthLessonFG: req.body.mondaySixthLessonFG,
    mondaySixthLessonTeacherFG: req.body.mondaySixthLessonTeacherFG,
    mondaySixthLessonClassroomFG: req.body.mondaySixthLessonClassroomFG,
    mondaySixthLessonSG: req.body.mondaySixthLessonSG,
    mondaySixthLessonTeacherSG: req.body.mondaySixthLessonTeacherSG,
    mondaySixthLessonClassroomSG: req.body.mondaySixthLessonClassroomSG,
    mondaySeventhLessonFG: req.body.mondaySeventhLessonFG,
    mondaySeventhLessonTeacherFG: req.body.mondaySeventhLessonTeacherFG,
    mondaySeventhLessonClassroomFG: req.body.mondaySeventhLessonClassroomFG,
    mondaySeventhLessonSG: req.body.mondaySeventhLessonSG,
    mondaySeventhLessonTeacherSG: req.body.mondaySeventhLessonTeacherSG,
    mondaySeventhLessonClassroomSG: req.body.mondaySeventhLessonClassroomSG,
    mondayEighthLessonFG: req.body.mondayEighthLessonFG,
    mondayEighthLessonTeacherFG: req.body.mondayEighthLessonTeacherFG,
    mondayEighthLessonClassroomFG: req.body.mondayEighthLessonClassroomFG,
    mondayEighthLessonSG: req.body.mondayEighthLessonSG,
    mondayEighthLessonTeacherSG: req.body.mondayEighthLessonTeacherSG,
    mondayEighthLessonClassroomSG: req.body.mondayEighthLessonClassroomSG,
    mondayNinthLessonFG: req.body.mondayNinthLessonFG,
    mondayNinthLessonTeacherFG: req.body.mondayNinthLessonTeacherFG,
    mondayNinthLessonClassroomFG: req.body.mondayNinthLessonClassroomFG,
    mondayNinthLessonSG: req.body.mondayNinthLessonSG,
    mondayNinthLessonTeacherSG: req.body.mondayNinthLessonTeacherSG,
    mondayNinthLessonClassroomSG: req.body.mondayNinthLessonClassroomSG,
    mondayTenthLessonFG: req.body.mondayTenthLessonFG,
    mondayTenthLessonTeacherFG: req.body.mondayTenthLessonTeacherFG,
    mondayTenthLessonClassroomFG: req.body.mondayTenthLessonClassroomFG,
    mondayTenthLessonSG: req.body.mondayTenthLessonSG,
    mondayTenthLessonTeacherSG: req.body.mondayTenthLessonTeacherSG,
    mondayTenthLessonClassroomSG: req.body.mondayTenthLessonClassroomSG,
    tuesdayFirstLessonFG: req.body.tuesdayFirstLessonFG,
    tuesdayFirstLessonTeacherFG: req.body.tuesdayFirstLessonTeacherFG,
    tuesdayFirstLessonClassroomFG: req.body.tuesdayFirstLessonClassroomFG,
    tuesdayFirstLessonSG: req.body.tuesdayFirstLessonSG,
    tuesdayFirstLessonTeacherSG: req.body.tuesdayFirstLessonTeacherSG,
    tuesdayFirstLessonClassroomSG: req.body.tuesdayFirstLessonClassroomSG,
    tuesdaySecondLessonFG: req.body.tuesdaySecondLessonFG,
    tuesdaySecondLessonTeacherFG: req.body.tuesdaySecondLessonTeacherFG,
    tuesdaySecondLessonClassroomFG: req.body.tuesdaySecondLessonClassroomFG,
    tuesdaySecondLessonSG: req.body.tuesdaySecondLessonSG,
    tuesdaySecondLessonTeacherSG: req.body.tuesdaySecondLessonTeacherSG,
    tuesdaySecondLessonClassroomSG: req.body.tuesdaySecondLessonClassroomSG,
    tuesdayThirdLessonFG: req.body.tuesdayThirdLessonFG,
    tuesdayThirdLessonTeacherFG: req.body.tuesdayThirdLessonTeacherFG,
    tuesdayThirdLessonClassroomFG: req.body.tuesdayThirdLessonClassroomFG,
    tuesdayThirdLessonSG: req.body.tuesdayThirdLessonSG,
    tuesdayThirdLessonTeacherSG: req.body.tuesdayThirdLessonTeacherSG,
    tuesdayThirdLessonClassroomSG: req.body.tuesdayThirdLessonClassroomSG,
    tuesdayFourthLessonFG: req.body.tuesdayFourthLessonFG,
    tuesdayFourthLessonTeacherFG: req.body.tuesdayFourthLessonTeacherFG,
    tuesdayFourthLessonClassroomFG: req.body.tuesdayFourthLessonClassroomFG,
    tuesdayFourthLessonSG: req.body.tuesdayFourthLessonSG,
    tuesdayFourthLessonTeacherSG: req.body.tuesdayFourthLessonTeacherSG,
    tuesdayFourthLessonClassroomSG: req.body.tuesdayFourthLessonClassroomSG,
    tuesdayFifthLessonFG: req.body.tuesdayFifthLessonFG,
    tuesdayFifthLessonTeacherFG: req.body.tuesdayFifthLessonTeacherFG,
    tuesdayFifthLessonClassroomFG: req.body.tuesdayFifthLessonClassroomFG,
    tuesdayFifthLessonSG: req.body.tuesdayFifthLessonSG,
    tuesdayFifthLessonTeacherSG: req.body.tuesdayFifthLessonTeacherSG,
    tuesdayFifthLessonClassroomSG: req.body.tuesdayFifthLessonClassroomSG,
    tuesdaySixthLessonFG: req.body.tuesdaySixthLessonFG,
    tuesdaySixthLessonTeacherFG: req.body.tuesdaySixthLessonTeacherFG,
    tuesdaySixthLessonClassroomFG: req.body.tuesdaySixthLessonClassroomFG,
    tuesdaySixthLessonSG: req.body.tuesdaySixthLessonSG,
    tuesdaySixthLessonTeacherSG: req.body.tuesdaySixthLessonTeacherSG,
    tuesdaySixthLessonClassroomSG: req.body.tuesdaySixthLessonClassroomSG,
    tuesdaySeventhLessonFG: req.body.tuesdaySeventhLessonFG,
    tuesdaySeventhLessonTeacherFG: req.body.tuesdaySeventhLessonTeacherFG,
    tuesdaySeventhLessonClassroomFG: req.body.tuesdaySeventhLessonClassroomFG,
    tuesdaySeventhLessonSG: req.body.tuesdaySeventhLessonSG,
    tuesdaySeventhLessonTeacherSG: req.body.tuesdaySeventhLessonTeacherSG,
    tuesdaySeventhLessonClassroomSG: req.body.tuesdaySeventhLessonClassroomSG,
    tuesdayEighthLessonFG: req.body.tuesdayEighthLessonFG,
    tuesdayEighthLessonTeacherFG: req.body.tuesdayEighthLessonTeacherFG,
    tuesdayEighthLessonClassroomFG: req.body.tuesdayEighthLessonClassroomFG,
    tuesdayEighthLessonSG: req.body.tuesdayEighthLessonSG,
    tuesdayEighthLessonTeacherSG: req.body.tuesdayEighthLessonTeacherSG,
    tuesdayEighthLessonClassroomSG: req.body.tuesdayEighthLessonClassroomSG,
    tuesdayNinthLessonFG: req.body.tuesdayNinthLessonFG,
    tuesdayNinthLessonTeacherFG: req.body.tuesdayNinthLessonTeacherFG,
    tuesdayNinthLessonClassroomFG: req.body.tuesdayNinthLessonClassroomFG,
    tuesdayNinthLessonSG: req.body.tuesdayNinthLessonSG,
    tuesdayNinthLessonTeacherSG: req.body.tuesdayNinthLessonTeacherSG,
    tuesdayNinthLessonClassroomSG: req.body.tuesdayNinthLessonClassroomSG,
    tuesdayTenthLessonFG: req.body.tuesdayTenthLessonFG,
    tuesdayTenthLessonTeacherFG: req.body.tuesdayTenthLessonTeacherFG,
    tuesdayTenthLessonClassroomFG: req.body.tuesdayTenthLessonClassroomFG,
    tuesdayTenthLessonSG: req.body.tuesdayTenthLessonSG,
    tuesdayTenthLessonTeacherSG: req.body.tuesdayTenthLessonTeacherSG,
    tuesdayTenthLessonClassroomSG: req.body.tuesdayTenthLessonClassroomSG,

    wednesdayFirstLessonFG: req.body.wednesdayFirstLessonFG,
    wednesdayFirstLessonTeacherFG: req.body.wednesdayFirstLessonTeacherFG,
    wednesdayFirstLessonClassroomFG: req.body.wednesdayFirstLessonClassroomFG,
    wednesdayFirstLessonSG: req.body.wednesdayFirstLessonSG,
    wednesdayFirstLessonTeacherSG: req.body.wednesdayFirstLessonTeacherSG,
    wednesdayFirstLessonClassroomSG: req.body.wednesdayFirstLessonClassroomSG,
    wednesdaySecondLessonFG: req.body.wednesdaySecondLessonFG,
    wednesdaySecondLessonTeacherFG: req.body.wednesdaySecondLessonTeacherFG,
    wednesdaySecondLessonClassroomFG: req.body.wednesdaySecondLessonClassroomFG,
    wednesdaySecondLessonSG: req.body.wednesdaySecondLessonSG,
    wednesdaySecondLessonTeacherSG: req.body.wednesdaySecondLessonTeacherSG,
    wednesdaySecondLessonClassroomSG: req.body.wednesdaySecondLessonClassroomSG,
    wednesdayThirdLessonFG: req.body.wednesdayThirdLessonFG,
    wednesdayThirdLessonTeacherFG: req.body.wednesdayThirdLessonTeacherFG,
    wednesdayThirdLessonClassroomFG: req.body.wednesdayThirdLessonClassroomFG,
    wednesdayThirdLessonSG: req.body.wednesdayThirdLessonSG,
    wednesdayThirdLessonTeacherSG: req.body.wednesdayThirdLessonTeacherSG,
    wednesdayThirdLessonClassroomSG: req.body.wednesdayThirdLessonClassroomSG,
    wednesdayFourthLessonFG: req.body.wednesdayFourthLessonFG,
    wednesdayFourthLessonTeacherFG: req.body.wednesdayFourthLessonTeacherFG,
    wednesdayFourthLessonClassroomFG: req.body.wednesdayFourthLessonClassroomFG,
    wednesdayFourthLessonSG: req.body.wednesdayFourthLessonSG,
    wednesdayFourthLessonTeacherSG: req.body.wednesdayFourthLessonTeacherSG,
    wednesdayFourthLessonClassroomSG: req.body.wednesdayFourthLessonClassroomSG,
    wednesdayFifthLessonFG: req.body.wednesdayFifthLessonFG,
    wednesdayFifthLessonTeacherFG: req.body.wednesdayFifthLessonTeacherFG,
    wednesdayFifthLessonClassroomFG: req.body.wednesdayFifthLessonClassroomFG,
    wednesdayFifthLessonSG: req.body.wednesdayFifthLessonSG,
    wednesdayFifthLessonTeacherSG: req.body.wednesdayFifthLessonTeacherSG,
    wednesdayFifthLessonClassroomSG: req.body.wednesdayFifthLessonClassroomSG,
    wednesdaySixthLessonFG: req.body.wednesdaySixthLessonFG,
    wednesdaySixthLessonTeacherFG: req.body.wednesdaySixthLessonTeacherFG,
    wednesdaySixthLessonClassroomFG: req.body.wednesdaySixthLessonClassroomFG,
    wednesdaySixthLessonSG: req.body.wednesdaySixthLessonSG,
    wednesdaySixthLessonTeacherSG: req.body.wednesdaySixthLessonTeacherSG,
    wednesdaySixthLessonClassroomSG: req.body.wednesdaySixthLessonClassroomSG,
    wednesdaySeventhLessonFG: req.body.wednesdaySeventhLessonFG,
    wednesdaySeventhLessonTeacherFG: req.body.wednesdaySeventhLessonTeacherFG,
    wednesdaySeventhLessonClassroomFG: req.body.wednesdaySeventhLessonClassroomFG,
    wednesdaySeventhLessonSG: req.body.wednesdaySeventhLessonSG,
    wednesdaySeventhLessonTeacherSG: req.body.wednesdaySeventhLessonTeacherSG,
    wednesdaySeventhLessonClassroomSG: req.body.wednesdaySeventhLessonClassroomSG,
    wednesdayEighthLessonFG: req.body.wednesdayEighthLessonFG,
    wednesdayEighthLessonTeacherFG: req.body.wednesdayEighthLessonTeacherFG,
    wednesdayEighthLessonClassroomFG: req.body.wednesdayEighthLessonClassroomFG,
    wednesdayEighthLessonSG: req.body.wednesdayEighthLessonSG,
    wednesdayEighthLessonTeacherSG: req.body.wednesdayEighthLessonTeacherSG,
    wednesdayEighthLessonClassroomSG: req.body.wednesdayEighthLessonClassroomSG,
    wednesdayNinthLessonFG: req.body.wednesdayNinthLessonFG,
    wednesdayNinthLessonTeacherFG: req.body.wednesdayNinthLessonTeacherFG,
    wednesdayNinthLessonClassroomFG: req.body.wednesdayNinthLessonClassroomFG,
    wednesdayNinthLessonSG: req.body.wednesdayNinthLessonSG,
    wednesdayNinthLessonTeacherSG: req.body.wednesdayNinthLessonTeacherSG,
    wednesdayNinthLessonClassroomSG: req.body.wednesdayNinthLessonClassroomSG,
    wednesdayTenthLessonFG: req.body.wednesdayTenthLessonFG,
    wednesdayTenthLessonTeacherFG: req.body.wednesdayTenthLessonTeacherFG,
    wednesdayTenthLessonClassroomFG: req.body.wednesdayTenthLessonClassroomFG,
    wednesdayTenthLessonSG: req.body.wednesdayTenthLessonSG,
    wednesdayTenthLessonTeacherSG: req.body.wednesdayTenthLessonTeacherSG,
    wednesdayTenthLessonClassroomSG: req.body.wednesdayTenthLessonClassroomSG,

    thursdayFirstLessonFG: req.body.thursdayFirstLessonFG,
    thursdayFirstLessonTeacherFG: req.body.thursdayFirstLessonTeacherFG,
    thursdayFirstLessonClassroomFG: req.body.thursdayFirstLessonClassroomFG,
    thursdayFirstLessonSG: req.body.thursdayFirstLessonSG,
    thursdayFirstLessonTeacherSG: req.body.thursdayFirstLessonTeacherSG,
    thursdayFirstLessonClassroomSG: req.body.thursdayFirstLessonClassroomSG,
    thursdaySecondLessonFG: req.body.thursdaySecondLessonFG,
    thursdaySecondLessonTeacherFG: req.body.thursdaySecondLessonTeacherFG,
    thursdaySecondLessonClassroomFG: req.body.thursdaySecondLessonClassroomFG,
    thursdaySecondLessonSG: req.body.thursdaySecondLessonSG,
    thursdaySecondLessonTeacherSG: req.body.thursdaySecondLessonTeacherSG,
    thursdaySecondLessonClassroomSG: req.body.thursdaySecondLessonClassroomSG,
    thursdayThirdLessonFG: req.body.thursdayThirdLessonFG,
    thursdayThirdLessonTeacherFG: req.body.thursdayThirdLessonTeacherFG,
    thursdayThirdLessonClassroomFG: req.body.thursdayThirdLessonClassroomFG,
    thursdayThirdLessonSG: req.body.thursdayThirdLessonSG,
    thursdayThirdLessonTeacherSG: req.body.thursdayThirdLessonTeacherSG,
    thursdayThirdLessonClassroomSG: req.body.thursdayThirdLessonClassroomSG,
    thursdayFourthLessonFG: req.body.thursdayFourthLessonFG,
    thursdayFourthLessonTeacherFG: req.body.thursdayFourthLessonTeacherFG,
    thursdayFourthLessonClassroomFG: req.body.thursdayFourthLessonClassroomFG,
    thursdayFourthLessonSG: req.body.thursdayFourthLessonSG,
    thursdayFourthLessonTeacherSG: req.body.thursdayFourthLessonTeacherSG,
    thursdayFourthLessonClassroomSG: req.body.thursdayFourthLessonClassroomSG,
    thursdayFifthLessonFG: req.body.thursdayFifthLessonFG,
    thursdayFifthLessonTeacherFG: req.body.thursdayFifthLessonTeacherFG,
    thursdayFifthLessonClassroomFG: req.body.thursdayFifthLessonClassroomFG,
    thursdayFifthLessonSG: req.body.thursdayFifthLessonSG,
    thursdayFifthLessonTeacherSG: req.body.thursdayFifthLessonTeacherSG,
    thursdayFifthLessonClassroomSG: req.body.thursdayFifthLessonClassroomSG,
    thursdaySixthLessonFG: req.body.thursdaySixthLessonFG,
    thursdaySixthLessonTeacherFG: req.body.thursdaySixthLessonTeacherFG,
    thursdaySixthLessonClassroomFG: req.body.thursdaySixthLessonClassroomFG,
    thursdaySixthLessonSG: req.body.thursdaySixthLessonSG,
    thursdaySixthLessonTeacherSG: req.body.thursdaySixthLessonTeacherSG,
    thursdaySixthLessonClassroomSG: req.body.thursdaySixthLessonClassroomSG,
    thursdaySeventhLessonFG: req.body.thursdaySeventhLessonFG,
    thursdaySeventhLessonTeacherFG: req.body.thursdaySeventhLessonTeacherFG,
    thursdaySeventhLessonClassroomFG: req.body.thursdaySeventhLessonClassroomFG,
    thursdaySeventhLessonSG: req.body.thursdaySeventhLessonSG,
    thursdaySeventhLessonTeacherSG: req.body.thursdaySeventhLessonTeacherSG,
    thursdaySeventhLessonClassroomSG: req.body.thursdaySeventhLessonClassroomSG,
    thursdayEighthLessonFG: req.body.thursdayEighthLessonFG,
    thursdayEighthLessonTeacherFG: req.body.thursdayEighthLessonTeacherFG,
    thursdayEighthLessonClassroomFG: req.body.thursdayEighthLessonClassroomFG,
    thursdayEighthLessonSG: req.body.thursdayEighthLessonSG,
    thursdayEighthLessonTeacherSG: req.body.thursdayEighthLessonTeacherSG,
    thursdayEighthLessonClassroomSG: req.body.thursdayEighthLessonClassroomSG,
    thursdayNinthLessonFG: req.body.thursdayNinthLessonFG,
    thursdayNinthLessonTeacherFG: req.body.thursdayNinthLessonTeacherFG,
    thursdayNinthLessonClassroomFG: req.body.thursdayNinthLessonClassroomFG,
    thursdayNinthLessonSG: req.body.thursdayNinthLessonSG,
    thursdayNinthLessonTeacherSG: req.body.thursdayNinthLessonTeacherSG,
    thursdayNinthLessonClassroomSG: req.body.thursdayNinthLessonClassroomSG,
    thursdayTenthLessonFG: req.body.thursdayTenthLessonFG,
    thursdayTenthLessonTeacherFG: req.body.thursdayTenthLessonTeacherFG,
    thursdayTenthLessonClassroomFG: req.body.thursdayTenthLessonClassroomFG,
    thursdayTenthLessonSG: req.body.thursdayTenthLessonSG,
    thursdayTenthLessonTeacherSG: req.body.thursdayTenthLessonTeacherSG,
    thursdayTenthLessonClassroomSG: req.body.thursdayTenthLessonClassroomSG,

    fridayFirstLessonFG: req.body.fridayFirstLessonFG,
    fridayFirstLessonTeacherFG: req.body.fridayFirstLessonTeacherFG,
    fridayFirstLessonClassroomFG: req.body.fridayFirstLessonClassroomFG,
    fridayFirstLessonSG: req.body.fridayFirstLessonSG,
    fridayFirstLessonTeacherSG: req.body.fridayFirstLessonTeacherSG,
    fridayFirstLessonClassroomSG: req.body.fridayFirstLessonClassroomSG,
    fridaySecondLessonFG: req.body.fridaySecondLessonFG,
    fridaySecondLessonTeacherFG: req.body.fridaySecondLessonTeacherFG,
    fridaySecondLessonClassroomFG: req.body.fridaySecondLessonClassroomFG,
    fridaySecondLessonSG: req.body.fridaySecondLessonSG,
    fridaySecondLessonTeacherSG: req.body.fridaySecondLessonTeacherSG,
    fridaySecondLessonClassroomSG: req.body.fridaySecondLessonClassroomSG,
    fridayThirdLessonFG: req.body.fridayThirdLessonFG,
    fridayThirdLessonTeacherFG: req.body.fridayThirdLessonTeacherFG,
    fridayThirdLessonClassroomFG: req.body.fridayThirdLessonClassroomFG,
    fridayThirdLessonSG: req.body.fridayThirdLessonSG,
    fridayThirdLessonTeacherSG: req.body.fridayThirdLessonTeacherSG,
    fridayThirdLessonClassroomSG: req.body.fridayThirdLessonClassroomSG,
    fridayFourthLessonFG: req.body.fridayFourthLessonFG,
    fridayFourthLessonTeacherFG: req.body.fridayFourthLessonTeacherFG,
    fridayFourthLessonClassroomFG: req.body.fridayFourthLessonClassroomFG,
    fridayFourthLessonSG: req.body.fridayFourthLessonSG,
    fridayFourthLessonTeacherSG: req.body.fridayFourthLessonTeacherSG,
    fridayFourthLessonClassroomSG: req.body.fridayFourthLessonClassroomSG,
    fridayFifthLessonFG: req.body.fridayFifthLessonFG,
    fridayFifthLessonTeacherFG: req.body.fridayFifthLessonTeacherFG,
    fridayFifthLessonClassroomFG: req.body.fridayFifthLessonClassroomFG,
    fridayFifthLessonSG: req.body.fridayFifthLessonSG,
    fridayFifthLessonTeacherSG: req.body.fridayFifthLessonTeacherSG,
    fridayFifthLessonClassroomSG: req.body.fridayFifthLessonClassroomSG,
    fridaySixthLessonFG: req.body.fridaySixthLessonFG,
    fridaySixthLessonTeacherFG: req.body.fridaySixthLessonTeacherFG,
    fridaySixthLessonClassroomFG: req.body.fridaySixthLessonClassroomFG,
    fridaySixthLessonSG: req.body.fridaySixthLessonSG,
    fridaySixthLessonTeacherSG: req.body.fridaySixthLessonTeacherSG,
    fridaySixthLessonClassroomSG: req.body.fridaySixthLessonClassroomSG,
    fridaySeventhLessonFG: req.body.fridaySeventhLessonFG,
    fridaySeventhLessonTeacherFG: req.body.fridaySeventhLessonTeacherFG,
    fridaySeventhLessonClassroomFG: req.body.fridaySeventhLessonClassroomFG,
    fridaySeventhLessonSG: req.body.fridaySeventhLessonSG,
    fridaySeventhLessonTeacherSG: req.body.fridaySeventhLessonTeacherSG,
    fridaySeventhLessonClassroomSG: req.body.fridaySeventhLessonClassroomSG,
    fridayEighthLessonFG: req.body.fridayEighthLessonFG,
    fridayEighthLessonTeacherFG: req.body.fridayEighthLessonTeacherFG,
    fridayEighthLessonClassroomFG: req.body.fridayEighthLessonClassroomFG,
    fridayEighthLessonSG: req.body.fridayEighthLessonSG,
    fridayEighthLessonTeacherSG: req.body.fridayEighthLessonTeacherSG,
    fridayEighthLessonClassroomSG: req.body.fridayEighthLessonClassroomSG,
    fridayNinthLessonFG: req.body.fridayNinthLessonFG,
    fridayNinthLessonTeacherFG: req.body.fridayNinthLessonTeacherFG,
    fridayNinthLessonClassroomFG: req.body.fridayNinthLessonClassroomFG,
    fridayNinthLessonSG: req.body.fridayNinthLessonSG,
    fridayNinthLessonTeacherSG: req.body.fridayNinthLessonTeacherSG,
    fridayNinthLessonClassroomSG: req.body.fridayNinthLessonClassroomSG,
    fridayTenthLessonFG: req.body.fridayTenthLessonFG,
    fridayTenthLessonTeacherFG: req.body.fridayTenthLessonTeacherFG,
    fridayTenthLessonClassroomFG: req.body.fridayTenthLessonClassroomFG,
    fridayTenthLessonSG: req.body.fridayTenthLessonSG,
    fridayTenthLessonTeacherSG: req.body.fridayTenthLessonTeacherSG,
    fridayTenthLessonClassroomSG: req.body.fridayTenthLessonClassroomSG,

    saturdayFirstLessonFG: req.body.saturdayFirstLessonFG,
    saturdayFirstLessonTeacherFG: req.body.saturdayFirstLessonTeacherFG,
    saturdayFirstLessonClassroomFG: req.body.saturdayFirstLessonClassroomFG,
    saturdayFirstLessonSG: req.body.saturdayFirstLessonSG,
    saturdayFirstLessonTeacherSG: req.body.saturdayFirstLessonTeacherSG,
    saturdayFirstLessonClassroomSG: req.body.saturdayFirstLessonClassroomSG,
    saturdaySecondLessonFG: req.body.saturdaySecondLessonFG,
    saturdaySecondLessonTeacherFG: req.body.saturdaySecondLessonTeacherFG,
    saturdaySecondLessonClassroomFG: req.body.saturdaySecondLessonClassroomFG,
    saturdaySecondLessonSG: req.body.saturdaySecondLessonSG,
    saturdaySecondLessonTeacherSG: req.body.saturdaySecondLessonTeacherSG,
    saturdaySecondLessonClassroomSG: req.body.saturdaySecondLessonClassroomSG,
    saturdayThirdLessonFG: req.body.saturdayThirdLessonFG,
    saturdayThirdLessonTeacherFG: req.body.saturdayThirdLessonTeacherFG,
    saturdayThirdLessonClassroomFG: req.body.saturdayThirdLessonClassroomFG,
    saturdayThirdLessonSG: req.body.saturdayThirdLessonSG,
    saturdayThirdLessonTeacherSG: req.body.saturdayThirdLessonTeacherSG,
    saturdayThirdLessonClassroomSG: req.body.saturdayThirdLessonClassroomSG,
    saturdayFourthLessonFG: req.body.saturdayFourthLessonFG,
    saturdayFourthLessonTeacherFG: req.body.saturdayFourthLessonTeacherFG,
    saturdayFourthLessonClassroomFG: req.body.saturdayFourthLessonClassroomFG,
    saturdayFourthLessonSG: req.body.saturdayFourthLessonSG,
    saturdayFourthLessonTeacherSG: req.body.saturdayFourthLessonTeacherSG,
    saturdayFourthLessonClassroomSG: req.body.saturdayFourthLessonClassroomSG,
    saturdayFifthLessonFG: req.body.saturdayFifthLessonFG,
    saturdayFifthLessonTeacherFG: req.body.saturdayFifthLessonTeacherFG,
    saturdayFifthLessonClassroomFG: req.body.saturdayFifthLessonClassroomFG,
    saturdayFifthLessonSG: req.body.saturdayFifthLessonSG,
    saturdayFifthLessonTeacherSG: req.body.saturdayFifthLessonTeacherSG,
    saturdayFifthLessonClassroomSG: req.body.saturdayFifthLessonClassroomSG,
    saturdaySixthLessonFG: req.body.saturdaySixthLessonFG,
    saturdaySixthLessonTeacherFG: req.body.saturdaySixthLessonTeacherFG,
    saturdaySixthLessonClassroomFG: req.body.saturdaySixthLessonClassroomFG,
    saturdaySixthLessonSG: req.body.saturdaySixthLessonSG,
    saturdaySixthLessonTeacherSG: req.body.saturdaySixthLessonTeacherSG,
    saturdaySixthLessonClassroomSG: req.body.saturdaySixthLessonClassroomSG,
    saturdaySeventhLessonFG: req.body.saturdaySeventhLessonFG,
    saturdaySeventhLessonTeacherFG: req.body.saturdaySeventhLessonTeacherFG,
    saturdaySeventhLessonClassroomFG: req.body.saturdaySeventhLessonClassroomFG,
    saturdaySeventhLessonSG: req.body.saturdaySeventhLessonSG,
    saturdaySeventhLessonTeacherSG: req.body.saturdaySeventhLessonTeacherSG,
    saturdaySeventhLessonClassroomSG: req.body.saturdaySeventhLessonClassroomSG,
    saturdayEighthLessonFG: req.body.saturdayEighthLessonFG,
    saturdayEighthLessonTeacherFG: req.body.saturdayEighthLessonTeacherFG,
    saturdayEighthLessonClassroomFG: req.body.saturdayEighthLessonClassroomFG,
    saturdayEighthLessonSG: req.body.saturdayEighthLessonSG,
    saturdayEighthLessonTeacherSG: req.body.saturdayEighthLessonTeacherSG,
    saturdayEighthLessonClassroomSG: req.body.saturdayEighthLessonClassroomSG,
    saturdayNinthLessonFG: req.body.saturdayNinthLessonFG,
    saturdayNinthLessonTeacherFG: req.body.saturdayNinthLessonTeacherFG,
    saturdayNinthLessonClassroomFG: req.body.saturdayNinthLessonClassroomFG,
    saturdayNinthLessonSG: req.body.saturdayNinthLessonSG,
    saturdayNinthLessonTeacherSG: req.body.saturdayNinthLessonTeacherSG,
    saturdayNinthLessonClassroomSG: req.body.saturdayNinthLessonClassroomSG,
    saturdayTenthLessonFG: req.body.saturdayTenthLessonFG,
    saturdayTenthLessonTeacherFG: req.body.saturdayTenthLessonTeacherFG,
    saturdayTenthLessonClassroomFG: req.body.saturdayTenthLessonClassroomFG,
    saturdayTenthLessonSG: req.body.saturdayTenthLessonSG,
    saturdayTenthLessonTeacherSG: req.body.saturdayTenthLessonTeacherSG,
    saturdayTenthLessonClassroomSG: req.body.saturdayTenthLessonClassroomSG,

  });
  Grade.updateOne({ _id: req.params.id }, grade)
    .then(result => {
      if (result.n > 0) {
        res.status(200).json({ message: "Update successful!" });
      } else {
        res.status(401).json({ message: "Not authorized!" });
      }
    })
    .catch(error => {
      res.status(500).json({
        message: "Couldn't udpate grade!"
      });
    });
};

exports.getGrades = (req, res, next) => {
  Grade.find().then(documents => {
    res.status(200).json({
      message: "Grades fetched successfully!",
      grades: documents
    });
  })
    .catch(error => {
      res.status(500).json({
        message: "Fetching grades failed!"
      });
    });
};

exports.getGrade = (req, res, next) => {
  Grade.findById(req.params.id).then(grade => {
    if (grade) {
      res.status(200).json(grade);
    } else {
      res.status(404).json({ message: "Grade not found!" });
    }
  })
    .catch(error => {
      res.status(500).json({
        message: "Fetching grade failed!"
      });
    });
};

exports.deleteGrade = (req, res, next) => {
  Grade.deleteOne({ _id: req.params.id })
    .then(result => {
      console.log(result);
      if (result.n > 0) {
        res.status(200).json({ message: "Deletion successful!" });
      } else {
        res.status(401).json({ message: "Not authorized!" });
      }
    })
    .catch(error => {
      res.status(500).json({
        message: "Deleting grades failed!"
      });
    });
};
