import { Component, OnInit, OnDestroy } from '@angular/core';
import { SubjectModel } from 'src/app/subjects/subject.model';
import { Subscription } from 'rxjs';
import { SubjectsService } from 'src/app/subjects/subjects.service';
import { GradesService } from '../grades.service';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { AuthService } from 'src/app/auth/auth.service';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { GradeModel } from '../grade.model';

@Component({
  selector: 'app-schedule-create',
  templateUrl: './schedule-create.component.html',
  styleUrls: ['./schedule-create.component.css']
})
export class ScheduleCreateComponent implements OnInit, OnDestroy {
  subjects: SubjectModel[] = [];
  grades: GradeModel[] = [];
  private gradesSub: Subscription;
  private subjectsSub: Subscription;
  grade: GradeModel;
  isLoading = false;
  form: FormGroup;
  // subjects: SubjectModel[] = [];
  // private gradeId: string;
  private authStatusSub: Subscription;
  // private subjectsSub: Subscription;
  private mode;
  private gradeId: string;

  constructor(
    public subjectsService: SubjectsService,
    public gradesService: GradesService,
    public route: ActivatedRoute,
    private authService: AuthService) { }

  ngOnInit() {
    this.authStatusSub = this.authService
      .getAuthStatusListener()
      .subscribe(authStatus => {
        this.isLoading = false;
      });

      this.gradesService.getGrades();
      this.gradesSub = this.gradesService
      .getGradeUpdateListener()
      .subscribe(( grades: GradeModel[] ) => {
        this.isLoading = false;
        this.grades = grades;
      });

      this.subjectsService.getSubjects();
      this.subjectsSub = this.subjectsService
      .getSubjectUpdateListener()
      .subscribe(( subjects: SubjectModel[] ) => {
        this.isLoading = false;
        this.subjects = subjects;
      });

    this.form = new FormGroup({
      gradeNumber: new FormControl(null, {
        validators: [Validators.required]
      }),
      gradeLiter: new FormControl(null, {
        validators: [Validators.required]
      }),
      mondayFirstLessonFG: new FormControl(null),
      mondayFirstLessonTeacherFG: new FormControl(null),
      mondayFirstLessonClassroomFG: new FormControl(null),
      mondayFirstLessonSG: new FormControl(null),
      mondayFirstLessonTeacherSG: new FormControl(null),
      mondayFirstLessonClassroomSG: new FormControl(null),
      mondaySecondLessonFG: new FormControl(null),
      mondaySecondLessonTeacherFG: new FormControl(null),
      mondaySecondLessonClassroomFG: new FormControl(null),
      mondaySecondLessonSG: new FormControl(null),
      mondaySecondLessonTeacherSG: new FormControl(null),
      mondaySecondLessonClassroomSG: new FormControl(null),
      mondayThirdLessonFG: new FormControl(null),
      mondayThirdLessonTeacherFG: new FormControl(null),
      mondayThirdLessonClassroomFG: new FormControl(null),
      mondayThirdLessonSG: new FormControl(null),
      mondayThirdLessonTeacherSG: new FormControl(null),
      mondayThirdLessonClassroomSG: new FormControl(null),
      mondayFourthLessonFG: new FormControl(null),
      mondayFourthLessonTeacherFG: new FormControl(null),
      mondayFourthLessonClassroomFG: new FormControl(null),
      mondayFourthLessonSG: new FormControl(null),
      mondayFourthLessonTeacherSG: new FormControl(null),
      mondayFourthLessonClassroomSG: new FormControl(null),
      mondayFifthLessonFG: new FormControl(null),
      mondayFifthLessonTeacherFG: new FormControl(null),
      mondayFifthLessonClassroomFG: new FormControl(null),
      mondayFifthLessonSG: new FormControl(null),
      mondayFifthLessonTeacherSG: new FormControl(null),
      mondayFifthLessonClassroomSG: new FormControl(null),
      mondaySixthLessonFG: new FormControl(null),
      mondaySixthLessonTeacherFG: new FormControl(null),
      mondaySixthLessonClassroomFG: new FormControl(null),
      mondaySixthLessonSG: new FormControl(null),
      mondaySixthLessonTeacherSG: new FormControl(null),
      mondaySixthLessonClassroomSG: new FormControl(null),
      mondaySeventhLessonFG: new FormControl(null),
      mondaySeventhLessonTeacherFG: new FormControl(null),
      mondaySeventhLessonClassroomFG: new FormControl(null),
      mondaySeventhLessonSG: new FormControl(null),
      mondaySeventhLessonTeacherSG: new FormControl(null),
      mondaySeventhLessonClassroomSG: new FormControl(null),
      mondayEighthLessonFG: new FormControl(null),
      mondayEighthLessonTeacherFG: new FormControl(null),
      mondayEighthLessonClassroomFG: new FormControl(null),
      mondayEighthLessonSG: new FormControl(null),
      mondayEighthLessonTeacherSG: new FormControl(null),
      mondayEighthLessonClassroomSG: new FormControl(null),
      mondayNinthLessonFG: new FormControl(null),
      mondayNinthLessonTeacherFG: new FormControl(null),
      mondayNinthLessonClassroomFG: new FormControl(null),
      mondayNinthLessonSG: new FormControl(null),
      mondayNinthLessonTeacherSG: new FormControl(null),
      mondayNinthLessonClassroomSG: new FormControl(null),
      mondayTenthLessonFG: new FormControl(null),
      mondayTenthLessonTeacherFG: new FormControl(null),
      mondayTenthLessonClassroomFG: new FormControl(null),
      mondayTenthLessonSG: new FormControl(null),
      mondayTenthLessonTeacherSG: new FormControl(null),
      mondayTenthLessonClassroomSG: new FormControl(null),

      tuesdayFirstLessonFG: new FormControl(null),
      tuesdayFirstLessonTeacherFG: new FormControl(null),
      tuesdayFirstLessonClassroomFG: new FormControl(null),
      tuesdayFirstLessonSG: new FormControl(null),
      tuesdayFirstLessonTeacherSG: new FormControl(null),
      tuesdayFirstLessonClassroomSG: new FormControl(null),
      tuesdaySecondLessonFG: new FormControl(null),
      tuesdaySecondLessonTeacherFG: new FormControl(null),
      tuesdaySecondLessonClassroomFG: new FormControl(null),
      tuesdaySecondLessonSG: new FormControl(null),
      tuesdaySecondLessonTeacherSG: new FormControl(null),
      tuesdaySecondLessonClassroomSG: new FormControl(null),
      tuesdayThirdLessonFG: new FormControl(null),
      tuesdayThirdLessonTeacherFG: new FormControl(null),
      tuesdayThirdLessonClassroomFG: new FormControl(null),
      tuesdayThirdLessonSG: new FormControl(null),
      tuesdayThirdLessonTeacherSG: new FormControl(null),
      tuesdayThirdLessonClassroomSG: new FormControl(null),
      tuesdayFourthLessonFG: new FormControl(null),
      tuesdayFourthLessonTeacherFG: new FormControl(null),
      tuesdayFourthLessonClassroomFG: new FormControl(null),
      tuesdayFourthLessonSG: new FormControl(null),
      tuesdayFourthLessonTeacherSG: new FormControl(null),
      tuesdayFourthLessonClassroomSG: new FormControl(null),
      tuesdayFifthLessonFG: new FormControl(null),
      tuesdayFifthLessonTeacherFG: new FormControl(null),
      tuesdayFifthLessonClassroomFG: new FormControl(null),
      tuesdayFifthLessonSG: new FormControl(null),
      tuesdayFifthLessonTeacherSG: new FormControl(null),
      tuesdayFifthLessonClassroomSG: new FormControl(null),
      tuesdaySixthLessonFG: new FormControl(null),
      tuesdaySixthLessonTeacherFG: new FormControl(null),
      tuesdaySixthLessonClassroomFG: new FormControl(null),
      tuesdaySixthLessonSG: new FormControl(null),
      tuesdaySixthLessonTeacherSG: new FormControl(null),
      tuesdaySixthLessonClassroomSG: new FormControl(null),
      tuesdaySeventhLessonFG: new FormControl(null),
      tuesdaySeventhLessonTeacherFG: new FormControl(null),
      tuesdaySeventhLessonClassroomFG: new FormControl(null),
      tuesdaySeventhLessonSG: new FormControl(null),
      tuesdaySeventhLessonTeacherSG: new FormControl(null),
      tuesdaySeventhLessonClassroomSG: new FormControl(null),
      tuesdayEighthLessonFG: new FormControl(null),
      tuesdayEighthLessonTeacherFG: new FormControl(null),
      tuesdayEighthLessonClassroomFG: new FormControl(null),
      tuesdayEighthLessonSG: new FormControl(null),
      tuesdayEighthLessonTeacherSG: new FormControl(null),
      tuesdayEighthLessonClassroomSG: new FormControl(null),
      tuesdayNinthLessonFG: new FormControl(null),
      tuesdayNinthLessonTeacherFG: new FormControl(null),
      tuesdayNinthLessonClassroomFG: new FormControl(null),
      tuesdayNinthLessonSG: new FormControl(null),
      tuesdayNinthLessonTeacherSG: new FormControl(null),
      tuesdayNinthLessonClassroomSG: new FormControl(null),
      tuesdayTenthLessonFG: new FormControl(null),
      tuesdayTenthLessonTeacherFG: new FormControl(null),
      tuesdayTenthLessonClassroomFG: new FormControl(null),
      tuesdayTenthLessonSG: new FormControl(null),
      tuesdayTenthLessonTeacherSG: new FormControl(null),
      tuesdayTenthLessonClassroomSG: new FormControl(null),

      wednesdayFirstLessonFG: new FormControl(null),
      wednesdayFirstLessonTeacherFG: new FormControl(null),
      wednesdayFirstLessonClassroomFG: new FormControl(null),
      wednesdayFirstLessonSG: new FormControl(null),
      wednesdayFirstLessonTeacherSG: new FormControl(null),
      wednesdayFirstLessonClassroomSG: new FormControl(null),
      wednesdaySecondLessonFG: new FormControl(null),
      wednesdaySecondLessonTeacherFG: new FormControl(null),
      wednesdaySecondLessonClassroomFG: new FormControl(null),
      wednesdaySecondLessonSG: new FormControl(null),
      wednesdaySecondLessonTeacherSG: new FormControl(null),
      wednesdaySecondLessonClassroomSG: new FormControl(null),
      wednesdayThirdLessonFG: new FormControl(null),
      wednesdayThirdLessonTeacherFG: new FormControl(null),
      wednesdayThirdLessonClassroomFG: new FormControl(null),
      wednesdayThirdLessonSG: new FormControl(null),
      wednesdayThirdLessonTeacherSG: new FormControl(null),
      wednesdayThirdLessonClassroomSG: new FormControl(null),
      wednesdayFourthLessonFG: new FormControl(null),
      wednesdayFourthLessonTeacherFG: new FormControl(null),
      wednesdayFourthLessonClassroomFG: new FormControl(null),
      wednesdayFourthLessonSG: new FormControl(null),
      wednesdayFourthLessonTeacherSG: new FormControl(null),
      wednesdayFourthLessonClassroomSG: new FormControl(null),
      wednesdayFifthLessonFG: new FormControl(null),
      wednesdayFifthLessonTeacherFG: new FormControl(null),
      wednesdayFifthLessonClassroomFG: new FormControl(null),
      wednesdayFifthLessonSG: new FormControl(null),
      wednesdayFifthLessonTeacherSG: new FormControl(null),
      wednesdayFifthLessonClassroomSG: new FormControl(null),
      wednesdaySixthLessonFG: new FormControl(null),
      wednesdaySixthLessonTeacherFG: new FormControl(null),
      wednesdaySixthLessonClassroomFG: new FormControl(null),
      wednesdaySixthLessonSG: new FormControl(null),
      wednesdaySixthLessonTeacherSG: new FormControl(null),
      wednesdaySixthLessonClassroomSG: new FormControl(null),
      wednesdaySeventhLessonFG: new FormControl(null),
      wednesdaySeventhLessonTeacherFG: new FormControl(null),
      wednesdaySeventhLessonClassroomFG: new FormControl(null),
      wednesdaySeventhLessonSG: new FormControl(null),
      wednesdaySeventhLessonTeacherSG: new FormControl(null),
      wednesdaySeventhLessonClassroomSG: new FormControl(null),
      wednesdayEighthLessonFG: new FormControl(null),
      wednesdayEighthLessonTeacherFG: new FormControl(null),
      wednesdayEighthLessonClassroomFG: new FormControl(null),
      wednesdayEighthLessonSG: new FormControl(null),
      wednesdayEighthLessonTeacherSG: new FormControl(null),
      wednesdayEighthLessonClassroomSG: new FormControl(null),
      wednesdayNinthLessonFG: new FormControl(null),
      wednesdayNinthLessonTeacherFG: new FormControl(null),
      wednesdayNinthLessonClassroomFG: new FormControl(null),
      wednesdayNinthLessonSG: new FormControl(null),
      wednesdayNinthLessonTeacherSG: new FormControl(null),
      wednesdayNinthLessonClassroomSG: new FormControl(null),
      wednesdayTenthLessonFG: new FormControl(null),
      wednesdayTenthLessonTeacherFG: new FormControl(null),
      wednesdayTenthLessonClassroomFG: new FormControl(null),
      wednesdayTenthLessonSG: new FormControl(null),
      wednesdayTenthLessonTeacherSG: new FormControl(null),
      wednesdayTenthLessonClassroomSG: new FormControl(null),

      thursdayFirstLessonFG: new FormControl(null),
      thursdayFirstLessonTeacherFG: new FormControl(null),
      thursdayFirstLessonClassroomFG: new FormControl(null),
      thursdayFirstLessonSG: new FormControl(null),
      thursdayFirstLessonTeacherSG: new FormControl(null),
      thursdayFirstLessonClassroomSG: new FormControl(null),
      thursdaySecondLessonFG: new FormControl(null),
      thursdaySecondLessonTeacherFG: new FormControl(null),
      thursdaySecondLessonClassroomFG: new FormControl(null),
      thursdaySecondLessonSG: new FormControl(null),
      thursdaySecondLessonTeacherSG: new FormControl(null),
      thursdaySecondLessonClassroomSG: new FormControl(null),
      thursdayThirdLessonFG: new FormControl(null),
      thursdayThirdLessonTeacherFG: new FormControl(null),
      thursdayThirdLessonClassroomFG: new FormControl(null),
      thursdayThirdLessonSG: new FormControl(null),
      thursdayThirdLessonTeacherSG: new FormControl(null),
      thursdayThirdLessonClassroomSG: new FormControl(null),
      thursdayFourthLessonFG: new FormControl(null),
      thursdayFourthLessonTeacherFG: new FormControl(null),
      thursdayFourthLessonClassroomFG: new FormControl(null),
      thursdayFourthLessonSG: new FormControl(null),
      thursdayFourthLessonTeacherSG: new FormControl(null),
      thursdayFourthLessonClassroomSG: new FormControl(null),
      thursdayFifthLessonFG: new FormControl(null),
      thursdayFifthLessonTeacherFG: new FormControl(null),
      thursdayFifthLessonClassroomFG: new FormControl(null),
      thursdayFifthLessonSG: new FormControl(null),
      thursdayFifthLessonTeacherSG: new FormControl(null),
      thursdayFifthLessonClassroomSG: new FormControl(null),
      thursdaySixthLessonFG: new FormControl(null),
      thursdaySixthLessonTeacherFG: new FormControl(null),
      thursdaySixthLessonClassroomFG: new FormControl(null),
      thursdaySixthLessonSG: new FormControl(null),
      thursdaySixthLessonTeacherSG: new FormControl(null),
      thursdaySixthLessonClassroomSG: new FormControl(null),
      thursdaySeventhLessonFG: new FormControl(null),
      thursdaySeventhLessonTeacherFG: new FormControl(null),
      thursdaySeventhLessonClassroomFG: new FormControl(null),
      thursdaySeventhLessonSG: new FormControl(null),
      thursdaySeventhLessonTeacherSG: new FormControl(null),
      thursdaySeventhLessonClassroomSG: new FormControl(null),
      thursdayEighthLessonFG: new FormControl(null),
      thursdayEighthLessonTeacherFG: new FormControl(null),
      thursdayEighthLessonClassroomFG: new FormControl(null),
      thursdayEighthLessonSG: new FormControl(null),
      thursdayEighthLessonTeacherSG: new FormControl(null),
      thursdayEighthLessonClassroomSG: new FormControl(null),
      thursdayNinthLessonFG: new FormControl(null),
      thursdayNinthLessonTeacherFG: new FormControl(null),
      thursdayNinthLessonClassroomFG: new FormControl(null),
      thursdayNinthLessonSG: new FormControl(null),
      thursdayNinthLessonTeacherSG: new FormControl(null),
      thursdayNinthLessonClassroomSG: new FormControl(null),
      thursdayTenthLessonFG: new FormControl(null),
      thursdayTenthLessonTeacherFG: new FormControl(null),
      thursdayTenthLessonClassroomFG: new FormControl(null),
      thursdayTenthLessonSG: new FormControl(null),
      thursdayTenthLessonTeacherSG: new FormControl(null),
      thursdayTenthLessonClassroomSG: new FormControl(null),

      fridayFirstLessonFG: new FormControl(null),
      fridayFirstLessonTeacherFG: new FormControl(null),
      fridayFirstLessonClassroomFG: new FormControl(null),
      fridayFirstLessonSG: new FormControl(null),
      fridayFirstLessonTeacherSG: new FormControl(null),
      fridayFirstLessonClassroomSG: new FormControl(null),
      fridaySecondLessonFG: new FormControl(null),
      fridaySecondLessonTeacherFG: new FormControl(null),
      fridaySecondLessonClassroomFG: new FormControl(null),
      fridaySecondLessonSG: new FormControl(null),
      fridaySecondLessonTeacherSG: new FormControl(null),
      fridaySecondLessonClassroomSG: new FormControl(null),
      fridayThirdLessonFG: new FormControl(null),
      fridayThirdLessonTeacherFG: new FormControl(null),
      fridayThirdLessonClassroomFG: new FormControl(null),
      fridayThirdLessonSG: new FormControl(null),
      fridayThirdLessonTeacherSG: new FormControl(null),
      fridayThirdLessonClassroomSG: new FormControl(null),
      fridayFourthLessonFG: new FormControl(null),
      fridayFourthLessonTeacherFG: new FormControl(null),
      fridayFourthLessonClassroomFG: new FormControl(null),
      fridayFourthLessonSG: new FormControl(null),
      fridayFourthLessonTeacherSG: new FormControl(null),
      fridayFourthLessonClassroomSG: new FormControl(null),
      fridayFifthLessonFG: new FormControl(null),
      fridayFifthLessonTeacherFG: new FormControl(null),
      fridayFifthLessonClassroomFG: new FormControl(null),
      fridayFifthLessonSG: new FormControl(null),
      fridayFifthLessonTeacherSG: new FormControl(null),
      fridayFifthLessonClassroomSG: new FormControl(null),
      fridaySixthLessonFG: new FormControl(null),
      fridaySixthLessonTeacherFG: new FormControl(null),
      fridaySixthLessonClassroomFG: new FormControl(null),
      fridaySixthLessonSG: new FormControl(null),
      fridaySixthLessonTeacherSG: new FormControl(null),
      fridaySixthLessonClassroomSG: new FormControl(null),
      fridaySeventhLessonFG: new FormControl(null),
      fridaySeventhLessonTeacherFG: new FormControl(null),
      fridaySeventhLessonClassroomFG: new FormControl(null),
      fridaySeventhLessonSG: new FormControl(null),
      fridaySeventhLessonTeacherSG: new FormControl(null),
      fridaySeventhLessonClassroomSG: new FormControl(null),
      fridayEighthLessonFG: new FormControl(null),
      fridayEighthLessonTeacherFG: new FormControl(null),
      fridayEighthLessonClassroomFG: new FormControl(null),
      fridayEighthLessonSG: new FormControl(null),
      fridayEighthLessonTeacherSG: new FormControl(null),
      fridayEighthLessonClassroomSG: new FormControl(null),
      fridayNinthLessonFG: new FormControl(null),
      fridayNinthLessonTeacherFG: new FormControl(null),
      fridayNinthLessonClassroomFG: new FormControl(null),
      fridayNinthLessonSG: new FormControl(null),
      fridayNinthLessonTeacherSG: new FormControl(null),
      fridayNinthLessonClassroomSG: new FormControl(null),
      fridayTenthLessonFG: new FormControl(null),
      fridayTenthLessonTeacherFG: new FormControl(null),
      fridayTenthLessonClassroomFG: new FormControl(null),
      fridayTenthLessonSG: new FormControl(null),
      fridayTenthLessonTeacherSG: new FormControl(null),
      fridayTenthLessonClassroomSG: new FormControl(null),

      saturdayFirstLessonFG: new FormControl(null),
      saturdayFirstLessonTeacherFG: new FormControl(null),
      saturdayFirstLessonClassroomFG: new FormControl(null),
      saturdayFirstLessonSG: new FormControl(null),
      saturdayFirstLessonTeacherSG: new FormControl(null),
      saturdayFirstLessonClassroomSG: new FormControl(null),
      saturdaySecondLessonFG: new FormControl(null),
      saturdaySecondLessonTeacherFG: new FormControl(null),
      saturdaySecondLessonClassroomFG: new FormControl(null),
      saturdaySecondLessonSG: new FormControl(null),
      saturdaySecondLessonTeacherSG: new FormControl(null),
      saturdaySecondLessonClassroomSG: new FormControl(null),
      saturdayThirdLessonFG: new FormControl(null),
      saturdayThirdLessonTeacherFG: new FormControl(null),
      saturdayThirdLessonClassroomFG: new FormControl(null),
      saturdayThirdLessonSG: new FormControl(null),
      saturdayThirdLessonTeacherSG: new FormControl(null),
      saturdayThirdLessonClassroomSG: new FormControl(null),
      saturdayFourthLessonFG: new FormControl(null),
      saturdayFourthLessonTeacherFG: new FormControl(null),
      saturdayFourthLessonClassroomFG: new FormControl(null),
      saturdayFourthLessonSG: new FormControl(null),
      saturdayFourthLessonTeacherSG: new FormControl(null),
      saturdayFourthLessonClassroomSG: new FormControl(null),
      saturdayFifthLessonFG: new FormControl(null),
      saturdayFifthLessonTeacherFG: new FormControl(null),
      saturdayFifthLessonClassroomFG: new FormControl(null),
      saturdayFifthLessonSG: new FormControl(null),
      saturdayFifthLessonTeacherSG: new FormControl(null),
      saturdayFifthLessonClassroomSG: new FormControl(null),
      saturdaySixthLessonFG: new FormControl(null),
      saturdaySixthLessonTeacherFG: new FormControl(null),
      saturdaySixthLessonClassroomFG: new FormControl(null),
      saturdaySixthLessonSG: new FormControl(null),
      saturdaySixthLessonTeacherSG: new FormControl(null),
      saturdaySixthLessonClassroomSG: new FormControl(null),
      saturdaySeventhLessonFG: new FormControl(null),
      saturdaySeventhLessonTeacherFG: new FormControl(null),
      saturdaySeventhLessonClassroomFG: new FormControl(null),
      saturdaySeventhLessonSG: new FormControl(null),
      saturdaySeventhLessonTeacherSG: new FormControl(null),
      saturdaySeventhLessonClassroomSG: new FormControl(null),
      saturdayEighthLessonFG: new FormControl(null),
      saturdayEighthLessonTeacherFG: new FormControl(null),
      saturdayEighthLessonClassroomFG: new FormControl(null),
      saturdayEighthLessonSG: new FormControl(null),
      saturdayEighthLessonTeacherSG: new FormControl(null),
      saturdayEighthLessonClassroomSG: new FormControl(null),
      saturdayNinthLessonFG: new FormControl(null),
      saturdayNinthLessonTeacherFG: new FormControl(null),
      saturdayNinthLessonClassroomFG: new FormControl(null),
      saturdayNinthLessonSG: new FormControl(null),
      saturdayNinthLessonTeacherSG: new FormControl(null),
      saturdayNinthLessonClassroomSG: new FormControl(null),
      saturdayTenthLessonFG: new FormControl(null),
      saturdayTenthLessonTeacherFG: new FormControl(null),
      saturdayTenthLessonClassroomFG: new FormControl(null),
      saturdayTenthLessonSG: new FormControl(null),
      saturdayTenthLessonTeacherSG: new FormControl(null),
      saturdayTenthLessonClassroomSG: new FormControl(null),
    });

    this.route.paramMap.subscribe((paramMap: ParamMap) => {
        this.mode = 'edit';
        this.gradeId = paramMap.get('gradeId');
        this.isLoading = true;
        this.gradesService.getGrade(this.gradeId).subscribe(gradeData => {
          this.isLoading = false;
          this.grade = {
            id: gradeData._id,

            gradeNumber: gradeData.gradeNumber,
            gradeLiter: gradeData.gradeLiter,

            mondayFirstLessonFG: gradeData.mondayFirstLessonFG,
            mondayFirstLessonTeacherFG: gradeData.mondayFirstLessonTeacherFG,
            mondayFirstLessonClassroomFG: gradeData.mondayFirstLessonClassroomFG,
            mondayFirstLessonSG: gradeData.mondayFirstLessonSG,
            mondayFirstLessonTeacherSG: gradeData.mondayFirstLessonTeacherSG,
            mondayFirstLessonClassroomSG: gradeData.mondayFirstLessonClassroomSG,
            mondaySecondLessonFG: gradeData.mondaySecondLessonFG,
            mondaySecondLessonTeacherFG: gradeData.mondaySecondLessonTeacherFG,
            mondaySecondLessonClassroomFG: gradeData.mondaySecondLessonClassroomFG,
            mondaySecondLessonSG: gradeData.mondaySecondLessonSG,
            mondaySecondLessonTeacherSG: gradeData.mondaySecondLessonTeacherSG,
            mondaySecondLessonClassroomSG: gradeData.mondaySecondLessonClassroomSG,
            mondayThirdLessonFG: gradeData.mondayThirdLessonFG,
            mondayThirdLessonTeacherFG: gradeData.mondayThirdLessonTeacherFG,
            mondayThirdLessonClassroomFG: gradeData.mondayThirdLessonClassroomFG,
            mondayThirdLessonSG: gradeData.mondayThirdLessonSG,
            mondayThirdLessonTeacherSG: gradeData.mondayThirdLessonTeacherSG,
            mondayThirdLessonClassroomSG: gradeData.mondayThirdLessonClassroomSG,
            mondayFourthLessonFG: gradeData.mondayFourthLessonFG,
            mondayFourthLessonTeacherFG: gradeData.mondayFourthLessonTeacherFG,
            mondayFourthLessonClassroomFG: gradeData.mondayFourthLessonClassroomFG,
            mondayFourthLessonSG: gradeData.mondayFourthLessonSG,
            mondayFourthLessonTeacherSG: gradeData.mondayFourthLessonTeacherSG,
            mondayFourthLessonClassroomSG: gradeData.mondayFourthLessonClassroomSG,
            mondayFifthLessonFG: gradeData.mondayFifthLessonFG,
            mondayFifthLessonTeacherFG: gradeData.mondayFifthLessonTeacherFG,
            mondayFifthLessonClassroomFG: gradeData.mondayFifthLessonClassroomFG,
            mondayFifthLessonSG: gradeData.mondayFifthLessonSG,
            mondayFifthLessonTeacherSG: gradeData.mondayFifthLessonTeacherSG,
            mondayFifthLessonClassroomSG: gradeData.mondayFifthLessonClassroomSG,
            mondaySixthLessonFG: gradeData.mondaySixthLessonFG,
            mondaySixthLessonTeacherFG: gradeData.mondaySixthLessonTeacherFG,
            mondaySixthLessonClassroomFG: gradeData.mondaySixthLessonClassroomFG,
            mondaySixthLessonSG: gradeData.mondaySixthLessonSG,
            mondaySixthLessonTeacherSG: gradeData.mondaySixthLessonTeacherSG,
            mondaySixthLessonClassroomSG: gradeData.mondaySixthLessonClassroomSG,
            mondaySeventhLessonFG: gradeData.mondaySeventhLessonFG,
            mondaySeventhLessonTeacherFG: gradeData.mondaySeventhLessonTeacherFG,
            mondaySeventhLessonClassroomFG: gradeData.mondaySeventhLessonClassroomFG,
            mondaySeventhLessonSG: gradeData.mondaySeventhLessonSG,
            mondaySeventhLessonTeacherSG: gradeData.mondaySeventhLessonTeacherSG,
            mondaySeventhLessonClassroomSG: gradeData.mondaySeventhLessonClassroomSG,
            mondayEighthLessonFG: gradeData.mondayEighthLessonFG,
            mondayEighthLessonTeacherFG: gradeData.mondayEighthLessonTeacherFG,
            mondayEighthLessonClassroomFG: gradeData.mondayEighthLessonClassroomFG,
            mondayEighthLessonSG: gradeData.mondayEighthLessonSG,
            mondayEighthLessonTeacherSG: gradeData.mondayEighthLessonTeacherSG,
            mondayEighthLessonClassroomSG: gradeData.mondayEighthLessonClassroomSG,
            mondayNinthLessonFG: gradeData.mondayNinthLessonFG,
            mondayNinthLessonTeacherFG: gradeData.mondayNinthLessonTeacherFG,
            mondayNinthLessonClassroomFG: gradeData.mondayNinthLessonClassroomFG,
            mondayNinthLessonSG: gradeData.mondayNinthLessonSG,
            mondayNinthLessonTeacherSG: gradeData.mondayNinthLessonTeacherSG,
            mondayNinthLessonClassroomSG: gradeData.mondayNinthLessonClassroomSG,
            mondayTenthLessonFG: gradeData.mondayTenthLessonFG,
            mondayTenthLessonTeacherFG: gradeData.mondayTenthLessonTeacherFG,
            mondayTenthLessonClassroomFG: gradeData.mondayTenthLessonClassroomFG,
            mondayTenthLessonSG: gradeData.mondayTenthLessonSG,
            mondayTenthLessonTeacherSG: gradeData.mondayTenthLessonTeacherSG,
            mondayTenthLessonClassroomSG: gradeData.mondayTenthLessonClassroomSG,

            tuesdayFirstLessonFG: gradeData.tuesdayFirstLessonFG,
            tuesdayFirstLessonTeacherFG: gradeData.tuesdayFirstLessonTeacherFG,
            tuesdayFirstLessonClassroomFG: gradeData.tuesdayFirstLessonClassroomFG,
            tuesdayFirstLessonSG: gradeData.tuesdayFirstLessonSG,
            tuesdayFirstLessonTeacherSG: gradeData.tuesdayFirstLessonTeacherSG,
            tuesdayFirstLessonClassroomSG: gradeData.tuesdayFirstLessonClassroomSG,
            tuesdaySecondLessonFG: gradeData.tuesdaySecondLessonFG,
            tuesdaySecondLessonTeacherFG: gradeData.tuesdaySecondLessonTeacherFG,
            tuesdaySecondLessonClassroomFG: gradeData.tuesdaySecondLessonClassroomFG,
            tuesdaySecondLessonSG: gradeData.tuesdaySecondLessonSG,
            tuesdaySecondLessonTeacherSG: gradeData.tuesdaySecondLessonTeacherSG,
            tuesdaySecondLessonClassroomSG: gradeData.tuesdaySecondLessonClassroomSG,
            tuesdayThirdLessonFG: gradeData.tuesdayThirdLessonFG,
            tuesdayThirdLessonTeacherFG: gradeData.tuesdayThirdLessonTeacherFG,
            tuesdayThirdLessonClassroomFG: gradeData.tuesdayThirdLessonClassroomFG,
            tuesdayThirdLessonSG: gradeData.tuesdayThirdLessonSG,
            tuesdayThirdLessonTeacherSG: gradeData.tuesdayThirdLessonTeacherSG,
            tuesdayThirdLessonClassroomSG: gradeData.tuesdayThirdLessonClassroomSG,
            tuesdayFourthLessonFG: gradeData.tuesdayFourthLessonFG,
            tuesdayFourthLessonTeacherFG: gradeData.tuesdayFourthLessonTeacherFG,
            tuesdayFourthLessonClassroomFG: gradeData.tuesdayFourthLessonClassroomFG,
            tuesdayFourthLessonSG: gradeData.tuesdayFourthLessonSG,
            tuesdayFourthLessonTeacherSG: gradeData.tuesdayFourthLessonTeacherSG,
            tuesdayFourthLessonClassroomSG: gradeData.tuesdayFourthLessonClassroomSG,
            tuesdayFifthLessonFG: gradeData.tuesdayFifthLessonFG,
            tuesdayFifthLessonTeacherFG: gradeData.tuesdayFifthLessonTeacherFG,
            tuesdayFifthLessonClassroomFG: gradeData.tuesdayFifthLessonClassroomFG,
            tuesdayFifthLessonSG: gradeData.tuesdayFifthLessonSG,
            tuesdayFifthLessonTeacherSG: gradeData.tuesdayFifthLessonTeacherSG,
            tuesdayFifthLessonClassroomSG: gradeData.tuesdayFifthLessonClassroomSG,
            tuesdaySixthLessonFG: gradeData.tuesdaySixthLessonFG,
            tuesdaySixthLessonTeacherFG: gradeData.tuesdaySixthLessonTeacherFG,
            tuesdaySixthLessonClassroomFG: gradeData.tuesdaySixthLessonClassroomFG,
            tuesdaySixthLessonSG: gradeData.tuesdaySixthLessonSG,
            tuesdaySixthLessonTeacherSG: gradeData.tuesdaySixthLessonTeacherSG,
            tuesdaySixthLessonClassroomSG: gradeData.tuesdaySixthLessonClassroomSG,
            tuesdaySeventhLessonFG: gradeData.tuesdaySeventhLessonFG,
            tuesdaySeventhLessonTeacherFG: gradeData.tuesdaySeventhLessonTeacherFG,
            tuesdaySeventhLessonClassroomFG: gradeData.tuesdaySeventhLessonClassroomFG,
            tuesdaySeventhLessonSG: gradeData.tuesdaySeventhLessonSG,
            tuesdaySeventhLessonTeacherSG: gradeData.tuesdaySeventhLessonTeacherSG,
            tuesdaySeventhLessonClassroomSG: gradeData.tuesdaySeventhLessonClassroomSG,
            tuesdayEighthLessonFG: gradeData.tuesdayEighthLessonFG,
            tuesdayEighthLessonTeacherFG: gradeData.tuesdayEighthLessonTeacherFG,
            tuesdayEighthLessonClassroomFG: gradeData.tuesdayEighthLessonClassroomFG,
            tuesdayEighthLessonSG: gradeData.tuesdayEighthLessonSG,
            tuesdayEighthLessonTeacherSG: gradeData.tuesdayEighthLessonTeacherSG,
            tuesdayEighthLessonClassroomSG: gradeData.tuesdayEighthLessonClassroomSG,
            tuesdayNinthLessonFG: gradeData.tuesdayNinthLessonFG,
            tuesdayNinthLessonTeacherFG: gradeData.tuesdayNinthLessonTeacherFG,
            tuesdayNinthLessonClassroomFG: gradeData.tuesdayNinthLessonClassroomFG,
            tuesdayNinthLessonSG: gradeData.tuesdayNinthLessonSG,
            tuesdayNinthLessonTeacherSG: gradeData.tuesdayNinthLessonTeacherSG,
            tuesdayNinthLessonClassroomSG: gradeData.tuesdayNinthLessonClassroomSG,
            tuesdayTenthLessonFG: gradeData.tuesdayTenthLessonFG,
            tuesdayTenthLessonTeacherFG: gradeData.tuesdayTenthLessonTeacherFG,
            tuesdayTenthLessonClassroomFG: gradeData.tuesdayTenthLessonClassroomFG,
            tuesdayTenthLessonSG: gradeData.tuesdayTenthLessonSG,
            tuesdayTenthLessonTeacherSG: gradeData.tuesdayTenthLessonTeacherSG,
            tuesdayTenthLessonClassroomSG: gradeData.tuesdayTenthLessonClassroomSG,

            wednesdayFirstLessonFG: gradeData.wednesdayFirstLessonFG,
            wednesdayFirstLessonTeacherFG: gradeData.wednesdayFirstLessonTeacherFG,
            wednesdayFirstLessonClassroomFG: gradeData.wednesdayFirstLessonClassroomFG,
            wednesdayFirstLessonSG: gradeData.wednesdayFirstLessonSG,
            wednesdayFirstLessonTeacherSG: gradeData.wednesdayFirstLessonTeacherSG,
            wednesdayFirstLessonClassroomSG: gradeData.wednesdayFirstLessonClassroomSG,
            wednesdaySecondLessonFG: gradeData.wednesdaySecondLessonFG,
            wednesdaySecondLessonTeacherFG: gradeData.wednesdaySecondLessonTeacherFG,
            wednesdaySecondLessonClassroomFG: gradeData.wednesdaySecondLessonClassroomFG,
            wednesdaySecondLessonSG: gradeData.wednesdaySecondLessonSG,
            wednesdaySecondLessonTeacherSG: gradeData.wednesdaySecondLessonTeacherSG,
            wednesdaySecondLessonClassroomSG: gradeData.wednesdaySecondLessonClassroomSG,
            wednesdayThirdLessonFG: gradeData.wednesdayThirdLessonFG,
            wednesdayThirdLessonTeacherFG: gradeData.wednesdayThirdLessonTeacherFG,
            wednesdayThirdLessonClassroomFG: gradeData.wednesdayThirdLessonClassroomFG,
            wednesdayThirdLessonSG: gradeData.wednesdayThirdLessonSG,
            wednesdayThirdLessonTeacherSG: gradeData.wednesdayThirdLessonTeacherSG,
            wednesdayThirdLessonClassroomSG: gradeData.wednesdayThirdLessonClassroomSG,
            wednesdayFourthLessonFG: gradeData.wednesdayFourthLessonFG,
            wednesdayFourthLessonTeacherFG: gradeData.wednesdayFourthLessonTeacherFG,
            wednesdayFourthLessonClassroomFG: gradeData.wednesdayFourthLessonClassroomFG,
            wednesdayFourthLessonSG: gradeData.wednesdayFourthLessonSG,
            wednesdayFourthLessonTeacherSG: gradeData.wednesdayFourthLessonTeacherSG,
            wednesdayFourthLessonClassroomSG: gradeData.wednesdayFourthLessonClassroomSG,
            wednesdayFifthLessonFG: gradeData.wednesdayFifthLessonFG,
            wednesdayFifthLessonTeacherFG: gradeData.wednesdayFifthLessonTeacherFG,
            wednesdayFifthLessonClassroomFG: gradeData.wednesdayFifthLessonClassroomFG,
            wednesdayFifthLessonSG: gradeData.wednesdayFifthLessonSG,
            wednesdayFifthLessonTeacherSG: gradeData.wednesdayFifthLessonTeacherSG,
            wednesdayFifthLessonClassroomSG: gradeData.wednesdayFifthLessonClassroomSG,
            wednesdaySixthLessonFG: gradeData.wednesdaySixthLessonFG,
            wednesdaySixthLessonTeacherFG: gradeData.wednesdaySixthLessonTeacherFG,
            wednesdaySixthLessonClassroomFG: gradeData.wednesdaySixthLessonClassroomFG,
            wednesdaySixthLessonSG: gradeData.wednesdaySixthLessonSG,
            wednesdaySixthLessonTeacherSG: gradeData.wednesdaySixthLessonTeacherSG,
            wednesdaySixthLessonClassroomSG: gradeData.wednesdaySixthLessonClassroomSG,
            wednesdaySeventhLessonFG: gradeData.wednesdaySeventhLessonFG,
            wednesdaySeventhLessonTeacherFG: gradeData.wednesdaySeventhLessonTeacherFG,
            wednesdaySeventhLessonClassroomFG: gradeData.wednesdaySeventhLessonClassroomFG,
            wednesdaySeventhLessonSG: gradeData.wednesdaySeventhLessonSG,
            wednesdaySeventhLessonTeacherSG: gradeData.wednesdaySeventhLessonTeacherSG,
            wednesdaySeventhLessonClassroomSG: gradeData.wednesdaySeventhLessonClassroomSG,
            wednesdayEighthLessonFG: gradeData.wednesdayEighthLessonFG,
            wednesdayEighthLessonTeacherFG: gradeData.wednesdayEighthLessonTeacherFG,
            wednesdayEighthLessonClassroomFG: gradeData.wednesdayEighthLessonClassroomFG,
            wednesdayEighthLessonSG: gradeData.wednesdayEighthLessonSG,
            wednesdayEighthLessonTeacherSG: gradeData.wednesdayEighthLessonTeacherSG,
            wednesdayEighthLessonClassroomSG: gradeData.wednesdayEighthLessonClassroomSG,
            wednesdayNinthLessonFG: gradeData.wednesdayNinthLessonFG,
            wednesdayNinthLessonTeacherFG: gradeData.wednesdayNinthLessonTeacherFG,
            wednesdayNinthLessonClassroomFG: gradeData.wednesdayNinthLessonClassroomFG,
            wednesdayNinthLessonSG: gradeData.wednesdayNinthLessonSG,
            wednesdayNinthLessonTeacherSG: gradeData.wednesdayNinthLessonTeacherSG,
            wednesdayNinthLessonClassroomSG: gradeData.wednesdayNinthLessonClassroomSG,
            wednesdayTenthLessonFG: gradeData.wednesdayTenthLessonFG,
            wednesdayTenthLessonTeacherFG: gradeData.wednesdayTenthLessonTeacherFG,
            wednesdayTenthLessonClassroomFG: gradeData.wednesdayTenthLessonClassroomFG,
            wednesdayTenthLessonSG: gradeData.wednesdayTenthLessonSG,
            wednesdayTenthLessonTeacherSG: gradeData.wednesdayTenthLessonTeacherSG,
            wednesdayTenthLessonClassroomSG: gradeData.wednesdayTenthLessonClassroomSG,

            thursdayFirstLessonFG: gradeData.thursdayFirstLessonFG,
            thursdayFirstLessonTeacherFG: gradeData.thursdayFirstLessonTeacherFG,
            thursdayFirstLessonClassroomFG: gradeData.thursdayFirstLessonClassroomFG,
            thursdayFirstLessonSG: gradeData.thursdayFirstLessonSG,
            thursdayFirstLessonTeacherSG: gradeData.thursdayFirstLessonTeacherSG,
            thursdayFirstLessonClassroomSG: gradeData.thursdayFirstLessonClassroomSG,
            thursdaySecondLessonFG: gradeData.thursdaySecondLessonFG,
            thursdaySecondLessonTeacherFG: gradeData.thursdaySecondLessonTeacherFG,
            thursdaySecondLessonClassroomFG: gradeData.thursdaySecondLessonClassroomFG,
            thursdaySecondLessonSG: gradeData.thursdaySecondLessonSG,
            thursdaySecondLessonTeacherSG: gradeData.thursdaySecondLessonTeacherSG,
            thursdaySecondLessonClassroomSG: gradeData.thursdaySecondLessonClassroomSG,
            thursdayThirdLessonFG: gradeData.thursdayThirdLessonFG,
            thursdayThirdLessonTeacherFG: gradeData.thursdayThirdLessonTeacherFG,
            thursdayThirdLessonClassroomFG: gradeData.thursdayThirdLessonClassroomFG,
            thursdayThirdLessonSG: gradeData.thursdayThirdLessonSG,
            thursdayThirdLessonTeacherSG: gradeData.thursdayThirdLessonTeacherSG,
            thursdayThirdLessonClassroomSG: gradeData.thursdayThirdLessonClassroomSG,
            thursdayFourthLessonFG: gradeData.thursdayFourthLessonFG,
            thursdayFourthLessonTeacherFG: gradeData.thursdayFourthLessonTeacherFG,
            thursdayFourthLessonClassroomFG: gradeData.thursdayFourthLessonClassroomFG,
            thursdayFourthLessonSG: gradeData.thursdayFourthLessonSG,
            thursdayFourthLessonTeacherSG: gradeData.thursdayFourthLessonTeacherSG,
            thursdayFourthLessonClassroomSG: gradeData.thursdayFourthLessonClassroomSG,
            thursdayFifthLessonFG: gradeData.thursdayFifthLessonFG,
            thursdayFifthLessonTeacherFG: gradeData.thursdayFifthLessonTeacherFG,
            thursdayFifthLessonClassroomFG: gradeData.thursdayFifthLessonClassroomFG,
            thursdayFifthLessonSG: gradeData.thursdayFifthLessonSG,
            thursdayFifthLessonTeacherSG: gradeData.thursdayFifthLessonTeacherSG,
            thursdayFifthLessonClassroomSG: gradeData.thursdayFifthLessonClassroomSG,
            thursdaySixthLessonFG: gradeData.thursdaySixthLessonFG,
            thursdaySixthLessonTeacherFG: gradeData.thursdaySixthLessonTeacherFG,
            thursdaySixthLessonClassroomFG: gradeData.thursdaySixthLessonClassroomFG,
            thursdaySixthLessonSG: gradeData.thursdaySixthLessonSG,
            thursdaySixthLessonTeacherSG: gradeData.thursdaySixthLessonTeacherSG,
            thursdaySixthLessonClassroomSG: gradeData.thursdaySixthLessonClassroomSG,
            thursdaySeventhLessonFG: gradeData.thursdaySeventhLessonFG,
            thursdaySeventhLessonTeacherFG: gradeData.thursdaySeventhLessonTeacherFG,
            thursdaySeventhLessonClassroomFG: gradeData.thursdaySeventhLessonClassroomFG,
            thursdaySeventhLessonSG: gradeData.thursdaySeventhLessonSG,
            thursdaySeventhLessonTeacherSG: gradeData.thursdaySeventhLessonTeacherSG,
            thursdaySeventhLessonClassroomSG: gradeData.thursdaySeventhLessonClassroomSG,
            thursdayEighthLessonFG: gradeData.thursdayEighthLessonFG,
            thursdayEighthLessonTeacherFG: gradeData.thursdayEighthLessonTeacherFG,
            thursdayEighthLessonClassroomFG: gradeData.thursdayEighthLessonClassroomFG,
            thursdayEighthLessonSG: gradeData.thursdayEighthLessonSG,
            thursdayEighthLessonTeacherSG: gradeData.thursdayEighthLessonTeacherSG,
            thursdayEighthLessonClassroomSG: gradeData.thursdayEighthLessonClassroomSG,
            thursdayNinthLessonFG: gradeData.thursdayNinthLessonFG,
            thursdayNinthLessonTeacherFG: gradeData.thursdayNinthLessonTeacherFG,
            thursdayNinthLessonClassroomFG: gradeData.thursdayNinthLessonClassroomFG,
            thursdayNinthLessonSG: gradeData.thursdayNinthLessonSG,
            thursdayNinthLessonTeacherSG: gradeData.thursdayNinthLessonTeacherSG,
            thursdayNinthLessonClassroomSG: gradeData.thursdayNinthLessonClassroomSG,
            thursdayTenthLessonFG: gradeData.thursdayTenthLessonFG,
            thursdayTenthLessonTeacherFG: gradeData.thursdayTenthLessonTeacherFG,
            thursdayTenthLessonClassroomFG: gradeData.thursdayTenthLessonClassroomFG,
            thursdayTenthLessonSG: gradeData.thursdayTenthLessonSG,
            thursdayTenthLessonTeacherSG: gradeData.thursdayTenthLessonTeacherSG,
            thursdayTenthLessonClassroomSG: gradeData.thursdayTenthLessonClassroomSG,

            fridayFirstLessonFG: gradeData.fridayFirstLessonFG,
            fridayFirstLessonTeacherFG: gradeData.fridayFirstLessonTeacherFG,
            fridayFirstLessonClassroomFG: gradeData.fridayFirstLessonClassroomFG,
            fridayFirstLessonSG: gradeData.fridayFirstLessonSG,
            fridayFirstLessonTeacherSG: gradeData.fridayFirstLessonTeacherSG,
            fridayFirstLessonClassroomSG: gradeData.fridayFirstLessonClassroomSG,
            fridaySecondLessonFG: gradeData.fridaySecondLessonFG,
            fridaySecondLessonTeacherFG: gradeData.fridaySecondLessonTeacherFG,
            fridaySecondLessonClassroomFG: gradeData.fridaySecondLessonClassroomFG,
            fridaySecondLessonSG: gradeData.fridaySecondLessonSG,
            fridaySecondLessonTeacherSG: gradeData.fridaySecondLessonTeacherSG,
            fridaySecondLessonClassroomSG: gradeData.fridaySecondLessonClassroomSG,
            fridayThirdLessonFG: gradeData.fridayThirdLessonFG,
            fridayThirdLessonTeacherFG: gradeData.fridayThirdLessonTeacherFG,
            fridayThirdLessonClassroomFG: gradeData.fridayThirdLessonClassroomFG,
            fridayThirdLessonSG: gradeData.fridayThirdLessonSG,
            fridayThirdLessonTeacherSG: gradeData.fridayThirdLessonTeacherSG,
            fridayThirdLessonClassroomSG: gradeData.fridayThirdLessonClassroomSG,
            fridayFourthLessonFG: gradeData.fridayFourthLessonFG,
            fridayFourthLessonTeacherFG: gradeData.fridayFourthLessonTeacherFG,
            fridayFourthLessonClassroomFG: gradeData.fridayFourthLessonClassroomFG,
            fridayFourthLessonSG: gradeData.fridayFourthLessonSG,
            fridayFourthLessonTeacherSG: gradeData.fridayFourthLessonTeacherSG,
            fridayFourthLessonClassroomSG: gradeData.fridayFourthLessonClassroomSG,
            fridayFifthLessonFG: gradeData.fridayFifthLessonFG,
            fridayFifthLessonTeacherFG: gradeData.fridayFifthLessonTeacherFG,
            fridayFifthLessonClassroomFG: gradeData.fridayFifthLessonClassroomFG,
            fridayFifthLessonSG: gradeData.fridayFifthLessonSG,
            fridayFifthLessonTeacherSG: gradeData.fridayFifthLessonTeacherSG,
            fridayFifthLessonClassroomSG: gradeData.fridayFifthLessonClassroomSG,
            fridaySixthLessonFG: gradeData.fridaySixthLessonFG,
            fridaySixthLessonTeacherFG: gradeData.fridaySixthLessonTeacherFG,
            fridaySixthLessonClassroomFG: gradeData.fridaySixthLessonClassroomFG,
            fridaySixthLessonSG: gradeData.fridaySixthLessonSG,
            fridaySixthLessonTeacherSG: gradeData.fridaySixthLessonTeacherSG,
            fridaySixthLessonClassroomSG: gradeData.fridaySixthLessonClassroomSG,
            fridaySeventhLessonFG: gradeData.fridaySeventhLessonFG,
            fridaySeventhLessonTeacherFG: gradeData.fridaySeventhLessonTeacherFG,
            fridaySeventhLessonClassroomFG: gradeData.fridaySeventhLessonClassroomFG,
            fridaySeventhLessonSG: gradeData.fridaySeventhLessonSG,
            fridaySeventhLessonTeacherSG: gradeData.fridaySeventhLessonTeacherSG,
            fridaySeventhLessonClassroomSG: gradeData.fridaySeventhLessonClassroomSG,
            fridayEighthLessonFG: gradeData.fridayEighthLessonFG,
            fridayEighthLessonTeacherFG: gradeData.fridayEighthLessonTeacherFG,
            fridayEighthLessonClassroomFG: gradeData.fridayEighthLessonClassroomFG,
            fridayEighthLessonSG: gradeData.fridayEighthLessonSG,
            fridayEighthLessonTeacherSG: gradeData.fridayEighthLessonTeacherSG,
            fridayEighthLessonClassroomSG: gradeData.fridayEighthLessonClassroomSG,
            fridayNinthLessonFG: gradeData.fridayNinthLessonFG,
            fridayNinthLessonTeacherFG: gradeData.fridayNinthLessonTeacherFG,
            fridayNinthLessonClassroomFG: gradeData.fridayNinthLessonClassroomFG,
            fridayNinthLessonSG: gradeData.fridayNinthLessonSG,
            fridayNinthLessonTeacherSG: gradeData.fridayNinthLessonTeacherSG,
            fridayNinthLessonClassroomSG: gradeData.fridayNinthLessonClassroomSG,
            fridayTenthLessonFG: gradeData.fridayTenthLessonFG,
            fridayTenthLessonTeacherFG: gradeData.fridayTenthLessonTeacherFG,
            fridayTenthLessonClassroomFG: gradeData.fridayTenthLessonClassroomFG,
            fridayTenthLessonSG: gradeData.fridayTenthLessonSG,
            fridayTenthLessonTeacherSG: gradeData.fridayTenthLessonTeacherSG,
            fridayTenthLessonClassroomSG: gradeData.fridayTenthLessonClassroomSG,

            saturdayFirstLessonFG: gradeData.saturdayFirstLessonFG,
            saturdayFirstLessonTeacherFG: gradeData.saturdayFirstLessonTeacherFG,
            saturdayFirstLessonClassroomFG: gradeData.saturdayFirstLessonClassroomFG,
            saturdayFirstLessonSG: gradeData.saturdayFirstLessonSG,
            saturdayFirstLessonTeacherSG: gradeData.saturdayFirstLessonTeacherSG,
            saturdayFirstLessonClassroomSG: gradeData.saturdayFirstLessonClassroomSG,
            saturdaySecondLessonFG: gradeData.saturdaySecondLessonFG,
            saturdaySecondLessonTeacherFG: gradeData.saturdaySecondLessonTeacherFG,
            saturdaySecondLessonClassroomFG: gradeData.saturdaySecondLessonClassroomFG,
            saturdaySecondLessonSG: gradeData.saturdaySecondLessonSG,
            saturdaySecondLessonTeacherSG: gradeData.saturdaySecondLessonTeacherSG,
            saturdaySecondLessonClassroomSG: gradeData.saturdaySecondLessonClassroomSG,
            saturdayThirdLessonFG: gradeData.saturdayThirdLessonFG,
            saturdayThirdLessonTeacherFG: gradeData.saturdayThirdLessonTeacherFG,
            saturdayThirdLessonClassroomFG: gradeData.saturdayThirdLessonClassroomFG,
            saturdayThirdLessonSG: gradeData.saturdayThirdLessonSG,
            saturdayThirdLessonTeacherSG: gradeData.saturdayThirdLessonTeacherSG,
            saturdayThirdLessonClassroomSG: gradeData.saturdayThirdLessonClassroomSG,
            saturdayFourthLessonFG: gradeData.saturdayFourthLessonFG,
            saturdayFourthLessonTeacherFG: gradeData.saturdayFourthLessonTeacherFG,
            saturdayFourthLessonClassroomFG: gradeData.saturdayFourthLessonClassroomFG,
            saturdayFourthLessonSG: gradeData.saturdayFourthLessonSG,
            saturdayFourthLessonTeacherSG: gradeData.saturdayFourthLessonTeacherSG,
            saturdayFourthLessonClassroomSG: gradeData.saturdayFourthLessonClassroomSG,
            saturdayFifthLessonFG: gradeData.saturdayFifthLessonFG,
            saturdayFifthLessonTeacherFG: gradeData.saturdayFifthLessonTeacherFG,
            saturdayFifthLessonClassroomFG: gradeData.saturdayFifthLessonClassroomFG,
            saturdayFifthLessonSG: gradeData.saturdayFifthLessonSG,
            saturdayFifthLessonTeacherSG: gradeData.saturdayFifthLessonTeacherSG,
            saturdayFifthLessonClassroomSG: gradeData.saturdayFifthLessonClassroomSG,
            saturdaySixthLessonFG: gradeData.saturdaySixthLessonFG,
            saturdaySixthLessonTeacherFG: gradeData.saturdaySixthLessonTeacherFG,
            saturdaySixthLessonClassroomFG: gradeData.saturdaySixthLessonClassroomFG,
            saturdaySixthLessonSG: gradeData.saturdaySixthLessonSG,
            saturdaySixthLessonTeacherSG: gradeData.saturdaySixthLessonTeacherSG,
            saturdaySixthLessonClassroomSG: gradeData.saturdaySixthLessonClassroomSG,
            saturdaySeventhLessonFG: gradeData.saturdaySeventhLessonFG,
            saturdaySeventhLessonTeacherFG: gradeData.saturdaySeventhLessonTeacherFG,
            saturdaySeventhLessonClassroomFG: gradeData.saturdaySeventhLessonClassroomFG,
            saturdaySeventhLessonSG: gradeData.saturdaySeventhLessonSG,
            saturdaySeventhLessonTeacherSG: gradeData.saturdaySeventhLessonTeacherSG,
            saturdaySeventhLessonClassroomSG: gradeData.saturdaySeventhLessonClassroomSG,
            saturdayEighthLessonFG: gradeData.saturdayEighthLessonFG,
            saturdayEighthLessonTeacherFG: gradeData.saturdayEighthLessonTeacherFG,
            saturdayEighthLessonClassroomFG: gradeData.saturdayEighthLessonClassroomFG,
            saturdayEighthLessonSG: gradeData.saturdayEighthLessonSG,
            saturdayEighthLessonTeacherSG: gradeData.saturdayEighthLessonTeacherSG,
            saturdayEighthLessonClassroomSG: gradeData.saturdayEighthLessonClassroomSG,
            saturdayNinthLessonFG: gradeData.saturdayNinthLessonFG,
            saturdayNinthLessonTeacherFG: gradeData.saturdayNinthLessonTeacherFG,
            saturdayNinthLessonClassroomFG: gradeData.saturdayNinthLessonClassroomFG,
            saturdayNinthLessonSG: gradeData.saturdayNinthLessonSG,
            saturdayNinthLessonTeacherSG: gradeData.saturdayNinthLessonTeacherSG,
            saturdayNinthLessonClassroomSG: gradeData.saturdayNinthLessonClassroomSG,
            saturdayTenthLessonFG: gradeData.saturdayTenthLessonFG,
            saturdayTenthLessonTeacherFG: gradeData.saturdayTenthLessonTeacherFG,
            saturdayTenthLessonClassroomFG: gradeData.saturdayTenthLessonClassroomFG,
            saturdayTenthLessonSG: gradeData.saturdayTenthLessonSG,
            saturdayTenthLessonTeacherSG: gradeData.saturdayTenthLessonTeacherSG,
            saturdayTenthLessonClassroomSG: gradeData.saturdayTenthLessonClassroomSG,
          };
          this.form.setValue({
            gradeNumber: this.grade.gradeNumber,
            gradeLiter: this.grade.gradeLiter,

            mondayFirstLessonFG: this.grade.mondayFirstLessonFG,
            mondayFirstLessonTeacherFG: this.grade.mondayFirstLessonTeacherFG,
            mondayFirstLessonClassroomFG: this.grade.mondayFirstLessonClassroomFG,
            mondayFirstLessonSG: this.grade.mondayFirstLessonSG,
            mondayFirstLessonTeacherSG: this.grade.mondayFirstLessonTeacherSG,
            mondayFirstLessonClassroomSG: this.grade.mondayFirstLessonClassroomSG,
            mondaySecondLessonFG: this.grade.mondaySecondLessonFG,
            mondaySecondLessonTeacherFG: this.grade.mondaySecondLessonTeacherFG,
            mondaySecondLessonClassroomFG: this.grade.mondaySecondLessonClassroomFG,
            mondaySecondLessonSG: this.grade.mondaySecondLessonSG,
            mondaySecondLessonTeacherSG: this.grade.mondaySecondLessonTeacherSG,
            mondaySecondLessonClassroomSG: this.grade.mondaySecondLessonClassroomSG,
            mondayThirdLessonFG: this.grade.mondayThirdLessonFG,
            mondayThirdLessonTeacherFG: this.grade.mondayThirdLessonTeacherFG,
            mondayThirdLessonClassroomFG: this.grade.mondayThirdLessonClassroomFG,
            mondayThirdLessonSG: this.grade.mondayThirdLessonSG,
            mondayThirdLessonTeacherSG: this.grade.mondayThirdLessonTeacherSG,
            mondayThirdLessonClassroomSG: this.grade.mondayThirdLessonClassroomSG,
            mondayFourthLessonFG: this.grade.mondayFourthLessonFG,
            mondayFourthLessonTeacherFG: this.grade.mondayFourthLessonTeacherFG,
            mondayFourthLessonClassroomFG: this.grade.mondayFourthLessonClassroomFG,
            mondayFourthLessonSG: this.grade.mondayFourthLessonSG,
            mondayFourthLessonTeacherSG: this.grade.mondayFourthLessonTeacherSG,
            mondayFourthLessonClassroomSG: this.grade.mondayFourthLessonClassroomSG,
            mondayFifthLessonFG: this.grade.mondayFifthLessonFG,
            mondayFifthLessonTeacherFG: this.grade.mondayFifthLessonTeacherFG,
            mondayFifthLessonClassroomFG: this.grade.mondayFifthLessonClassroomFG,
            mondayFifthLessonSG: this.grade.mondayFifthLessonSG,
            mondayFifthLessonTeacherSG: this.grade.mondayFifthLessonTeacherSG,
            mondayFifthLessonClassroomSG: this.grade.mondayFifthLessonClassroomSG,
            mondaySixthLessonFG: this.grade.mondaySixthLessonFG,
            mondaySixthLessonTeacherFG: this.grade.mondaySixthLessonTeacherFG,
            mondaySixthLessonClassroomFG: this.grade.mondaySixthLessonClassroomFG,
            mondaySixthLessonSG: this.grade.mondaySixthLessonSG,
            mondaySixthLessonTeacherSG: this.grade.mondaySixthLessonTeacherSG,
            mondaySixthLessonClassroomSG: this.grade.mondaySixthLessonClassroomSG,
            mondaySeventhLessonFG: this.grade.mondaySeventhLessonFG,
            mondaySeventhLessonTeacherFG: this.grade.mondaySeventhLessonTeacherFG,
            mondaySeventhLessonClassroomFG: this.grade.mondaySeventhLessonClassroomFG,
            mondaySeventhLessonSG: this.grade.mondaySeventhLessonSG,
            mondaySeventhLessonTeacherSG: this.grade.mondaySeventhLessonTeacherSG,
            mondaySeventhLessonClassroomSG: this.grade.mondaySeventhLessonClassroomSG,
            mondayEighthLessonFG: this.grade.mondayEighthLessonFG,
            mondayEighthLessonTeacherFG: this.grade.mondayEighthLessonTeacherFG,
            mondayEighthLessonClassroomFG: this.grade.mondayEighthLessonClassroomFG,
            mondayEighthLessonSG: this.grade.mondayEighthLessonSG,
            mondayEighthLessonTeacherSG: this.grade.mondayEighthLessonTeacherSG,
            mondayEighthLessonClassroomSG: this.grade.mondayEighthLessonClassroomSG,
            mondayNinthLessonFG: this.grade.mondayNinthLessonFG,
            mondayNinthLessonTeacherFG: this.grade.mondayNinthLessonTeacherFG,
            mondayNinthLessonClassroomFG: this.grade.mondayNinthLessonClassroomFG,
            mondayNinthLessonSG: this.grade.mondayNinthLessonSG,
            mondayNinthLessonTeacherSG: this.grade.mondayNinthLessonTeacherSG,
            mondayNinthLessonClassroomSG: this.grade.mondayNinthLessonClassroomSG,
            mondayTenthLessonFG: this.grade.mondayTenthLessonFG,
            mondayTenthLessonTeacherFG: this.grade.mondayTenthLessonTeacherFG,
            mondayTenthLessonClassroomFG: this.grade.mondayTenthLessonClassroomFG,
            mondayTenthLessonSG: this.grade.mondayTenthLessonSG,
            mondayTenthLessonTeacherSG: this.grade.mondayTenthLessonTeacherSG,
            mondayTenthLessonClassroomSG: this.grade.mondayTenthLessonClassroomSG,


            tuesdayFirstLessonFG: this.grade.tuesdayFirstLessonFG,
            tuesdayFirstLessonTeacherFG: this.grade.tuesdayFirstLessonTeacherFG,
            tuesdayFirstLessonClassroomFG: this.grade.tuesdayFirstLessonClassroomFG,
            tuesdayFirstLessonSG: this.grade.tuesdayFirstLessonSG,
            tuesdayFirstLessonTeacherSG: this.grade.tuesdayFirstLessonTeacherSG,
            tuesdayFirstLessonClassroomSG: this.grade.tuesdayFirstLessonClassroomSG,
            tuesdaySecondLessonFG: this.grade.tuesdaySecondLessonFG,
            tuesdaySecondLessonTeacherFG: this.grade.tuesdaySecondLessonTeacherFG,
            tuesdaySecondLessonClassroomFG: this.grade.tuesdaySecondLessonClassroomFG,
            tuesdaySecondLessonSG: this.grade.tuesdaySecondLessonSG,
            tuesdaySecondLessonTeacherSG: this.grade.tuesdaySecondLessonTeacherSG,
            tuesdaySecondLessonClassroomSG: this.grade.tuesdaySecondLessonClassroomSG,
            tuesdayThirdLessonFG: this.grade.tuesdayThirdLessonFG,
            tuesdayThirdLessonTeacherFG: this.grade.tuesdayThirdLessonTeacherFG,
            tuesdayThirdLessonClassroomFG: this.grade.tuesdayThirdLessonClassroomFG,
            tuesdayThirdLessonSG: this.grade.tuesdayThirdLessonSG,
            tuesdayThirdLessonTeacherSG: this.grade.tuesdayThirdLessonTeacherSG,
            tuesdayThirdLessonClassroomSG: this.grade.tuesdayThirdLessonClassroomSG,
            tuesdayFourthLessonFG: this.grade.tuesdayFourthLessonFG,
            tuesdayFourthLessonTeacherFG: this.grade.tuesdayFourthLessonTeacherFG,
            tuesdayFourthLessonClassroomFG: this.grade.tuesdayFourthLessonClassroomFG,
            tuesdayFourthLessonSG: this.grade.tuesdayFourthLessonSG,
            tuesdayFourthLessonTeacherSG: this.grade.tuesdayFourthLessonTeacherSG,
            tuesdayFourthLessonClassroomSG: this.grade.tuesdayFourthLessonClassroomSG,
            tuesdayFifthLessonFG: this.grade.tuesdayFifthLessonFG,
            tuesdayFifthLessonTeacherFG: this.grade.tuesdayFifthLessonTeacherFG,
            tuesdayFifthLessonClassroomFG: this.grade.tuesdayFifthLessonClassroomFG,
            tuesdayFifthLessonSG: this.grade.tuesdayFifthLessonSG,
            tuesdayFifthLessonTeacherSG: this.grade.tuesdayFifthLessonTeacherSG,
            tuesdayFifthLessonClassroomSG: this.grade.tuesdayFifthLessonClassroomSG,
            tuesdaySixthLessonFG: this.grade.tuesdaySixthLessonFG,
            tuesdaySixthLessonTeacherFG: this.grade.tuesdaySixthLessonTeacherFG,
            tuesdaySixthLessonClassroomFG: this.grade.tuesdaySixthLessonClassroomFG,
            tuesdaySixthLessonSG: this.grade.tuesdaySixthLessonSG,
            tuesdaySixthLessonTeacherSG: this.grade.tuesdaySixthLessonTeacherSG,
            tuesdaySixthLessonClassroomSG: this.grade.tuesdaySixthLessonClassroomSG,
            tuesdaySeventhLessonFG: this.grade.tuesdaySeventhLessonFG,
            tuesdaySeventhLessonTeacherFG: this.grade.tuesdaySeventhLessonTeacherFG,
            tuesdaySeventhLessonClassroomFG: this.grade.tuesdaySeventhLessonClassroomFG,
            tuesdaySeventhLessonSG: this.grade.tuesdaySeventhLessonSG,
            tuesdaySeventhLessonTeacherSG: this.grade.tuesdaySeventhLessonTeacherSG,
            tuesdaySeventhLessonClassroomSG: this.grade.tuesdaySeventhLessonClassroomSG,
            tuesdayEighthLessonFG: this.grade.tuesdayEighthLessonFG,
            tuesdayEighthLessonTeacherFG: this.grade.tuesdayEighthLessonTeacherFG,
            tuesdayEighthLessonClassroomFG: this.grade.tuesdayEighthLessonClassroomFG,
            tuesdayEighthLessonSG: this.grade.tuesdayEighthLessonSG,
            tuesdayEighthLessonTeacherSG: this.grade.tuesdayEighthLessonTeacherSG,
            tuesdayEighthLessonClassroomSG: this.grade.tuesdayEighthLessonClassroomSG,
            tuesdayNinthLessonFG: this.grade.tuesdayNinthLessonFG,
            tuesdayNinthLessonTeacherFG: this.grade.tuesdayNinthLessonTeacherFG,
            tuesdayNinthLessonClassroomFG: this.grade.tuesdayNinthLessonClassroomFG,
            tuesdayNinthLessonSG: this.grade.tuesdayNinthLessonSG,
            tuesdayNinthLessonTeacherSG: this.grade.tuesdayNinthLessonTeacherSG,
            tuesdayNinthLessonClassroomSG: this.grade.tuesdayNinthLessonClassroomSG,
            tuesdayTenthLessonFG: this.grade.tuesdayTenthLessonFG,
            tuesdayTenthLessonTeacherFG: this.grade.tuesdayTenthLessonTeacherFG,
            tuesdayTenthLessonClassroomFG: this.grade.tuesdayTenthLessonClassroomFG,
            tuesdayTenthLessonSG: this.grade.tuesdayTenthLessonSG,
            tuesdayTenthLessonTeacherSG: this.grade.tuesdayTenthLessonTeacherSG,
            tuesdayTenthLessonClassroomSG: this.grade.tuesdayTenthLessonClassroomSG,

            wednesdayFirstLessonFG: this.grade.wednesdayFirstLessonFG,
            wednesdayFirstLessonTeacherFG: this.grade.wednesdayFirstLessonTeacherFG,
            wednesdayFirstLessonClassroomFG: this.grade.wednesdayFirstLessonClassroomFG,
            wednesdayFirstLessonSG: this.grade.wednesdayFirstLessonSG,
            wednesdayFirstLessonTeacherSG: this.grade.wednesdayFirstLessonTeacherSG,
            wednesdayFirstLessonClassroomSG: this.grade.wednesdayFirstLessonClassroomSG,
            wednesdaySecondLessonFG: this.grade.wednesdaySecondLessonFG,
            wednesdaySecondLessonTeacherFG: this.grade.wednesdaySecondLessonTeacherFG,
            wednesdaySecondLessonClassroomFG: this.grade.wednesdaySecondLessonClassroomFG,
            wednesdaySecondLessonSG: this.grade.wednesdaySecondLessonSG,
            wednesdaySecondLessonTeacherSG: this.grade.wednesdaySecondLessonTeacherSG,
            wednesdaySecondLessonClassroomSG: this.grade.wednesdaySecondLessonClassroomSG,
            wednesdayThirdLessonFG: this.grade.wednesdayThirdLessonFG,
            wednesdayThirdLessonTeacherFG: this.grade.wednesdayThirdLessonTeacherFG,
            wednesdayThirdLessonClassroomFG: this.grade.wednesdayThirdLessonClassroomFG,
            wednesdayThirdLessonSG: this.grade.wednesdayThirdLessonSG,
            wednesdayThirdLessonTeacherSG: this.grade.wednesdayThirdLessonTeacherSG,
            wednesdayThirdLessonClassroomSG: this.grade.wednesdayThirdLessonClassroomSG,
            wednesdayFourthLessonFG: this.grade.wednesdayFourthLessonFG,
            wednesdayFourthLessonTeacherFG: this.grade.wednesdayFourthLessonTeacherFG,
            wednesdayFourthLessonClassroomFG: this.grade.wednesdayFourthLessonClassroomFG,
            wednesdayFourthLessonSG: this.grade.wednesdayFourthLessonSG,
            wednesdayFourthLessonTeacherSG: this.grade.wednesdayFourthLessonTeacherSG,
            wednesdayFourthLessonClassroomSG: this.grade.wednesdayFourthLessonClassroomSG,
            wednesdayFifthLessonFG: this.grade.wednesdayFifthLessonFG,
            wednesdayFifthLessonTeacherFG: this.grade.wednesdayFifthLessonTeacherFG,
            wednesdayFifthLessonClassroomFG: this.grade.wednesdayFifthLessonClassroomFG,
            wednesdayFifthLessonSG: this.grade.wednesdayFifthLessonSG,
            wednesdayFifthLessonTeacherSG: this.grade.wednesdayFifthLessonTeacherSG,
            wednesdayFifthLessonClassroomSG: this.grade.wednesdayFifthLessonClassroomSG,
            wednesdaySixthLessonFG: this.grade.wednesdaySixthLessonFG,
            wednesdaySixthLessonTeacherFG: this.grade.wednesdaySixthLessonTeacherFG,
            wednesdaySixthLessonClassroomFG: this.grade.wednesdaySixthLessonClassroomFG,
            wednesdaySixthLessonSG: this.grade.wednesdaySixthLessonSG,
            wednesdaySixthLessonTeacherSG: this.grade.wednesdaySixthLessonTeacherSG,
            wednesdaySixthLessonClassroomSG: this.grade.wednesdaySixthLessonClassroomSG,
            wednesdaySeventhLessonFG: this.grade.wednesdaySeventhLessonFG,
            wednesdaySeventhLessonTeacherFG: this.grade.wednesdaySeventhLessonTeacherFG,
            wednesdaySeventhLessonClassroomFG: this.grade.wednesdaySeventhLessonClassroomFG,
            wednesdaySeventhLessonSG: this.grade.wednesdaySeventhLessonSG,
            wednesdaySeventhLessonTeacherSG: this.grade.wednesdaySeventhLessonTeacherSG,
            wednesdaySeventhLessonClassroomSG: this.grade.wednesdaySeventhLessonClassroomSG,
            wednesdayEighthLessonFG: this.grade.wednesdayEighthLessonFG,
            wednesdayEighthLessonTeacherFG: this.grade.wednesdayEighthLessonTeacherFG,
            wednesdayEighthLessonClassroomFG: this.grade.wednesdayEighthLessonClassroomFG,
            wednesdayEighthLessonSG: this.grade.wednesdayEighthLessonSG,
            wednesdayEighthLessonTeacherSG: this.grade.wednesdayEighthLessonTeacherSG,
            wednesdayEighthLessonClassroomSG: this.grade.wednesdayEighthLessonClassroomSG,
            wednesdayNinthLessonFG: this.grade.wednesdayNinthLessonFG,
            wednesdayNinthLessonTeacherFG: this.grade.wednesdayNinthLessonTeacherFG,
            wednesdayNinthLessonClassroomFG: this.grade.wednesdayNinthLessonClassroomFG,
            wednesdayNinthLessonSG: this.grade.wednesdayNinthLessonSG,
            wednesdayNinthLessonTeacherSG: this.grade.wednesdayNinthLessonTeacherSG,
            wednesdayNinthLessonClassroomSG: this.grade.wednesdayNinthLessonClassroomSG,
            wednesdayTenthLessonFG: this.grade.wednesdayTenthLessonFG,
            wednesdayTenthLessonTeacherFG: this.grade.wednesdayTenthLessonTeacherFG,
            wednesdayTenthLessonClassroomFG: this.grade.wednesdayTenthLessonClassroomFG,
            wednesdayTenthLessonSG: this.grade.wednesdayTenthLessonSG,
            wednesdayTenthLessonTeacherSG: this.grade.wednesdayTenthLessonTeacherSG,
            wednesdayTenthLessonClassroomSG: this.grade.wednesdayTenthLessonClassroomSG,

            thursdayFirstLessonFG: this.grade.thursdayFirstLessonFG,
            thursdayFirstLessonTeacherFG: this.grade.thursdayFirstLessonTeacherFG,
            thursdayFirstLessonClassroomFG: this.grade.thursdayFirstLessonClassroomFG,
            thursdayFirstLessonSG: this.grade.thursdayFirstLessonSG,
            thursdayFirstLessonTeacherSG: this.grade.thursdayFirstLessonTeacherSG,
            thursdayFirstLessonClassroomSG: this.grade.thursdayFirstLessonClassroomSG,
            thursdaySecondLessonFG: this.grade.thursdaySecondLessonFG,
            thursdaySecondLessonTeacherFG: this.grade.thursdaySecondLessonTeacherFG,
            thursdaySecondLessonClassroomFG: this.grade.thursdaySecondLessonClassroomFG,
            thursdaySecondLessonSG: this.grade.thursdaySecondLessonSG,
            thursdaySecondLessonTeacherSG: this.grade.thursdaySecondLessonTeacherSG,
            thursdaySecondLessonClassroomSG: this.grade.thursdaySecondLessonClassroomSG,
            thursdayThirdLessonFG: this.grade.thursdayThirdLessonFG,
            thursdayThirdLessonTeacherFG: this.grade.thursdayThirdLessonTeacherFG,
            thursdayThirdLessonClassroomFG: this.grade.thursdayThirdLessonClassroomFG,
            thursdayThirdLessonSG: this.grade.thursdayThirdLessonSG,
            thursdayThirdLessonTeacherSG: this.grade.thursdayThirdLessonTeacherSG,
            thursdayThirdLessonClassroomSG: this.grade.thursdayThirdLessonClassroomSG,
            thursdayFourthLessonFG: this.grade.thursdayFourthLessonFG,
            thursdayFourthLessonTeacherFG: this.grade.thursdayFourthLessonTeacherFG,
            thursdayFourthLessonClassroomFG: this.grade.thursdayFourthLessonClassroomFG,
            thursdayFourthLessonSG: this.grade.thursdayFourthLessonSG,
            thursdayFourthLessonTeacherSG: this.grade.thursdayFourthLessonTeacherSG,
            thursdayFourthLessonClassroomSG: this.grade.thursdayFourthLessonClassroomSG,
            thursdayFifthLessonFG: this.grade.thursdayFifthLessonFG,
            thursdayFifthLessonTeacherFG: this.grade.thursdayFifthLessonTeacherFG,
            thursdayFifthLessonClassroomFG: this.grade.thursdayFifthLessonClassroomFG,
            thursdayFifthLessonSG: this.grade.thursdayFifthLessonSG,
            thursdayFifthLessonTeacherSG: this.grade.thursdayFifthLessonTeacherSG,
            thursdayFifthLessonClassroomSG: this.grade.thursdayFifthLessonClassroomSG,
            thursdaySixthLessonFG: this.grade.thursdaySixthLessonFG,
            thursdaySixthLessonTeacherFG: this.grade.thursdaySixthLessonTeacherFG,
            thursdaySixthLessonClassroomFG: this.grade.thursdaySixthLessonClassroomFG,
            thursdaySixthLessonSG: this.grade.thursdaySixthLessonSG,
            thursdaySixthLessonTeacherSG: this.grade.thursdaySixthLessonTeacherSG,
            thursdaySixthLessonClassroomSG: this.grade.thursdaySixthLessonClassroomSG,
            thursdaySeventhLessonFG: this.grade.thursdaySeventhLessonFG,
            thursdaySeventhLessonTeacherFG: this.grade.thursdaySeventhLessonTeacherFG,
            thursdaySeventhLessonClassroomFG: this.grade.thursdaySeventhLessonClassroomFG,
            thursdaySeventhLessonSG: this.grade.thursdaySeventhLessonSG,
            thursdaySeventhLessonTeacherSG: this.grade.thursdaySeventhLessonTeacherSG,
            thursdaySeventhLessonClassroomSG: this.grade.thursdaySeventhLessonClassroomSG,
            thursdayEighthLessonFG: this.grade.thursdayEighthLessonFG,
            thursdayEighthLessonTeacherFG: this.grade.thursdayEighthLessonTeacherFG,
            thursdayEighthLessonClassroomFG: this.grade.thursdayEighthLessonClassroomFG,
            thursdayEighthLessonSG: this.grade.thursdayEighthLessonSG,
            thursdayEighthLessonTeacherSG: this.grade.thursdayEighthLessonTeacherSG,
            thursdayEighthLessonClassroomSG: this.grade.thursdayEighthLessonClassroomSG,
            thursdayNinthLessonFG: this.grade.thursdayNinthLessonFG,
            thursdayNinthLessonTeacherFG: this.grade.thursdayNinthLessonTeacherFG,
            thursdayNinthLessonClassroomFG: this.grade.thursdayNinthLessonClassroomFG,
            thursdayNinthLessonSG: this.grade.thursdayNinthLessonSG,
            thursdayNinthLessonTeacherSG: this.grade.thursdayNinthLessonTeacherSG,
            thursdayNinthLessonClassroomSG: this.grade.thursdayNinthLessonClassroomSG,
            thursdayTenthLessonFG: this.grade.thursdayTenthLessonFG,
            thursdayTenthLessonTeacherFG: this.grade.thursdayTenthLessonTeacherFG,
            thursdayTenthLessonClassroomFG: this.grade.thursdayTenthLessonClassroomFG,
            thursdayTenthLessonSG: this.grade.thursdayTenthLessonSG,
            thursdayTenthLessonTeacherSG: this.grade.thursdayTenthLessonTeacherSG,
            thursdayTenthLessonClassroomSG: this.grade.thursdayTenthLessonClassroomSG,

            fridayFirstLessonFG: this.grade.fridayFirstLessonFG,
            fridayFirstLessonTeacherFG: this.grade.fridayFirstLessonTeacherFG,
            fridayFirstLessonClassroomFG: this.grade.fridayFirstLessonClassroomFG,
            fridayFirstLessonSG: this.grade.fridayFirstLessonSG,
            fridayFirstLessonTeacherSG: this.grade.fridayFirstLessonTeacherSG,
            fridayFirstLessonClassroomSG: this.grade.fridayFirstLessonClassroomSG,
            fridaySecondLessonFG: this.grade.fridaySecondLessonFG,
            fridaySecondLessonTeacherFG: this.grade.fridaySecondLessonTeacherFG,
            fridaySecondLessonClassroomFG: this.grade.fridaySecondLessonClassroomFG,
            fridaySecondLessonSG: this.grade.fridaySecondLessonSG,
            fridaySecondLessonTeacherSG: this.grade.fridaySecondLessonTeacherSG,
            fridaySecondLessonClassroomSG: this.grade.fridaySecondLessonClassroomSG,
            fridayThirdLessonFG: this.grade.fridayThirdLessonFG,
            fridayThirdLessonTeacherFG: this.grade.fridayThirdLessonTeacherFG,
            fridayThirdLessonClassroomFG: this.grade.fridayThirdLessonClassroomFG,
            fridayThirdLessonSG: this.grade.fridayThirdLessonSG,
            fridayThirdLessonTeacherSG: this.grade.fridayThirdLessonTeacherSG,
            fridayThirdLessonClassroomSG: this.grade.fridayThirdLessonClassroomSG,
            fridayFourthLessonFG: this.grade.fridayFourthLessonFG,
            fridayFourthLessonTeacherFG: this.grade.fridayFourthLessonTeacherFG,
            fridayFourthLessonClassroomFG: this.grade.fridayFourthLessonClassroomFG,
            fridayFourthLessonSG: this.grade.fridayFourthLessonSG,
            fridayFourthLessonTeacherSG: this.grade.fridayFourthLessonTeacherSG,
            fridayFourthLessonClassroomSG: this.grade.fridayFourthLessonClassroomSG,
            fridayFifthLessonFG: this.grade.fridayFifthLessonFG,
            fridayFifthLessonTeacherFG: this.grade.fridayFifthLessonTeacherFG,
            fridayFifthLessonClassroomFG: this.grade.fridayFifthLessonClassroomFG,
            fridayFifthLessonSG: this.grade.fridayFifthLessonSG,
            fridayFifthLessonTeacherSG: this.grade.fridayFifthLessonTeacherSG,
            fridayFifthLessonClassroomSG: this.grade.fridayFifthLessonClassroomSG,
            fridaySixthLessonFG: this.grade.fridaySixthLessonFG,
            fridaySixthLessonTeacherFG: this.grade.fridaySixthLessonTeacherFG,
            fridaySixthLessonClassroomFG: this.grade.fridaySixthLessonClassroomFG,
            fridaySixthLessonSG: this.grade.fridaySixthLessonSG,
            fridaySixthLessonTeacherSG: this.grade.fridaySixthLessonTeacherSG,
            fridaySixthLessonClassroomSG: this.grade.fridaySixthLessonClassroomSG,
            fridaySeventhLessonFG: this.grade.fridaySeventhLessonFG,
            fridaySeventhLessonTeacherFG: this.grade.fridaySeventhLessonTeacherFG,
            fridaySeventhLessonClassroomFG: this.grade.fridaySeventhLessonClassroomFG,
            fridaySeventhLessonSG: this.grade.fridaySeventhLessonSG,
            fridaySeventhLessonTeacherSG: this.grade.fridaySeventhLessonTeacherSG,
            fridaySeventhLessonClassroomSG: this.grade.fridaySeventhLessonClassroomSG,
            fridayEighthLessonFG: this.grade.fridayEighthLessonFG,
            fridayEighthLessonTeacherFG: this.grade.fridayEighthLessonTeacherFG,
            fridayEighthLessonClassroomFG: this.grade.fridayEighthLessonClassroomFG,
            fridayEighthLessonSG: this.grade.fridayEighthLessonSG,
            fridayEighthLessonTeacherSG: this.grade.fridayEighthLessonTeacherSG,
            fridayEighthLessonClassroomSG: this.grade.fridayEighthLessonClassroomSG,
            fridayNinthLessonFG: this.grade.fridayNinthLessonFG,
            fridayNinthLessonTeacherFG: this.grade.fridayNinthLessonTeacherFG,
            fridayNinthLessonClassroomFG: this.grade.fridayNinthLessonClassroomFG,
            fridayNinthLessonSG: this.grade.fridayNinthLessonSG,
            fridayNinthLessonTeacherSG: this.grade.fridayNinthLessonTeacherSG,
            fridayNinthLessonClassroomSG: this.grade.fridayNinthLessonClassroomSG,
            fridayTenthLessonFG: this.grade.fridayTenthLessonFG,
            fridayTenthLessonTeacherFG: this.grade.fridayTenthLessonTeacherFG,
            fridayTenthLessonClassroomFG: this.grade.fridayTenthLessonClassroomFG,
            fridayTenthLessonSG: this.grade.fridayTenthLessonSG,
            fridayTenthLessonTeacherSG: this.grade.fridayTenthLessonTeacherSG,
            fridayTenthLessonClassroomSG: this.grade.fridayTenthLessonClassroomSG,

            saturdayFirstLessonFG: this.grade.saturdayFirstLessonFG,
            saturdayFirstLessonTeacherFG: this.grade.saturdayFirstLessonTeacherFG,
            saturdayFirstLessonClassroomFG: this.grade.saturdayFirstLessonClassroomFG,
            saturdayFirstLessonSG: this.grade.saturdayFirstLessonSG,
            saturdayFirstLessonTeacherSG: this.grade.saturdayFirstLessonTeacherSG,
            saturdayFirstLessonClassroomSG: this.grade.saturdayFirstLessonClassroomSG,
            saturdaySecondLessonFG: this.grade.saturdaySecondLessonFG,
            saturdaySecondLessonTeacherFG: this.grade.saturdaySecondLessonTeacherFG,
            saturdaySecondLessonClassroomFG: this.grade.saturdaySecondLessonClassroomFG,
            saturdaySecondLessonSG: this.grade.saturdaySecondLessonSG,
            saturdaySecondLessonTeacherSG: this.grade.saturdaySecondLessonTeacherSG,
            saturdaySecondLessonClassroomSG: this.grade.saturdaySecondLessonClassroomSG,
            saturdayThirdLessonFG: this.grade.saturdayThirdLessonFG,
            saturdayThirdLessonTeacherFG: this.grade.saturdayThirdLessonTeacherFG,
            saturdayThirdLessonClassroomFG: this.grade.saturdayThirdLessonClassroomFG,
            saturdayThirdLessonSG: this.grade.saturdayThirdLessonSG,
            saturdayThirdLessonTeacherSG: this.grade.saturdayThirdLessonTeacherSG,
            saturdayThirdLessonClassroomSG: this.grade.saturdayThirdLessonClassroomSG,
            saturdayFourthLessonFG: this.grade.saturdayFourthLessonFG,
            saturdayFourthLessonTeacherFG: this.grade.saturdayFourthLessonTeacherFG,
            saturdayFourthLessonClassroomFG: this.grade.saturdayFourthLessonClassroomFG,
            saturdayFourthLessonSG: this.grade.saturdayFourthLessonSG,
            saturdayFourthLessonTeacherSG: this.grade.saturdayFourthLessonTeacherSG,
            saturdayFourthLessonClassroomSG: this.grade.saturdayFourthLessonClassroomSG,
            saturdayFifthLessonFG: this.grade.saturdayFifthLessonFG,
            saturdayFifthLessonTeacherFG: this.grade.saturdayFifthLessonTeacherFG,
            saturdayFifthLessonClassroomFG: this.grade.saturdayFifthLessonClassroomFG,
            saturdayFifthLessonSG: this.grade.saturdayFifthLessonSG,
            saturdayFifthLessonTeacherSG: this.grade.saturdayFifthLessonTeacherSG,
            saturdayFifthLessonClassroomSG: this.grade.saturdayFifthLessonClassroomSG,
            saturdaySixthLessonFG: this.grade.saturdaySixthLessonFG,
            saturdaySixthLessonTeacherFG: this.grade.saturdaySixthLessonTeacherFG,
            saturdaySixthLessonClassroomFG: this.grade.saturdaySixthLessonClassroomFG,
            saturdaySixthLessonSG: this.grade.saturdaySixthLessonSG,
            saturdaySixthLessonTeacherSG: this.grade.saturdaySixthLessonTeacherSG,
            saturdaySixthLessonClassroomSG: this.grade.saturdaySixthLessonClassroomSG,
            saturdaySeventhLessonFG: this.grade.saturdaySeventhLessonFG,
            saturdaySeventhLessonTeacherFG: this.grade.saturdaySeventhLessonTeacherFG,
            saturdaySeventhLessonClassroomFG: this.grade.saturdaySeventhLessonClassroomFG,
            saturdaySeventhLessonSG: this.grade.saturdaySeventhLessonSG,
            saturdaySeventhLessonTeacherSG: this.grade.saturdaySeventhLessonTeacherSG,
            saturdaySeventhLessonClassroomSG: this.grade.saturdaySeventhLessonClassroomSG,
            saturdayEighthLessonFG: this.grade.saturdayEighthLessonFG,
            saturdayEighthLessonTeacherFG: this.grade.saturdayEighthLessonTeacherFG,
            saturdayEighthLessonClassroomFG: this.grade.saturdayEighthLessonClassroomFG,
            saturdayEighthLessonSG: this.grade.saturdayEighthLessonSG,
            saturdayEighthLessonTeacherSG: this.grade.saturdayEighthLessonTeacherSG,
            saturdayEighthLessonClassroomSG: this.grade.saturdayEighthLessonClassroomSG,
            saturdayNinthLessonFG: this.grade.saturdayNinthLessonFG,
            saturdayNinthLessonTeacherFG: this.grade.saturdayNinthLessonTeacherFG,
            saturdayNinthLessonClassroomFG: this.grade.saturdayNinthLessonClassroomFG,
            saturdayNinthLessonSG: this.grade.saturdayNinthLessonSG,
            saturdayNinthLessonTeacherSG: this.grade.saturdayNinthLessonTeacherSG,
            saturdayNinthLessonClassroomSG: this.grade.saturdayNinthLessonClassroomSG,
            saturdayTenthLessonFG: this.grade.saturdayTenthLessonFG,
            saturdayTenthLessonTeacherFG: this.grade.saturdayTenthLessonTeacherFG,
            saturdayTenthLessonClassroomFG: this.grade.saturdayTenthLessonClassroomFG,
            saturdayTenthLessonSG: this.grade.saturdayTenthLessonSG,
            saturdayTenthLessonTeacherSG: this.grade.saturdayTenthLessonTeacherSG,
            saturdayTenthLessonClassroomSG: this.grade.saturdayTenthLessonClassroomSG,

          });
        });
    });
  }

  onSaveGrade() {
    if (this.form.invalid) {
      return;
    }
    this.isLoading = true;
      this.gradesService.updateGrade(
        this.gradeId,
        this.form.value.gradeNumber,
        this.form.value.gradeLiter,

        this.form.value.mondayFirstLessonFG,
        this.form.value.mondayFirstLessonTeacherFG,
        this.form.value.mondayFirstLessonClassroomFG,
        this.form.value.mondayFirstLessonSG,
        this.form.value.mondayFirstLessonTeacherSG,
        this.form.value.mondayFirstLessonClassroomSG,
        this.form.value.mondaySecondLessonFG,
        this.form.value.mondaySecondLessonTeacherFG,
        this.form.value.mondaySecondLessonClassroomFG,
        this.form.value.mondaySecondLessonSG,
        this.form.value.mondaySecondLessonTeacherSG,
        this.form.value.mondaySecondLessonClassroomSG,
        this.form.value.mondayThirdLessonFG,
        this.form.value.mondayThirdLessonTeacherFG,
        this.form.value.mondayThirdLessonClassroomFG,
        this.form.value.mondayThirdLessonSG,
        this.form.value.mondayThirdLessonTeacherSG,
        this.form.value.mondayThirdLessonClassroomSG,
        this.form.value.mondayFourthLessonFG,
        this.form.value.mondayFourthLessonTeacherFG,
        this.form.value.mondayFourthLessonClassroomFG,
        this.form.value.mondayFourthLessonSG,
        this.form.value.mondayFourthLessonTeacherSG,
        this.form.value.mondayFourthLessonClassroomSG,
        this.form.value.mondayFifthLessonFG,
        this.form.value.mondayFifthLessonTeacherFG,
        this.form.value.mondayFifthLessonClassroomFG,
        this.form.value.mondayFifthLessonSG,
        this.form.value.mondayFifthLessonTeacherSG,
        this.form.value.mondayFifthLessonClassroomSG,
        this.form.value.mondaySixthLessonFG,
        this.form.value.mondaySixthLessonTeacherFG,
        this.form.value.mondaySixthLessonClassroomFG,
        this.form.value.mondaySixthLessonSG,
        this.form.value.mondaySixthLessonTeacherSG,
        this.form.value.mondaySixthLessonClassroomSG,
        this.form.value.mondaySeventhLessonFG,
        this.form.value.mondaySeventhLessonTeacherFG,
        this.form.value.mondaySeventhLessonClassroomFG,
        this.form.value.mondaySeventhLessonSG,
        this.form.value.mondaySeventhLessonTeacherSG,
        this.form.value.mondaySeventhLessonClassroomSG,
        this.form.value.mondayEighthLessonFG,
        this.form.value.mondayEighthLessonTeacherFG,
        this.form.value.mondayEighthLessonClassroomFG,
        this.form.value.mondayEighthLessonSG,
        this.form.value.mondayEighthLessonTeacherSG,
        this.form.value.mondayEighthLessonClassroomSG,
        this.form.value.mondayNinthLessonFG,
        this.form.value.mondayNinthLessonTeacherFG,
        this.form.value.mondayNinthLessonClassroomFG,
        this.form.value.mondayNinthLessonSG,
        this.form.value.mondayNinthLessonTeacherSG,
        this.form.value.mondayNinthLessonClassroomSG,
        this.form.value.mondayTenthLessonFG,
        this.form.value.mondayTenthLessonTeacherFG,
        this.form.value.mondayTenthLessonClassroomFG,
        this.form.value.mondayTenthLessonSG,
        this.form.value.mondayTenthLessonTeacherSG,
        this.form.value.mondayTenthLessonClassroomSG,

        this.form.value.tuesdayFirstLessonFG,
        this.form.value.tuesdayFirstLessonTeacherFG,
        this.form.value.tuesdayFirstLessonClassroomFG,
        this.form.value.tuesdayFirstLessonSG,
        this.form.value.tuesdayFirstLessonTeacherSG,
        this.form.value.tuesdayFirstLessonClassroomSG,
        this.form.value.tuesdaySecondLessonFG,
        this.form.value.tuesdaySecondLessonTeacherFG,
        this.form.value.tuesdaySecondLessonClassroomFG,
        this.form.value.tuesdaySecondLessonSG,
        this.form.value.tuesdaySecondLessonTeacherSG,
        this.form.value.tuesdaySecondLessonClassroomSG,
        this.form.value.tuesdayThirdLessonFG,
        this.form.value.tuesdayThirdLessonTeacherFG,
        this.form.value.tuesdayThirdLessonClassroomFG,
        this.form.value.tuesdayThirdLessonSG,
        this.form.value.tuesdayThirdLessonTeacherSG,
        this.form.value.tuesdayThirdLessonClassroomSG,
        this.form.value.tuesdayFourthLessonFG,
        this.form.value.tuesdayFourthLessonTeacherFG,
        this.form.value.tuesdayFourthLessonClassroomFG,
        this.form.value.tuesdayFourthLessonSG,
        this.form.value.tuesdayFourthLessonTeacherSG,
        this.form.value.tuesdayFourthLessonClassroomSG,
        this.form.value.tuesdayFifthLessonFG,
        this.form.value.tuesdayFifthLessonTeacherFG,
        this.form.value.tuesdayFifthLessonClassroomFG,
        this.form.value.tuesdayFifthLessonSG,
        this.form.value.tuesdayFifthLessonTeacherSG,
        this.form.value.tuesdayFifthLessonClassroomSG,
        this.form.value.tuesdaySixthLessonFG,
        this.form.value.tuesdaySixthLessonTeacherFG,
        this.form.value.tuesdaySixthLessonClassroomFG,
        this.form.value.tuesdaySixthLessonSG,
        this.form.value.tuesdaySixthLessonTeacherSG,
        this.form.value.tuesdaySixthLessonClassroomSG,
        this.form.value.tuesdaySeventhLessonFG,
        this.form.value.tuesdaySeventhLessonTeacherFG,
        this.form.value.tuesdaySeventhLessonClassroomFG,
        this.form.value.tuesdaySeventhLessonSG,
        this.form.value.tuesdaySeventhLessonTeacherSG,
        this.form.value.tuesdaySeventhLessonClassroomSG,
        this.form.value.tuesdayEighthLessonFG,
        this.form.value.tuesdayEighthLessonTeacherFG,
        this.form.value.tuesdayEighthLessonClassroomFG,
        this.form.value.tuesdayEighthLessonSG,
        this.form.value.tuesdayEighthLessonTeacherSG,
        this.form.value.tuesdayEighthLessonClassroomSG,
        this.form.value.tuesdayNinthLessonFG,
        this.form.value.tuesdayNinthLessonTeacherFG,
        this.form.value.tuesdayNinthLessonClassroomFG,
        this.form.value.tuesdayNinthLessonSG,
        this.form.value.tuesdayNinthLessonTeacherSG,
        this.form.value.tuesdayNinthLessonClassroomSG,
        this.form.value.tuesdayTenthLessonFG,
        this.form.value.tuesdayTenthLessonTeacherFG,
        this.form.value.tuesdayTenthLessonClassroomFG,
        this.form.value.tuesdayTenthLessonSG,
        this.form.value.tuesdayTenthLessonTeacherSG,
        this.form.value.tuesdayTenthLessonClassroomSG,

        this.form.value.wednesdayFirstLessonFG,
        this.form.value.wednesdayFirstLessonTeacherFG,
        this.form.value.wednesdayFirstLessonClassroomFG,
        this.form.value.wednesdayFirstLessonSG,
        this.form.value.wednesdayFirstLessonTeacherSG,
        this.form.value.wednesdayFirstLessonClassroomSG,
        this.form.value.wednesdaySecondLessonFG,
        this.form.value.wednesdaySecondLessonTeacherFG,
        this.form.value.wednesdaySecondLessonClassroomFG,
        this.form.value.wednesdaySecondLessonSG,
        this.form.value.wednesdaySecondLessonTeacherSG,
        this.form.value.wednesdaySecondLessonClassroomSG,
        this.form.value.wednesdayThirdLessonFG,
        this.form.value.wednesdayThirdLessonTeacherFG,
        this.form.value.wednesdayThirdLessonClassroomFG,
        this.form.value.wednesdayThirdLessonSG,
        this.form.value.wednesdayThirdLessonTeacherSG,
        this.form.value.wednesdayThirdLessonClassroomSG,
        this.form.value.wednesdayFourthLessonFG,
        this.form.value.wednesdayFourthLessonTeacherFG,
        this.form.value.wednesdayFourthLessonClassroomFG,
        this.form.value.wednesdayFourthLessonSG,
        this.form.value.wednesdayFourthLessonTeacherSG,
        this.form.value.wednesdayFourthLessonClassroomSG,
        this.form.value.wednesdayFifthLessonFG,
        this.form.value.wednesdayFifthLessonTeacherFG,
        this.form.value.wednesdayFifthLessonClassroomFG,
        this.form.value.wednesdayFifthLessonSG,
        this.form.value.wednesdayFifthLessonTeacherSG,
        this.form.value.wednesdayFifthLessonClassroomSG,
        this.form.value.wednesdaySixthLessonFG,
        this.form.value.wednesdaySixthLessonTeacherFG,
        this.form.value.wednesdaySixthLessonClassroomFG,
        this.form.value.wednesdaySixthLessonSG,
        this.form.value.wednesdaySixthLessonTeacherSG,
        this.form.value.wednesdaySixthLessonClassroomSG,
        this.form.value.wednesdaySeventhLessonFG,
        this.form.value.wednesdaySeventhLessonTeacherFG,
        this.form.value.wednesdaySeventhLessonClassroomFG,
        this.form.value.wednesdaySeventhLessonSG,
        this.form.value.wednesdaySeventhLessonTeacherSG,
        this.form.value.wednesdaySeventhLessonClassroomSG,
        this.form.value.wednesdayEighthLessonFG,
        this.form.value.wednesdayEighthLessonTeacherFG,
        this.form.value.wednesdayEighthLessonClassroomFG,
        this.form.value.wednesdayEighthLessonSG,
        this.form.value.wednesdayEighthLessonTeacherSG,
        this.form.value.wednesdayEighthLessonClassroomSG,
        this.form.value.wednesdayNinthLessonFG,
        this.form.value.wednesdayNinthLessonTeacherFG,
        this.form.value.wednesdayNinthLessonClassroomFG,
        this.form.value.wednesdayNinthLessonSG,
        this.form.value.wednesdayNinthLessonTeacherSG,
        this.form.value.wednesdayNinthLessonClassroomSG,
        this.form.value.wednesdayTenthLessonFG,
        this.form.value.wednesdayTenthLessonTeacherFG,
        this.form.value.wednesdayTenthLessonClassroomFG,
        this.form.value.wednesdayTenthLessonSG,
        this.form.value.wednesdayTenthLessonTeacherSG,
        this.form.value.wednesdayTenthLessonClassroomSG,

        this.form.value.thursdayFirstLessonFG,
        this.form.value.thursdayFirstLessonTeacherFG,
        this.form.value.thursdayFirstLessonClassroomFG,
        this.form.value.thursdayFirstLessonSG,
        this.form.value.thursdayFirstLessonTeacherSG,
        this.form.value.thursdayFirstLessonClassroomSG,
        this.form.value.thursdaySecondLessonFG,
        this.form.value.thursdaySecondLessonTeacherFG,
        this.form.value.thursdaySecondLessonClassroomFG,
        this.form.value.thursdaySecondLessonSG,
        this.form.value.thursdaySecondLessonTeacherSG,
        this.form.value.thursdaySecondLessonClassroomSG,
        this.form.value.thursdayThirdLessonFG,
        this.form.value.thursdayThirdLessonTeacherFG,
        this.form.value.thursdayThirdLessonClassroomFG,
        this.form.value.thursdayThirdLessonSG,
        this.form.value.thursdayThirdLessonTeacherSG,
        this.form.value.thursdayThirdLessonClassroomSG,
        this.form.value.thursdayFourthLessonFG,
        this.form.value.thursdayFourthLessonTeacherFG,
        this.form.value.thursdayFourthLessonClassroomFG,
        this.form.value.thursdayFourthLessonSG,
        this.form.value.thursdayFourthLessonTeacherSG,
        this.form.value.thursdayFourthLessonClassroomSG,
        this.form.value.thursdayFifthLessonFG,
        this.form.value.thursdayFifthLessonTeacherFG,
        this.form.value.thursdayFifthLessonClassroomFG,
        this.form.value.thursdayFifthLessonSG,
        this.form.value.thursdayFifthLessonTeacherSG,
        this.form.value.thursdayFifthLessonClassroomSG,
        this.form.value.thursdaySixthLessonFG,
        this.form.value.thursdaySixthLessonTeacherFG,
        this.form.value.thursdaySixthLessonClassroomFG,
        this.form.value.thursdaySixthLessonSG,
        this.form.value.thursdaySixthLessonTeacherSG,
        this.form.value.thursdaySixthLessonClassroomSG,
        this.form.value.thursdaySeventhLessonFG,
        this.form.value.thursdaySeventhLessonTeacherFG,
        this.form.value.thursdaySeventhLessonClassroomFG,
        this.form.value.thursdaySeventhLessonSG,
        this.form.value.thursdaySeventhLessonTeacherSG,
        this.form.value.thursdaySeventhLessonClassroomSG,
        this.form.value.thursdayEighthLessonFG,
        this.form.value.thursdayEighthLessonTeacherFG,
        this.form.value.thursdayEighthLessonClassroomFG,
        this.form.value.thursdayEighthLessonSG,
        this.form.value.thursdayEighthLessonTeacherSG,
        this.form.value.thursdayEighthLessonClassroomSG,
        this.form.value.thursdayNinthLessonFG,
        this.form.value.thursdayNinthLessonTeacherFG,
        this.form.value.thursdayNinthLessonClassroomFG,
        this.form.value.thursdayNinthLessonSG,
        this.form.value.thursdayNinthLessonTeacherSG,
        this.form.value.thursdayNinthLessonClassroomSG,
        this.form.value.thursdayTenthLessonFG,
        this.form.value.thursdayTenthLessonTeacherFG,
        this.form.value.thursdayTenthLessonClassroomFG,
        this.form.value.thursdayTenthLessonSG,
        this.form.value.thursdayTenthLessonTeacherSG,
        this.form.value.thursdayTenthLessonClassroomSG,

        this.form.value.fridayFirstLessonFG,
        this.form.value.fridayFirstLessonTeacherFG,
        this.form.value.fridayFirstLessonClassroomFG,
        this.form.value.fridayFirstLessonSG,
        this.form.value.fridayFirstLessonTeacherSG,
        this.form.value.fridayFirstLessonClassroomSG,
        this.form.value.fridaySecondLessonFG,
        this.form.value.fridaySecondLessonTeacherFG,
        this.form.value.fridaySecondLessonClassroomFG,
        this.form.value.fridaySecondLessonSG,
        this.form.value.fridaySecondLessonTeacherSG,
        this.form.value.fridaySecondLessonClassroomSG,
        this.form.value.fridayThirdLessonFG,
        this.form.value.fridayThirdLessonTeacherFG,
        this.form.value.fridayThirdLessonClassroomFG,
        this.form.value.fridayThirdLessonSG,
        this.form.value.fridayThirdLessonTeacherSG,
        this.form.value.fridayThirdLessonClassroomSG,
        this.form.value.fridayFourthLessonFG,
        this.form.value.fridayFourthLessonTeacherFG,
        this.form.value.fridayFourthLessonClassroomFG,
        this.form.value.fridayFourthLessonSG,
        this.form.value.fridayFourthLessonTeacherSG,
        this.form.value.fridayFourthLessonClassroomSG,
        this.form.value.fridayFifthLessonFG,
        this.form.value.fridayFifthLessonTeacherFG,
        this.form.value.fridayFifthLessonClassroomFG,
        this.form.value.fridayFifthLessonSG,
        this.form.value.fridayFifthLessonTeacherSG,
        this.form.value.fridayFifthLessonClassroomSG,
        this.form.value.fridaySixthLessonFG,
        this.form.value.fridaySixthLessonTeacherFG,
        this.form.value.fridaySixthLessonClassroomFG,
        this.form.value.fridaySixthLessonSG,
        this.form.value.fridaySixthLessonTeacherSG,
        this.form.value.fridaySixthLessonClassroomSG,
        this.form.value.fridaySeventhLessonFG,
        this.form.value.fridaySeventhLessonTeacherFG,
        this.form.value.fridaySeventhLessonClassroomFG,
        this.form.value.fridaySeventhLessonSG,
        this.form.value.fridaySeventhLessonTeacherSG,
        this.form.value.fridaySeventhLessonClassroomSG,
        this.form.value.fridayEighthLessonFG,
        this.form.value.fridayEighthLessonTeacherFG,
        this.form.value.fridayEighthLessonClassroomFG,
        this.form.value.fridayEighthLessonSG,
        this.form.value.fridayEighthLessonTeacherSG,
        this.form.value.fridayEighthLessonClassroomSG,
        this.form.value.fridayNinthLessonFG,
        this.form.value.fridayNinthLessonTeacherFG,
        this.form.value.fridayNinthLessonClassroomFG,
        this.form.value.fridayNinthLessonSG,
        this.form.value.fridayNinthLessonTeacherSG,
        this.form.value.fridayNinthLessonClassroomSG,
        this.form.value.fridayTenthLessonFG,
        this.form.value.fridayTenthLessonTeacherFG,
        this.form.value.fridayTenthLessonClassroomFG,
        this.form.value.fridayTenthLessonSG,
        this.form.value.fridayTenthLessonTeacherSG,
        this.form.value.fridayTenthLessonClassroomSG,

        this.form.value.saturdayFirstLessonFG,
        this.form.value.saturdayFirstLessonTeacherFG,
        this.form.value.saturdayFirstLessonClassroomFG,
        this.form.value.saturdayFirstLessonSG,
        this.form.value.saturdayFirstLessonTeacherSG,
        this.form.value.saturdayFirstLessonClassroomSG,
        this.form.value.saturdaySecondLessonFG,
        this.form.value.saturdaySecondLessonTeacherFG,
        this.form.value.saturdaySecondLessonClassroomFG,
        this.form.value.saturdaySecondLessonSG,
        this.form.value.saturdaySecondLessonTeacherSG,
        this.form.value.saturdaySecondLessonClassroomSG,
        this.form.value.saturdayThirdLessonFG,
        this.form.value.saturdayThirdLessonTeacherFG,
        this.form.value.saturdayThirdLessonClassroomFG,
        this.form.value.saturdayThirdLessonSG,
        this.form.value.saturdayThirdLessonTeacherSG,
        this.form.value.saturdayThirdLessonClassroomSG,
        this.form.value.saturdayFourthLessonFG,
        this.form.value.saturdayFourthLessonTeacherFG,
        this.form.value.saturdayFourthLessonClassroomFG,
        this.form.value.saturdayFourthLessonSG,
        this.form.value.saturdayFourthLessonTeacherSG,
        this.form.value.saturdayFourthLessonClassroomSG,
        this.form.value.saturdayFifthLessonFG,
        this.form.value.saturdayFifthLessonTeacherFG,
        this.form.value.saturdayFifthLessonClassroomFG,
        this.form.value.saturdayFifthLessonSG,
        this.form.value.saturdayFifthLessonTeacherSG,
        this.form.value.saturdayFifthLessonClassroomSG,
        this.form.value.saturdaySixthLessonFG,
        this.form.value.saturdaySixthLessonTeacherFG,
        this.form.value.saturdaySixthLessonClassroomFG,
        this.form.value.saturdaySixthLessonSG,
        this.form.value.saturdaySixthLessonTeacherSG,
        this.form.value.saturdaySixthLessonClassroomSG,
        this.form.value.saturdaySeventhLessonFG,
        this.form.value.saturdaySeventhLessonTeacherFG,
        this.form.value.saturdaySeventhLessonClassroomFG,
        this.form.value.saturdaySeventhLessonSG,
        this.form.value.saturdaySeventhLessonTeacherSG,
        this.form.value.saturdaySeventhLessonClassroomSG,
        this.form.value.saturdayEighthLessonFG,
        this.form.value.saturdayEighthLessonTeacherFG,
        this.form.value.saturdayEighthLessonClassroomFG,
        this.form.value.saturdayEighthLessonSG,
        this.form.value.saturdayEighthLessonTeacherSG,
        this.form.value.saturdayEighthLessonClassroomSG,
        this.form.value.saturdayNinthLessonFG,
        this.form.value.saturdayNinthLessonTeacherFG,
        this.form.value.saturdayNinthLessonClassroomFG,
        this.form.value.saturdayNinthLessonSG,
        this.form.value.saturdayNinthLessonTeacherSG,
        this.form.value.saturdayNinthLessonClassroomSG,
        this.form.value.saturdayTenthLessonFG,
        this.form.value.saturdayTenthLessonTeacherFG,
        this.form.value.saturdayTenthLessonClassroomFG,
        this.form.value.saturdayTenthLessonSG,
        this.form.value.saturdayTenthLessonTeacherSG,
        this.form.value.saturdayTenthLessonClassroomSG,
      );
    this.form.reset();
  }

  ngOnDestroy() {
    this.authStatusSub.unsubscribe();
    this.gradesSub.unsubscribe();
    this.subjectsSub.unsubscribe();
  }
}
