import { Component, OnInit, OnDestroy } from '@angular/core';
import { SubjectModel } from 'src/app/subjects/subject.model';
import { GradeModel } from '../grade.model';
import { Subscription } from 'rxjs';
import { SubjectsService } from 'src/app/subjects/subjects.service';
import { GradesService } from '../grades.service';
import { AuthService } from 'src/app/auth/auth.service';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { ActivatedRoute, ParamMap } from '@angular/router';

@Component({
  selector: 'app-schedule',
  templateUrl: './schedule.component.html',
  styleUrls: ['./schedule.component.css']
})
export class ScheduleComponent implements OnInit, OnDestroy {
  form: FormGroup;
  subjects: SubjectModel[] = [];
  grades: GradeModel[] = [];
  private gradesSub: Subscription;
  private subjectsSub: Subscription;
  isLoading = false;
  private authStatusSub: Subscription;
  grade: GradeModel;
  private gradeId: string;

  constructor(
    public subjectsService: SubjectsService,
    public gradesService: GradesService,
    private authService: AuthService,
    public route: ActivatedRoute,
    ) { }

  ngOnInit() {
    this.isLoading = true;

    this.gradesSub = this.gradesService
      .getGradeUpdateListener()
      .subscribe(( grades: GradeModel[] ) => {
        this.isLoading = false;
        this.grades = grades;
      });

      this.authStatusSub = this.authService
        .getAuthStatusListener()
        .subscribe(authStatus => {
          this.isLoading = false;
        });

        this.subjectsService.getSubjects();
        this.subjectsSub = this.subjectsService
        .getSubjectUpdateListener()
        .subscribe(( subjects: SubjectModel[] ) => {
          this.isLoading = false;
          this.subjects = subjects;
        });



        this.route.paramMap.subscribe((paramMap: ParamMap) => {
          this.gradeId = paramMap.get('gradeId');
          this.gradesService.getGrade(this.gradeId).subscribe(gradeData => {
          this.isLoading = false;
          this.grade = {
            id: gradeData._id,

            gradeNumber: gradeData.gradeNumber,
            gradeLiter: gradeData.gradeLiter,

            mondayFirstLessonFG: gradeData.mondayFirstLessonFG,
            mondayFirstLessonTeacherFG: gradeData.mondayFirstLessonTeacherFG,
            mondayFirstLessonClassroomFG: gradeData.mondayFirstLessonClassroomFG,
            mondayFirstLessonSG: gradeData.mondayFirstLessonSG,
            mondayFirstLessonTeacherSG: gradeData.mondayFirstLessonTeacherSG,
            mondayFirstLessonClassroomSG: gradeData.mondayFirstLessonClassroomSG,
            mondaySecondLessonFG: gradeData.mondaySecondLessonFG,
            mondaySecondLessonTeacherFG: gradeData.mondaySecondLessonTeacherFG,
            mondaySecondLessonClassroomFG: gradeData.mondaySecondLessonClassroomFG,
            mondaySecondLessonSG: gradeData.mondaySecondLessonSG,
            mondaySecondLessonTeacherSG: gradeData.mondaySecondLessonTeacherSG,
            mondaySecondLessonClassroomSG: gradeData.mondaySecondLessonClassroomSG,
            mondayThirdLessonFG: gradeData.mondayThirdLessonFG,
            mondayThirdLessonTeacherFG: gradeData.mondayThirdLessonTeacherFG,
            mondayThirdLessonClassroomFG: gradeData.mondayThirdLessonClassroomFG,
            mondayThirdLessonSG: gradeData.mondayThirdLessonSG,
            mondayThirdLessonTeacherSG: gradeData.mondayThirdLessonTeacherSG,
            mondayThirdLessonClassroomSG: gradeData.mondayThirdLessonClassroomSG,
            mondayFourthLessonFG: gradeData.mondayFourthLessonFG,
            mondayFourthLessonTeacherFG: gradeData.mondayFourthLessonTeacherFG,
            mondayFourthLessonClassroomFG: gradeData.mondayFourthLessonClassroomFG,
            mondayFourthLessonSG: gradeData.mondayFourthLessonSG,
            mondayFourthLessonTeacherSG: gradeData.mondayFourthLessonTeacherSG,
            mondayFourthLessonClassroomSG: gradeData.mondayFourthLessonClassroomSG,
            mondayFifthLessonFG: gradeData.mondayFifthLessonFG,
            mondayFifthLessonTeacherFG: gradeData.mondayFifthLessonTeacherFG,
            mondayFifthLessonClassroomFG: gradeData.mondayFifthLessonClassroomFG,
            mondayFifthLessonSG: gradeData.mondayFifthLessonSG,
            mondayFifthLessonTeacherSG: gradeData.mondayFifthLessonTeacherSG,
            mondayFifthLessonClassroomSG: gradeData.mondayFifthLessonClassroomSG,
            mondaySixthLessonFG: gradeData.mondaySixthLessonFG,
            mondaySixthLessonTeacherFG: gradeData.mondaySixthLessonTeacherFG,
            mondaySixthLessonClassroomFG: gradeData.mondaySixthLessonClassroomFG,
            mondaySixthLessonSG: gradeData.mondaySixthLessonSG,
            mondaySixthLessonTeacherSG: gradeData.mondaySixthLessonTeacherSG,
            mondaySixthLessonClassroomSG: gradeData.mondaySixthLessonClassroomSG,
            mondaySeventhLessonFG: gradeData.mondaySeventhLessonFG,
            mondaySeventhLessonTeacherFG: gradeData.mondaySeventhLessonTeacherFG,
            mondaySeventhLessonClassroomFG: gradeData.mondaySeventhLessonClassroomFG,
            mondaySeventhLessonSG: gradeData.mondaySeventhLessonSG,
            mondaySeventhLessonTeacherSG: gradeData.mondaySeventhLessonTeacherSG,
            mondaySeventhLessonClassroomSG: gradeData.mondaySeventhLessonClassroomSG,
            mondayEighthLessonFG: gradeData.mondayEighthLessonFG,
            mondayEighthLessonTeacherFG: gradeData.mondayEighthLessonTeacherFG,
            mondayEighthLessonClassroomFG: gradeData.mondayEighthLessonClassroomFG,
            mondayEighthLessonSG: gradeData.mondayEighthLessonSG,
            mondayEighthLessonTeacherSG: gradeData.mondayEighthLessonTeacherSG,
            mondayEighthLessonClassroomSG: gradeData.mondayEighthLessonClassroomSG,
            mondayNinthLessonFG: gradeData.mondayNinthLessonFG,
            mondayNinthLessonTeacherFG: gradeData.mondayNinthLessonTeacherFG,
            mondayNinthLessonClassroomFG: gradeData.mondayNinthLessonClassroomFG,
            mondayNinthLessonSG: gradeData.mondayNinthLessonSG,
            mondayNinthLessonTeacherSG: gradeData.mondayNinthLessonTeacherSG,
            mondayNinthLessonClassroomSG: gradeData.mondayNinthLessonClassroomSG,
            mondayTenthLessonFG: gradeData.mondayTenthLessonFG,
            mondayTenthLessonTeacherFG: gradeData.mondayTenthLessonTeacherFG,
            mondayTenthLessonClassroomFG: gradeData.mondayTenthLessonClassroomFG,
            mondayTenthLessonSG: gradeData.mondayTenthLessonSG,
            mondayTenthLessonTeacherSG: gradeData.mondayTenthLessonTeacherSG,
            mondayTenthLessonClassroomSG: gradeData.mondayTenthLessonClassroomSG,

            tuesdayFirstLessonFG: gradeData.tuesdayFirstLessonFG,
            tuesdayFirstLessonTeacherFG: gradeData.tuesdayFirstLessonTeacherFG,
            tuesdayFirstLessonClassroomFG: gradeData.tuesdayFirstLessonClassroomFG,
            tuesdayFirstLessonSG: gradeData.tuesdayFirstLessonSG,
            tuesdayFirstLessonTeacherSG: gradeData.tuesdayFirstLessonTeacherSG,
            tuesdayFirstLessonClassroomSG: gradeData.tuesdayFirstLessonClassroomSG,
            tuesdaySecondLessonFG: gradeData.tuesdaySecondLessonFG,
            tuesdaySecondLessonTeacherFG: gradeData.tuesdaySecondLessonTeacherFG,
            tuesdaySecondLessonClassroomFG: gradeData.tuesdaySecondLessonClassroomFG,
            tuesdaySecondLessonSG: gradeData.tuesdaySecondLessonSG,
            tuesdaySecondLessonTeacherSG: gradeData.tuesdaySecondLessonTeacherSG,
            tuesdaySecondLessonClassroomSG: gradeData.tuesdaySecondLessonClassroomSG,
            tuesdayThirdLessonFG: gradeData.tuesdayThirdLessonFG,
            tuesdayThirdLessonTeacherFG: gradeData.tuesdayThirdLessonTeacherFG,
            tuesdayThirdLessonClassroomFG: gradeData.tuesdayThirdLessonClassroomFG,
            tuesdayThirdLessonSG: gradeData.tuesdayThirdLessonSG,
            tuesdayThirdLessonTeacherSG: gradeData.tuesdayThirdLessonTeacherSG,
            tuesdayThirdLessonClassroomSG: gradeData.tuesdayThirdLessonClassroomSG,
            tuesdayFourthLessonFG: gradeData.tuesdayFourthLessonFG,
            tuesdayFourthLessonTeacherFG: gradeData.tuesdayFourthLessonTeacherFG,
            tuesdayFourthLessonClassroomFG: gradeData.tuesdayFourthLessonClassroomFG,
            tuesdayFourthLessonSG: gradeData.tuesdayFourthLessonSG,
            tuesdayFourthLessonTeacherSG: gradeData.tuesdayFourthLessonTeacherSG,
            tuesdayFourthLessonClassroomSG: gradeData.tuesdayFourthLessonClassroomSG,
            tuesdayFifthLessonFG: gradeData.tuesdayFifthLessonFG,
            tuesdayFifthLessonTeacherFG: gradeData.tuesdayFifthLessonTeacherFG,
            tuesdayFifthLessonClassroomFG: gradeData.tuesdayFifthLessonClassroomFG,
            tuesdayFifthLessonSG: gradeData.tuesdayFifthLessonSG,
            tuesdayFifthLessonTeacherSG: gradeData.tuesdayFifthLessonTeacherSG,
            tuesdayFifthLessonClassroomSG: gradeData.tuesdayFifthLessonClassroomSG,
            tuesdaySixthLessonFG: gradeData.tuesdaySixthLessonFG,
            tuesdaySixthLessonTeacherFG: gradeData.tuesdaySixthLessonTeacherFG,
            tuesdaySixthLessonClassroomFG: gradeData.tuesdaySixthLessonClassroomFG,
            tuesdaySixthLessonSG: gradeData.tuesdaySixthLessonSG,
            tuesdaySixthLessonTeacherSG: gradeData.tuesdaySixthLessonTeacherSG,
            tuesdaySixthLessonClassroomSG: gradeData.tuesdaySixthLessonClassroomSG,
            tuesdaySeventhLessonFG: gradeData.tuesdaySeventhLessonFG,
            tuesdaySeventhLessonTeacherFG: gradeData.tuesdaySeventhLessonTeacherFG,
            tuesdaySeventhLessonClassroomFG: gradeData.tuesdaySeventhLessonClassroomFG,
            tuesdaySeventhLessonSG: gradeData.tuesdaySeventhLessonSG,
            tuesdaySeventhLessonTeacherSG: gradeData.tuesdaySeventhLessonTeacherSG,
            tuesdaySeventhLessonClassroomSG: gradeData.tuesdaySeventhLessonClassroomSG,
            tuesdayEighthLessonFG: gradeData.tuesdayEighthLessonFG,
            tuesdayEighthLessonTeacherFG: gradeData.tuesdayEighthLessonTeacherFG,
            tuesdayEighthLessonClassroomFG: gradeData.tuesdayEighthLessonClassroomFG,
            tuesdayEighthLessonSG: gradeData.tuesdayEighthLessonSG,
            tuesdayEighthLessonTeacherSG: gradeData.tuesdayEighthLessonTeacherSG,
            tuesdayEighthLessonClassroomSG: gradeData.tuesdayEighthLessonClassroomSG,
            tuesdayNinthLessonFG: gradeData.tuesdayNinthLessonFG,
            tuesdayNinthLessonTeacherFG: gradeData.tuesdayNinthLessonTeacherFG,
            tuesdayNinthLessonClassroomFG: gradeData.tuesdayNinthLessonClassroomFG,
            tuesdayNinthLessonSG: gradeData.tuesdayNinthLessonSG,
            tuesdayNinthLessonTeacherSG: gradeData.tuesdayNinthLessonTeacherSG,
            tuesdayNinthLessonClassroomSG: gradeData.tuesdayNinthLessonClassroomSG,
            tuesdayTenthLessonFG: gradeData.tuesdayTenthLessonFG,
            tuesdayTenthLessonTeacherFG: gradeData.tuesdayTenthLessonTeacherFG,
            tuesdayTenthLessonClassroomFG: gradeData.tuesdayTenthLessonClassroomFG,
            tuesdayTenthLessonSG: gradeData.tuesdayTenthLessonSG,
            tuesdayTenthLessonTeacherSG: gradeData.tuesdayTenthLessonTeacherSG,
            tuesdayTenthLessonClassroomSG: gradeData.tuesdayTenthLessonClassroomSG,

            wednesdayFirstLessonFG: gradeData.wednesdayFirstLessonFG,
            wednesdayFirstLessonTeacherFG: gradeData.wednesdayFirstLessonTeacherFG,
            wednesdayFirstLessonClassroomFG: gradeData.wednesdayFirstLessonClassroomFG,
            wednesdayFirstLessonSG: gradeData.wednesdayFirstLessonSG,
            wednesdayFirstLessonTeacherSG: gradeData.wednesdayFirstLessonTeacherSG,
            wednesdayFirstLessonClassroomSG: gradeData.wednesdayFirstLessonClassroomSG,
            wednesdaySecondLessonFG: gradeData.wednesdaySecondLessonFG,
            wednesdaySecondLessonTeacherFG: gradeData.wednesdaySecondLessonTeacherFG,
            wednesdaySecondLessonClassroomFG: gradeData.wednesdaySecondLessonClassroomFG,
            wednesdaySecondLessonSG: gradeData.wednesdaySecondLessonSG,
            wednesdaySecondLessonTeacherSG: gradeData.wednesdaySecondLessonTeacherSG,
            wednesdaySecondLessonClassroomSG: gradeData.wednesdaySecondLessonClassroomSG,
            wednesdayThirdLessonFG: gradeData.wednesdayThirdLessonFG,
            wednesdayThirdLessonTeacherFG: gradeData.wednesdayThirdLessonTeacherFG,
            wednesdayThirdLessonClassroomFG: gradeData.wednesdayThirdLessonClassroomFG,
            wednesdayThirdLessonSG: gradeData.wednesdayThirdLessonSG,
            wednesdayThirdLessonTeacherSG: gradeData.wednesdayThirdLessonTeacherSG,
            wednesdayThirdLessonClassroomSG: gradeData.wednesdayThirdLessonClassroomSG,
            wednesdayFourthLessonFG: gradeData.wednesdayFourthLessonFG,
            wednesdayFourthLessonTeacherFG: gradeData.wednesdayFourthLessonTeacherFG,
            wednesdayFourthLessonClassroomFG: gradeData.wednesdayFourthLessonClassroomFG,
            wednesdayFourthLessonSG: gradeData.wednesdayFourthLessonSG,
            wednesdayFourthLessonTeacherSG: gradeData.wednesdayFourthLessonTeacherSG,
            wednesdayFourthLessonClassroomSG: gradeData.wednesdayFourthLessonClassroomSG,
            wednesdayFifthLessonFG: gradeData.wednesdayFifthLessonFG,
            wednesdayFifthLessonTeacherFG: gradeData.wednesdayFifthLessonTeacherFG,
            wednesdayFifthLessonClassroomFG: gradeData.wednesdayFifthLessonClassroomFG,
            wednesdayFifthLessonSG: gradeData.wednesdayFifthLessonSG,
            wednesdayFifthLessonTeacherSG: gradeData.wednesdayFifthLessonTeacherSG,
            wednesdayFifthLessonClassroomSG: gradeData.wednesdayFifthLessonClassroomSG,
            wednesdaySixthLessonFG: gradeData.wednesdaySixthLessonFG,
            wednesdaySixthLessonTeacherFG: gradeData.wednesdaySixthLessonTeacherFG,
            wednesdaySixthLessonClassroomFG: gradeData.wednesdaySixthLessonClassroomFG,
            wednesdaySixthLessonSG: gradeData.wednesdaySixthLessonSG,
            wednesdaySixthLessonTeacherSG: gradeData.wednesdaySixthLessonTeacherSG,
            wednesdaySixthLessonClassroomSG: gradeData.wednesdaySixthLessonClassroomSG,
            wednesdaySeventhLessonFG: gradeData.wednesdaySeventhLessonFG,
            wednesdaySeventhLessonTeacherFG: gradeData.wednesdaySeventhLessonTeacherFG,
            wednesdaySeventhLessonClassroomFG: gradeData.wednesdaySeventhLessonClassroomFG,
            wednesdaySeventhLessonSG: gradeData.wednesdaySeventhLessonSG,
            wednesdaySeventhLessonTeacherSG: gradeData.wednesdaySeventhLessonTeacherSG,
            wednesdaySeventhLessonClassroomSG: gradeData.wednesdaySeventhLessonClassroomSG,
            wednesdayEighthLessonFG: gradeData.wednesdayEighthLessonFG,
            wednesdayEighthLessonTeacherFG: gradeData.wednesdayEighthLessonTeacherFG,
            wednesdayEighthLessonClassroomFG: gradeData.wednesdayEighthLessonClassroomFG,
            wednesdayEighthLessonSG: gradeData.wednesdayEighthLessonSG,
            wednesdayEighthLessonTeacherSG: gradeData.wednesdayEighthLessonTeacherSG,
            wednesdayEighthLessonClassroomSG: gradeData.wednesdayEighthLessonClassroomSG,
            wednesdayNinthLessonFG: gradeData.wednesdayNinthLessonFG,
            wednesdayNinthLessonTeacherFG: gradeData.wednesdayNinthLessonTeacherFG,
            wednesdayNinthLessonClassroomFG: gradeData.wednesdayNinthLessonClassroomFG,
            wednesdayNinthLessonSG: gradeData.wednesdayNinthLessonSG,
            wednesdayNinthLessonTeacherSG: gradeData.wednesdayNinthLessonTeacherSG,
            wednesdayNinthLessonClassroomSG: gradeData.wednesdayNinthLessonClassroomSG,
            wednesdayTenthLessonFG: gradeData.wednesdayTenthLessonFG,
            wednesdayTenthLessonTeacherFG: gradeData.wednesdayTenthLessonTeacherFG,
            wednesdayTenthLessonClassroomFG: gradeData.wednesdayTenthLessonClassroomFG,
            wednesdayTenthLessonSG: gradeData.wednesdayTenthLessonSG,
            wednesdayTenthLessonTeacherSG: gradeData.wednesdayTenthLessonTeacherSG,
            wednesdayTenthLessonClassroomSG: gradeData.wednesdayTenthLessonClassroomSG,

            thursdayFirstLessonFG: gradeData.thursdayFirstLessonFG,
            thursdayFirstLessonTeacherFG: gradeData.thursdayFirstLessonTeacherFG,
            thursdayFirstLessonClassroomFG: gradeData.thursdayFirstLessonClassroomFG,
            thursdayFirstLessonSG: gradeData.thursdayFirstLessonSG,
            thursdayFirstLessonTeacherSG: gradeData.thursdayFirstLessonTeacherSG,
            thursdayFirstLessonClassroomSG: gradeData.thursdayFirstLessonClassroomSG,
            thursdaySecondLessonFG: gradeData.thursdaySecondLessonFG,
            thursdaySecondLessonTeacherFG: gradeData.thursdaySecondLessonTeacherFG,
            thursdaySecondLessonClassroomFG: gradeData.thursdaySecondLessonClassroomFG,
            thursdaySecondLessonSG: gradeData.thursdaySecondLessonSG,
            thursdaySecondLessonTeacherSG: gradeData.thursdaySecondLessonTeacherSG,
            thursdaySecondLessonClassroomSG: gradeData.thursdaySecondLessonClassroomSG,
            thursdayThirdLessonFG: gradeData.thursdayThirdLessonFG,
            thursdayThirdLessonTeacherFG: gradeData.thursdayThirdLessonTeacherFG,
            thursdayThirdLessonClassroomFG: gradeData.thursdayThirdLessonClassroomFG,
            thursdayThirdLessonSG: gradeData.thursdayThirdLessonSG,
            thursdayThirdLessonTeacherSG: gradeData.thursdayThirdLessonTeacherSG,
            thursdayThirdLessonClassroomSG: gradeData.thursdayThirdLessonClassroomSG,
            thursdayFourthLessonFG: gradeData.thursdayFourthLessonFG,
            thursdayFourthLessonTeacherFG: gradeData.thursdayFourthLessonTeacherFG,
            thursdayFourthLessonClassroomFG: gradeData.thursdayFourthLessonClassroomFG,
            thursdayFourthLessonSG: gradeData.thursdayFourthLessonSG,
            thursdayFourthLessonTeacherSG: gradeData.thursdayFourthLessonTeacherSG,
            thursdayFourthLessonClassroomSG: gradeData.thursdayFourthLessonClassroomSG,
            thursdayFifthLessonFG: gradeData.thursdayFifthLessonFG,
            thursdayFifthLessonTeacherFG: gradeData.thursdayFifthLessonTeacherFG,
            thursdayFifthLessonClassroomFG: gradeData.thursdayFifthLessonClassroomFG,
            thursdayFifthLessonSG: gradeData.thursdayFifthLessonSG,
            thursdayFifthLessonTeacherSG: gradeData.thursdayFifthLessonTeacherSG,
            thursdayFifthLessonClassroomSG: gradeData.thursdayFifthLessonClassroomSG,
            thursdaySixthLessonFG: gradeData.thursdaySixthLessonFG,
            thursdaySixthLessonTeacherFG: gradeData.thursdaySixthLessonTeacherFG,
            thursdaySixthLessonClassroomFG: gradeData.thursdaySixthLessonClassroomFG,
            thursdaySixthLessonSG: gradeData.thursdaySixthLessonSG,
            thursdaySixthLessonTeacherSG: gradeData.thursdaySixthLessonTeacherSG,
            thursdaySixthLessonClassroomSG: gradeData.thursdaySixthLessonClassroomSG,
            thursdaySeventhLessonFG: gradeData.thursdaySeventhLessonFG,
            thursdaySeventhLessonTeacherFG: gradeData.thursdaySeventhLessonTeacherFG,
            thursdaySeventhLessonClassroomFG: gradeData.thursdaySeventhLessonClassroomFG,
            thursdaySeventhLessonSG: gradeData.thursdaySeventhLessonSG,
            thursdaySeventhLessonTeacherSG: gradeData.thursdaySeventhLessonTeacherSG,
            thursdaySeventhLessonClassroomSG: gradeData.thursdaySeventhLessonClassroomSG,
            thursdayEighthLessonFG: gradeData.thursdayEighthLessonFG,
            thursdayEighthLessonTeacherFG: gradeData.thursdayEighthLessonTeacherFG,
            thursdayEighthLessonClassroomFG: gradeData.thursdayEighthLessonClassroomFG,
            thursdayEighthLessonSG: gradeData.thursdayEighthLessonSG,
            thursdayEighthLessonTeacherSG: gradeData.thursdayEighthLessonTeacherSG,
            thursdayEighthLessonClassroomSG: gradeData.thursdayEighthLessonClassroomSG,
            thursdayNinthLessonFG: gradeData.thursdayNinthLessonFG,
            thursdayNinthLessonTeacherFG: gradeData.thursdayNinthLessonTeacherFG,
            thursdayNinthLessonClassroomFG: gradeData.thursdayNinthLessonClassroomFG,
            thursdayNinthLessonSG: gradeData.thursdayNinthLessonSG,
            thursdayNinthLessonTeacherSG: gradeData.thursdayNinthLessonTeacherSG,
            thursdayNinthLessonClassroomSG: gradeData.thursdayNinthLessonClassroomSG,
            thursdayTenthLessonFG: gradeData.thursdayTenthLessonFG,
            thursdayTenthLessonTeacherFG: gradeData.thursdayTenthLessonTeacherFG,
            thursdayTenthLessonClassroomFG: gradeData.thursdayTenthLessonClassroomFG,
            thursdayTenthLessonSG: gradeData.thursdayTenthLessonSG,
            thursdayTenthLessonTeacherSG: gradeData.thursdayTenthLessonTeacherSG,
            thursdayTenthLessonClassroomSG: gradeData.thursdayTenthLessonClassroomSG,

            fridayFirstLessonFG: gradeData.fridayFirstLessonFG,
            fridayFirstLessonTeacherFG: gradeData.fridayFirstLessonTeacherFG,
            fridayFirstLessonClassroomFG: gradeData.fridayFirstLessonClassroomFG,
            fridayFirstLessonSG: gradeData.fridayFirstLessonSG,
            fridayFirstLessonTeacherSG: gradeData.fridayFirstLessonTeacherSG,
            fridayFirstLessonClassroomSG: gradeData.fridayFirstLessonClassroomSG,
            fridaySecondLessonFG: gradeData.fridaySecondLessonFG,
            fridaySecondLessonTeacherFG: gradeData.fridaySecondLessonTeacherFG,
            fridaySecondLessonClassroomFG: gradeData.fridaySecondLessonClassroomFG,
            fridaySecondLessonSG: gradeData.fridaySecondLessonSG,
            fridaySecondLessonTeacherSG: gradeData.fridaySecondLessonTeacherSG,
            fridaySecondLessonClassroomSG: gradeData.fridaySecondLessonClassroomSG,
            fridayThirdLessonFG: gradeData.fridayThirdLessonFG,
            fridayThirdLessonTeacherFG: gradeData.fridayThirdLessonTeacherFG,
            fridayThirdLessonClassroomFG: gradeData.fridayThirdLessonClassroomFG,
            fridayThirdLessonSG: gradeData.fridayThirdLessonSG,
            fridayThirdLessonTeacherSG: gradeData.fridayThirdLessonTeacherSG,
            fridayThirdLessonClassroomSG: gradeData.fridayThirdLessonClassroomSG,
            fridayFourthLessonFG: gradeData.fridayFourthLessonFG,
            fridayFourthLessonTeacherFG: gradeData.fridayFourthLessonTeacherFG,
            fridayFourthLessonClassroomFG: gradeData.fridayFourthLessonClassroomFG,
            fridayFourthLessonSG: gradeData.fridayFourthLessonSG,
            fridayFourthLessonTeacherSG: gradeData.fridayFourthLessonTeacherSG,
            fridayFourthLessonClassroomSG: gradeData.fridayFourthLessonClassroomSG,
            fridayFifthLessonFG: gradeData.fridayFifthLessonFG,
            fridayFifthLessonTeacherFG: gradeData.fridayFifthLessonTeacherFG,
            fridayFifthLessonClassroomFG: gradeData.fridayFifthLessonClassroomFG,
            fridayFifthLessonSG: gradeData.fridayFifthLessonSG,
            fridayFifthLessonTeacherSG: gradeData.fridayFifthLessonTeacherSG,
            fridayFifthLessonClassroomSG: gradeData.fridayFifthLessonClassroomSG,
            fridaySixthLessonFG: gradeData.fridaySixthLessonFG,
            fridaySixthLessonTeacherFG: gradeData.fridaySixthLessonTeacherFG,
            fridaySixthLessonClassroomFG: gradeData.fridaySixthLessonClassroomFG,
            fridaySixthLessonSG: gradeData.fridaySixthLessonSG,
            fridaySixthLessonTeacherSG: gradeData.fridaySixthLessonTeacherSG,
            fridaySixthLessonClassroomSG: gradeData.fridaySixthLessonClassroomSG,
            fridaySeventhLessonFG: gradeData.fridaySeventhLessonFG,
            fridaySeventhLessonTeacherFG: gradeData.fridaySeventhLessonTeacherFG,
            fridaySeventhLessonClassroomFG: gradeData.fridaySeventhLessonClassroomFG,
            fridaySeventhLessonSG: gradeData.fridaySeventhLessonSG,
            fridaySeventhLessonTeacherSG: gradeData.fridaySeventhLessonTeacherSG,
            fridaySeventhLessonClassroomSG: gradeData.fridaySeventhLessonClassroomSG,
            fridayEighthLessonFG: gradeData.fridayEighthLessonFG,
            fridayEighthLessonTeacherFG: gradeData.fridayEighthLessonTeacherFG,
            fridayEighthLessonClassroomFG: gradeData.fridayEighthLessonClassroomFG,
            fridayEighthLessonSG: gradeData.fridayEighthLessonSG,
            fridayEighthLessonTeacherSG: gradeData.fridayEighthLessonTeacherSG,
            fridayEighthLessonClassroomSG: gradeData.fridayEighthLessonClassroomSG,
            fridayNinthLessonFG: gradeData.fridayNinthLessonFG,
            fridayNinthLessonTeacherFG: gradeData.fridayNinthLessonTeacherFG,
            fridayNinthLessonClassroomFG: gradeData.fridayNinthLessonClassroomFG,
            fridayNinthLessonSG: gradeData.fridayNinthLessonSG,
            fridayNinthLessonTeacherSG: gradeData.fridayNinthLessonTeacherSG,
            fridayNinthLessonClassroomSG: gradeData.fridayNinthLessonClassroomSG,
            fridayTenthLessonFG: gradeData.fridayTenthLessonFG,
            fridayTenthLessonTeacherFG: gradeData.fridayTenthLessonTeacherFG,
            fridayTenthLessonClassroomFG: gradeData.fridayTenthLessonClassroomFG,
            fridayTenthLessonSG: gradeData.fridayTenthLessonSG,
            fridayTenthLessonTeacherSG: gradeData.fridayTenthLessonTeacherSG,
            fridayTenthLessonClassroomSG: gradeData.fridayTenthLessonClassroomSG,

            saturdayFirstLessonFG: gradeData.saturdayFirstLessonFG,
            saturdayFirstLessonTeacherFG: gradeData.saturdayFirstLessonTeacherFG,
            saturdayFirstLessonClassroomFG: gradeData.saturdayFirstLessonClassroomFG,
            saturdayFirstLessonSG: gradeData.saturdayFirstLessonSG,
            saturdayFirstLessonTeacherSG: gradeData.saturdayFirstLessonTeacherSG,
            saturdayFirstLessonClassroomSG: gradeData.saturdayFirstLessonClassroomSG,
            saturdaySecondLessonFG: gradeData.saturdaySecondLessonFG,
            saturdaySecondLessonTeacherFG: gradeData.saturdaySecondLessonTeacherFG,
            saturdaySecondLessonClassroomFG: gradeData.saturdaySecondLessonClassroomFG,
            saturdaySecondLessonSG: gradeData.saturdaySecondLessonSG,
            saturdaySecondLessonTeacherSG: gradeData.saturdaySecondLessonTeacherSG,
            saturdaySecondLessonClassroomSG: gradeData.saturdaySecondLessonClassroomSG,
            saturdayThirdLessonFG: gradeData.saturdayThirdLessonFG,
            saturdayThirdLessonTeacherFG: gradeData.saturdayThirdLessonTeacherFG,
            saturdayThirdLessonClassroomFG: gradeData.saturdayThirdLessonClassroomFG,
            saturdayThirdLessonSG: gradeData.saturdayThirdLessonSG,
            saturdayThirdLessonTeacherSG: gradeData.saturdayThirdLessonTeacherSG,
            saturdayThirdLessonClassroomSG: gradeData.saturdayThirdLessonClassroomSG,
            saturdayFourthLessonFG: gradeData.saturdayFourthLessonFG,
            saturdayFourthLessonTeacherFG: gradeData.saturdayFourthLessonTeacherFG,
            saturdayFourthLessonClassroomFG: gradeData.saturdayFourthLessonClassroomFG,
            saturdayFourthLessonSG: gradeData.saturdayFourthLessonSG,
            saturdayFourthLessonTeacherSG: gradeData.saturdayFourthLessonTeacherSG,
            saturdayFourthLessonClassroomSG: gradeData.saturdayFourthLessonClassroomSG,
            saturdayFifthLessonFG: gradeData.saturdayFifthLessonFG,
            saturdayFifthLessonTeacherFG: gradeData.saturdayFifthLessonTeacherFG,
            saturdayFifthLessonClassroomFG: gradeData.saturdayFifthLessonClassroomFG,
            saturdayFifthLessonSG: gradeData.saturdayFifthLessonSG,
            saturdayFifthLessonTeacherSG: gradeData.saturdayFifthLessonTeacherSG,
            saturdayFifthLessonClassroomSG: gradeData.saturdayFifthLessonClassroomSG,
            saturdaySixthLessonFG: gradeData.saturdaySixthLessonFG,
            saturdaySixthLessonTeacherFG: gradeData.saturdaySixthLessonTeacherFG,
            saturdaySixthLessonClassroomFG: gradeData.saturdaySixthLessonClassroomFG,
            saturdaySixthLessonSG: gradeData.saturdaySixthLessonSG,
            saturdaySixthLessonTeacherSG: gradeData.saturdaySixthLessonTeacherSG,
            saturdaySixthLessonClassroomSG: gradeData.saturdaySixthLessonClassroomSG,
            saturdaySeventhLessonFG: gradeData.saturdaySeventhLessonFG,
            saturdaySeventhLessonTeacherFG: gradeData.saturdaySeventhLessonTeacherFG,
            saturdaySeventhLessonClassroomFG: gradeData.saturdaySeventhLessonClassroomFG,
            saturdaySeventhLessonSG: gradeData.saturdaySeventhLessonSG,
            saturdaySeventhLessonTeacherSG: gradeData.saturdaySeventhLessonTeacherSG,
            saturdaySeventhLessonClassroomSG: gradeData.saturdaySeventhLessonClassroomSG,
            saturdayEighthLessonFG: gradeData.saturdayEighthLessonFG,
            saturdayEighthLessonTeacherFG: gradeData.saturdayEighthLessonTeacherFG,
            saturdayEighthLessonClassroomFG: gradeData.saturdayEighthLessonClassroomFG,
            saturdayEighthLessonSG: gradeData.saturdayEighthLessonSG,
            saturdayEighthLessonTeacherSG: gradeData.saturdayEighthLessonTeacherSG,
            saturdayEighthLessonClassroomSG: gradeData.saturdayEighthLessonClassroomSG,
            saturdayNinthLessonFG: gradeData.saturdayNinthLessonFG,
            saturdayNinthLessonTeacherFG: gradeData.saturdayNinthLessonTeacherFG,
            saturdayNinthLessonClassroomFG: gradeData.saturdayNinthLessonClassroomFG,
            saturdayNinthLessonSG: gradeData.saturdayNinthLessonSG,
            saturdayNinthLessonTeacherSG: gradeData.saturdayNinthLessonTeacherSG,
            saturdayNinthLessonClassroomSG: gradeData.saturdayNinthLessonClassroomSG,
            saturdayTenthLessonFG: gradeData.saturdayTenthLessonFG,
            saturdayTenthLessonTeacherFG: gradeData.saturdayTenthLessonTeacherFG,
            saturdayTenthLessonClassroomFG: gradeData.saturdayTenthLessonClassroomFG,
            saturdayTenthLessonSG: gradeData.saturdayTenthLessonSG,
            saturdayTenthLessonTeacherSG: gradeData.saturdayTenthLessonTeacherSG,
            saturdayTenthLessonClassroomSG: gradeData.saturdayTenthLessonClassroomSG,
          };
        });
      });
  }

  ngOnDestroy() {
    this.authStatusSub.unsubscribe();
    this.gradesSub.unsubscribe();
    this.subjectsSub.unsubscribe();
  }

}
