const mongoose = require("mongoose");

const gradeSchema = mongoose.Schema({
  gradeNumber: { type: Number, min: 7, max: 12, required: true },
  gradeLiter: { type: String, required: true },

  mondayFirstLessonFG: { type: String },
  mondayFirstLessonTeacherFG: { type: String },
  mondayFirstLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondayFirstLessonSG: { type: String },
  mondayFirstLessonTeacherSG: { type: String },
  mondayFirstLessonClassroomSG: { type: Number, min: 100, max: 400 },
  mondaySecondLessonFG: { type: String },
  mondaySecondLessonTeacherFG: { type: String },
  mondaySecondLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondaySecondLessonSG: { type: String },
  mondaySecondLessonTeacherSG: { type: String },
  mondaySecondLessonClassroomSG: { type: Number, min: 100, max: 400 },
  mondayThirdLessonFG: { type: String },
  mondayThirdLessonTeacherFG: { type: String },
  mondayThirdLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondayThirdLessonSG: { type: String },
  mondayThirdLessonTeacherSG: { type: String },
  mondayThirdLessonClassroomSG: { type: Number, min: 100, max: 400 },
  mondayFourthLessonFG: { type: String },
  mondayFourthLessonTeacherFG: { type: String },
  mondayFourthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondayFourthLessonSG: { type: String },
  mondayFourthLessonTeacherSG: { type: String },
  mondayFourthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  mondayFifthLessonFG: { type: String },
  mondayFifthLessonTeacherFG: { type: String },
  mondayFifthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondayFifthLessonSG: { type: String },
  mondayFifthLessonTeacherSG: { type: String },
  mondayFifthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  mondaySixthLessonFG: { type: String },
  mondaySixthLessonTeacherFG: { type: String },
  mondaySixthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondaySixthLessonSG: { type: String },
  mondaySixthLessonTeacherSG: { type: String },
  mondaySixthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  mondaySeventhLessonFG: { type: String },
  mondaySeventhLessonTeacherFG: { type: String },
  mondaySeventhLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondaySeventhLessonSG: { type: String },
  mondaySeventhLessonTeacherSG: { type: String },
  mondaySeventhLessonClassroomSG: { type: Number, min: 100, max: 400 },
  mondayEighthLessonFG: { type: String },
  mondayEighthLessonTeacherFG: { type: String },
  mondayEighthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondayEighthLessonSG: { type: String },
  mondayEighthLessonTeacherSG: { type: String },
  mondayEighthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  mondayNinthLessonFG: { type: String },
  mondayNinthLessonTeacherFG: { type: String },
  mondayNinthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondayNinthLessonSG: { type: String },
  mondayNinthLessonTeacherSG: { type: String },
  mondayNinthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  mondayTenthLessonFG: { type: String },
  mondayTenthLessonTeacherFG: { type: String },
  mondayTenthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  mondayTenthLessonSG: { type: String },
  mondayTenthLessonTeacherSG: { type: String },
  mondayTenthLessonClassroomSG: { type: Number, min: 100, max: 400 },

  tuesdayFirstLessonFG: { type: String },
  tuesdayFirstLessonTeacherFG: { type: String },
  tuesdayFirstLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdayFirstLessonSG: { type: String },
  tuesdayFirstLessonTeacherSG: { type: String },
  tuesdayFirstLessonClassroomSG: { type: Number, min: 100, max: 400 },
  tuesdaySecondLessonFG: { type: String },
  tuesdaySecondLessonTeacherFG: { type: String },
  tuesdaySecondLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdaySecondLessonSG: { type: String },
  tuesdaySecondLessonTeacherSG: { type: String },
  tuesdaySecondLessonClassroomSG: { type: Number, min: 100, max: 400 },
  tuesdayThirdLessonFG: { type: String },
  tuesdayThirdLessonTeacherFG: { type: String },
  tuesdayThirdLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdayThirdLessonSG: { type: String },
  tuesdayThirdLessonTeacherSG: { type: String },
  tuesdayThirdLessonClassroomSG: { type: Number, min: 100, max: 400 },
  tuesdayFourthLessonFG: { type: String },
  tuesdayFourthLessonTeacherFG: { type: String },
  tuesdayFourthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdayFourthLessonSG: { type: String },
  tuesdayFourthLessonTeacherSG: { type: String },
  tuesdayFourthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  tuesdayFifthLessonFG: { type: String },
  tuesdayFifthLessonTeacherFG: { type: String },
  tuesdayFifthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdayFifthLessonSG: { type: String },
  tuesdayFifthLessonTeacherSG: { type: String },
  tuesdayFifthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  tuesdaySixthLessonFG: { type: String },
  tuesdaySixthLessonTeacherFG: { type: String },
  tuesdaySixthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdaySixthLessonSG: { type: String },
  tuesdaySixthLessonTeacherSG: { type: String },
  tuesdaySixthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  tuesdaySeventhLessonFG: { type: String },
  tuesdaySeventhLessonTeacherFG: { type: String },
  tuesdaySeventhLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdaySeventhLessonSG: { type: String },
  tuesdaySeventhLessonTeacherSG: { type: String },
  tuesdaySeventhLessonClassroomSG: { type: Number, min: 100, max: 400 },
  tuesdayEighthLessonFG: { type: String },
  tuesdayEighthLessonTeacherFG: { type: String },
  tuesdayEighthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdayEighthLessonSG: { type: String },
  tuesdayEighthLessonTeacherSG: { type: String },
  tuesdayEighthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  tuesdayNinthLessonFG: { type: String },
  tuesdayNinthLessonTeacherFG: { type: String },
  tuesdayNinthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdayNinthLessonSG: { type: String },
  tuesdayNinthLessonTeacherSG: { type: String },
  tuesdayNinthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  tuesdayTenthLessonFG: { type: String },
  tuesdayTenthLessonTeacherFG: { type: String },
  tuesdayTenthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  tuesdayTenthLessonSG: { type: String },
  tuesdayTenthLessonTeacherSG: { type: String },
  tuesdayTenthLessonClassroomSG: { type: Number, min: 100, max: 400 },

  wednesdayFirstLessonFG: { type: String },
  wednesdayFirstLessonTeacherFG: { type: String },
  wednesdayFirstLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdayFirstLessonSG: { type: String },
  wednesdayFirstLessonTeacherSG: { type: String },
  wednesdayFirstLessonClassroomSG: { type: Number, min: 100, max: 400 },
  wednesdaySecondLessonFG: { type: String },
  wednesdaySecondLessonTeacherFG: { type: String },
  wednesdaySecondLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdaySecondLessonSG: { type: String },
  wednesdaySecondLessonTeacherSG: { type: String },
  wednesdaySecondLessonClassroomSG: { type: Number, min: 100, max: 400 },
  wednesdayThirdLessonFG: { type: String },
  wednesdayThirdLessonTeacherFG: { type: String },
  wednesdayThirdLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdayThirdLessonSG: { type: String },
  wednesdayThirdLessonTeacherSG: { type: String },
  wednesdayThirdLessonClassroomSG: { type: Number, min: 100, max: 400 },
  wednesdayFourthLessonFG: { type: String },
  wednesdayFourthLessonTeacherFG: { type: String },
  wednesdayFourthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdayFourthLessonSG: { type: String },
  wednesdayFourthLessonTeacherSG: { type: String },
  wednesdayFourthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  wednesdayFifthLessonFG: { type: String },
  wednesdayFifthLessonTeacherFG: { type: String },
  wednesdayFifthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdayFifthLessonSG: { type: String },
  wednesdayFifthLessonTeacherSG: { type: String },
  wednesdayFifthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  wednesdaySixthLessonFG: { type: String },
  wednesdaySixthLessonTeacherFG: { type: String },
  wednesdaySixthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdaySixthLessonSG: { type: String },
  wednesdaySixthLessonTeacherSG: { type: String },
  wednesdaySixthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  wednesdaySeventhLessonFG: { type: String },
  wednesdaySeventhLessonTeacherFG: { type: String },
  wednesdaySeventhLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdaySeventhLessonSG: { type: String },
  wednesdaySeventhLessonTeacherSG: { type: String },
  wednesdaySeventhLessonClassroomSG: { type: Number, min: 100, max: 400 },
  wednesdayEighthLessonFG: { type: String },
  wednesdayEighthLessonTeacherFG: { type: String },
  wednesdayEighthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdayEighthLessonSG: { type: String },
  wednesdayEighthLessonTeacherSG: { type: String },
  wednesdayEighthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  wednesdayNinthLessonFG: { type: String },
  wednesdayNinthLessonTeacherFG: { type: String },
  wednesdayNinthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdayNinthLessonSG: { type: String },
  wednesdayNinthLessonTeacherSG: { type: String },
  wednesdayNinthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  wednesdayTenthLessonFG: { type: String },
  wednesdayTenthLessonTeacherFG: { type: String },
  wednesdayTenthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  wednesdayTenthLessonSG: { type: String },
  wednesdayTenthLessonTeacherSG: { type: String },
  wednesdayTenthLessonClassroomSG: { type: Number, min: 100, max: 400 },

  thursdayFirstLessonFG: { type: String },
  thursdayFirstLessonTeacherFG: { type: String },
  thursdayFirstLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdayFirstLessonSG: { type: String },
  thursdayFirstLessonTeacherSG: { type: String },
  thursdayFirstLessonClassroomSG: { type: Number, min: 100, max: 400 },
  thursdaySecondLessonFG: { type: String },
  thursdaySecondLessonTeacherFG: { type: String },
  thursdaySecondLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdaySecondLessonSG: { type: String },
  thursdaySecondLessonTeacherSG: { type: String },
  thursdaySecondLessonClassroomSG: { type: Number, min: 100, max: 400 },
  thursdayThirdLessonFG: { type: String },
  thursdayThirdLessonTeacherFG: { type: String },
  thursdayThirdLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdayThirdLessonSG: { type: String },
  thursdayThirdLessonTeacherSG: { type: String },
  thursdayThirdLessonClassroomSG: { type: Number, min: 100, max: 400 },
  thursdayFourthLessonFG: { type: String },
  thursdayFourthLessonTeacherFG: { type: String },
  thursdayFourthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdayFourthLessonSG: { type: String },
  thursdayFourthLessonTeacherSG: { type: String },
  thursdayFourthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  thursdayFifthLessonFG: { type: String },
  thursdayFifthLessonTeacherFG: { type: String },
  thursdayFifthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdayFifthLessonSG: { type: String },
  thursdayFifthLessonTeacherSG: { type: String },
  thursdayFifthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  thursdaySixthLessonFG: { type: String },
  thursdaySixthLessonTeacherFG: { type: String },
  thursdaySixthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdaySixthLessonSG: { type: String },
  thursdaySixthLessonTeacherSG: { type: String },
  thursdaySixthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  thursdaySeventhLessonFG: { type: String },
  thursdaySeventhLessonTeacherFG: { type: String },
  thursdaySeventhLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdaySeventhLessonSG: { type: String },
  thursdaySeventhLessonTeacherSG: { type: String },
  thursdaySeventhLessonClassroomSG: { type: Number, min: 100, max: 400 },
  thursdayEighthLessonFG: { type: String },
  thursdayEighthLessonTeacherFG: { type: String },
  thursdayEighthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdayEighthLessonSG: { type: String },
  thursdayEighthLessonTeacherSG: { type: String },
  thursdayEighthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  thursdayNinthLessonFG: { type: String },
  thursdayNinthLessonTeacherFG: { type: String },
  thursdayNinthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdayNinthLessonSG: { type: String },
  thursdayNinthLessonTeacherSG: { type: String },
  thursdayNinthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  thursdayTenthLessonFG: { type: String },
  thursdayTenthLessonTeacherFG: { type: String },
  thursdayTenthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  thursdayTenthLessonSG: { type: String },
  thursdayTenthLessonTeacherSG: { type: String },
  thursdayTenthLessonClassroomSG: { type: Number, min: 100, max: 400 },

  fridayFirstLessonFG: { type: String },
  fridayFirstLessonTeacherFG: { type: String },
  fridayFirstLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridayFirstLessonSG: { type: String },
  fridayFirstLessonTeacherSG: { type: String },
  fridayFirstLessonClassroomSG: { type: Number, min: 100, max: 400 },
  fridaySecondLessonFG: { type: String },
  fridaySecondLessonTeacherFG: { type: String },
  fridaySecondLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridaySecondLessonSG: { type: String },
  fridaySecondLessonTeacherSG: { type: String },
  fridaySecondLessonClassroomSG: { type: Number, min: 100, max: 400 },
  fridayThirdLessonFG: { type: String },
  fridayThirdLessonTeacherFG: { type: String },
  fridayThirdLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridayThirdLessonSG: { type: String },
  fridayThirdLessonTeacherSG: { type: String },
  fridayThirdLessonClassroomSG: { type: Number, min: 100, max: 400 },
  fridayFourthLessonFG: { type: String },
  fridayFourthLessonTeacherFG: { type: String },
  fridayFourthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridayFourthLessonSG: { type: String },
  fridayFourthLessonTeacherSG: { type: String },
  fridayFourthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  fridayFifthLessonFG: { type: String },
  fridayFifthLessonTeacherFG: { type: String },
  fridayFifthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridayFifthLessonSG: { type: String },
  fridayFifthLessonTeacherSG: { type: String },
  fridayFifthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  fridaySixthLessonFG: { type: String },
  fridaySixthLessonTeacherFG: { type: String },
  fridaySixthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridaySixthLessonSG: { type: String },
  fridaySixthLessonTeacherSG: { type: String },
  fridaySixthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  fridaySeventhLessonFG: { type: String },
  fridaySeventhLessonTeacherFG: { type: String },
  fridaySeventhLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridaySeventhLessonSG: { type: String },
  fridaySeventhLessonTeacherSG: { type: String },
  fridaySeventhLessonClassroomSG: { type: Number, min: 100, max: 400 },
  fridayEighthLessonFG: { type: String },
  fridayEighthLessonTeacherFG: { type: String },
  fridayEighthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridayEighthLessonSG: { type: String },
  fridayEighthLessonTeacherSG: { type: String },
  fridayEighthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  fridayNinthLessonFG: { type: String },
  fridayNinthLessonTeacherFG: { type: String },
  fridayNinthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridayNinthLessonSG: { type: String },
  fridayNinthLessonTeacherSG: { type: String },
  fridayNinthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  fridayTenthLessonFG: { type: String },
  fridayTenthLessonTeacherFG: { type: String },
  fridayTenthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  fridayTenthLessonSG: { type: String },
  fridayTenthLessonTeacherSG: { type: String },
  fridayTenthLessonClassroomSG: { type: Number, min: 100, max: 400 },

  saturdayFirstLessonFG: { type: String },
  saturdayFirstLessonTeacherFG: { type: String },
  saturdayFirstLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdayFirstLessonSG: { type: String },
  saturdayFirstLessonTeacherSG: { type: String },
  saturdayFirstLessonClassroomSG: { type: Number, min: 100, max: 400 },
  saturdaySecondLessonFG: { type: String },
  saturdaySecondLessonTeacherFG: { type: String },
  saturdaySecondLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdaySecondLessonSG: { type: String },
  saturdaySecondLessonTeacherSG: { type: String },
  saturdaySecondLessonClassroomSG: { type: Number, min: 100, max: 400 },
  saturdayThirdLessonFG: { type: String },
  saturdayThirdLessonTeacherFG: { type: String },
  saturdayThirdLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdayThirdLessonSG: { type: String },
  saturdayThirdLessonTeacherSG: { type: String },
  saturdayThirdLessonClassroomSG: { type: Number, min: 100, max: 400 },
  saturdayFourthLessonFG: { type: String },
  saturdayFourthLessonTeacherFG: { type: String },
  saturdayFourthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdayFourthLessonSG: { type: String },
  saturdayFourthLessonTeacherSG: { type: String },
  saturdayFourthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  saturdayFifthLessonFG: { type: String },
  saturdayFifthLessonTeacherFG: { type: String },
  saturdayFifthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdayFifthLessonSG: { type: String },
  saturdayFifthLessonTeacherSG: { type: String },
  saturdayFifthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  saturdaySixthLessonFG: { type: String },
  saturdaySixthLessonTeacherFG: { type: String },
  saturdaySixthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdaySixthLessonSG: { type: String },
  saturdaySixthLessonTeacherSG: { type: String },
  saturdaySixthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  saturdaySeventhLessonFG: { type: String },
  saturdaySeventhLessonTeacherFG: { type: String },
  saturdaySeventhLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdaySeventhLessonSG: { type: String },
  saturdaySeventhLessonTeacherSG: { type: String },
  saturdaySeventhLessonClassroomSG: { type: Number, min: 100, max: 400 },
  saturdayEighthLessonFG: { type: String },
  saturdayEighthLessonTeacherFG: { type: String },
  saturdayEighthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdayEighthLessonSG: { type: String },
  saturdayEighthLessonTeacherSG: { type: String },
  saturdayEighthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  saturdayNinthLessonFG: { type: String },
  saturdayNinthLessonTeacherFG: { type: String },
  saturdayNinthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdayNinthLessonSG: { type: String },
  saturdayNinthLessonTeacherSG: { type: String },
  saturdayNinthLessonClassroomSG: { type: Number, min: 100, max: 400 },
  saturdayTenthLessonFG: { type: String },
  saturdayTenthLessonTeacherFG: { type: String },
  saturdayTenthLessonClassroomFG: { type: Number, min: 100, max: 400 },
  saturdayTenthLessonSG: { type: String },
  saturdayTenthLessonTeacherSG: { type: String },
  saturdayTenthLessonClassroomSG: { type: Number, min: 100, max: 400 },
});

module.exports = mongoose.model("Grade", gradeSchema);
